### ISSUE TITLE
是否考虑可以自定义通知方式？

### ISSUE THREAD

**Issue by hhhkkk520** [FranzKafkaYu/x-ui#1]
您好，

感谢您增加了TG机器人通知的功能，这是很棒很实用的功能！
想提出一个小小的建议，是否可以考虑做成可以自定义的方式呢？

例如：用户可以自定义采取POST或GET的方式请求、以JSON类型请求、可以自定义Header、自定义Body

这样的好处是可以很灵活地满足目前绝大部份的通知方式，包括并且不仅限于TG、wxpusher、Server酱，毕竟还有很大一部分用户不使用TG

再次感谢您的贡献，如果您认为这条建议没有价值，您可以随时关闭这条Issue

**Comment by FranzKafkaYu** [comment]
暂时还未考虑，目前想的是先实现一种通知方式，在此基础上尽可能拓展功能，后续再考虑拓展其他的通知方式。

**Comment by hhhkkk520** [comment]
谢谢您的回复
