### ISSUE TITLE
大佬这是什么问题？

### ISSUE THREAD

**Issue by 2399483979** [FranzKafkaYu/x-ui#10]
[ERR] 面板启动失败，可能是因为启动时间超过了两秒，请稍后查看日志信息
日志：May 08 16:31:00 root systemd[1]: x-ui.service: main process exited, code=exited, status=1/FAILURE
May 08 16:31:00 root systemd[1]: Unit x-ui.service entered failed state.
May 08 16:31:00 root systemd[1]: x-ui.service failed.

**Comment by FranzKafkaYu** [comment]
请提供一下面板的版本以及你系统相关的信息

**Comment by FranzKafkaYu** [comment]
无任何有效信息，暂时关闭该issue
