### ISSUE TITLE
无法使用证书连接

### ISSUE THREAD

**Issue by SugarFatFree** [FranzKafkaYu/x-ui#100]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

已使用方式1生成SSL证书，生成时配置的是443端口，无法进行连接
![@5$G{$(4ZBXUNTUX{06G$C1](https://user-images.githubusercontent.com/30424828/196625341-e14cd4a9-8c95-410b-af6b-065efa69a7de.png)

### Version of x-ui

<details>

```console
$ x-ui version
0.3.3.16:20220814
```

</details>

### x-ui log or xray log

<details>

```console
无
```

</details>

**Comment by FranzKafkaYu** [comment]
@SugarFatFree 1.是否使用多个客户端进行测试，比如Win/Android等 2.是否确认对应端口有开放  3.公钥文件尽量使用fullchain.cer 4.路径设置尽量不要为"/"

**Comment by SugarFatFree** [comment]
使用fullchain.cer 成功连接，感谢

**Comment by Jerry-Young-23** [comment]
> 使用fullchain.cer 成功连接，感谢

确实，如果使用普通的证书，在电脑端用v2rayn正常连接，安卓端v2rayng无法正常连接。使用fullchain后，电脑安卓均正常连接
