### ISSUE TITLE
ios is not working

### ISSUE THREAD

**Issue by shahrooz1349** [FranzKafkaYu/x-ui#103]
hi dear development 
Thanks for this nice script 
I changed from the original version to your version
Everything is fine in Android and Windows, but in iOS it connects but does not download
Tested in centos and ubuntu, the problem still exists

@FranzKafkaYu  Regard

**Comment by FranzKafkaYu** [comment]
> hi dear development Thanks for this nice script I changed from the original version to your version Everything is fine in Android and Windows, but in iOS it connects but does not download Tested in centos and ubuntu, the problem still exists
> 
> @FranzKafkaYu Regard

@shahrooz1349 Which protocol do you use?And what client app do you use in iOS?

**Comment by shahrooz1349** [comment]
@FranzKafkaYu 
protocol: vmess
transmission: ws
app is  "one click vpn" for ios

**Comment by FranzKafkaYu** [comment]
> one click vpn

@shahrooz1349 plz try to use **shadowrocket** instead.

**Comment by shahrooz1349** [comment]
@ok tnx dear
