### ISSUE TITLE
切换xray版本到v1.6.0后打不开面板

### ISSUE THREAD

**Issue by zhucaidan** [FranzKafkaYu/x-ui#104]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

切换xray版本到v1.6.0后打不开面板
系统为Debian 11 amd64
切换后打开面板首页提示 404 page not found

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
https://github.com/FranzKafkaYu/x-ui/issues/78
