### ISSUE TITLE
x-ui登錄後一片空白

### ISSUE THREAD

**Issue by cwyin7788** [FranzKafkaYu/x-ui#105]
ARM64处理器，debian 11，从原版x-ui升级，在登录页面输入ID密码登录后一片空白，Mac的safari、ios的safari / chrome都一样  试过移除装回原版，登录后一切正常  然后，移除原版再装这个版本，还是有相同问题

thanks

**Comment by FranzKafkaYu** [comment]
> ARM64处理器，debian 11，从原版x-ui升级，在登录页面输入ID密码登录后一片空白，Mac的safari、ios的safari / chrome都一样 试过移除装回原版，登录后一切正常 然后，移除原版再装这个版本，还是有相同问题
> 
> thanks

@cwyin7788 首先确保x-ui运行正常，在此前提下：如果单纯是页面空白，请尝试清除浏览器缓存与Cookie后（或更换其他之前未登陆过的浏览器）再行登录，如果是`404 not found`错误,请查看WIKI文档

**Comment by cwyin7788** [comment]
> > ARM64处理器，debian 11，从原版x-ui升级，在登录页面输入ID密码登录后一片空白，Mac的safari、ios的safari / chrome都一样 试过移除装回原版，登录后一切正常 然后，移除原版再装这个版本，还是有相同问题
> 
> > 
> 
> > thanks
> 
> 
> 
> @cwyin7788 首先确保x-ui运行正常，在此前提下：如果单纯是页面空白，请尝试清除浏览器缓存与Cookie后（或更换其他之前未登陆过的浏览器）再行登录，如果是`404 not found`错误,请查看WIKI文档

谢谢闪电回覆，已经确认你这个版本的x-ui在正常运行，service x-ui status，見到正常运行，日志里也没见到错误，我已清空了ios里的safari / chrome的缓存，亦分别以safari的私密浏览、chrome的无痕浏览登录过，全都一样，在登录页面登录后，就是一片空白，试过在公司之前没登录过的一台mac电脑safari登录，也是一样

把你这个移除后再装回原版的，登录后又一切正常

是一片空白，不是404

**Comment by doutuo** [comment]
备份原版的 x-ui.db  然后 重新安装作者这版的，先不替换数据库，试下是否能打开，若能打开，再替换数据库试试

**Comment by doutuo** [comment]
备份x-ui.db后，系统记得重新安装

**Comment by cwyin7788** [comment]
> 备份x-ui.db后，系统记得重新安装

要重新安装系统？🤔️

**Comment by ayunhe** [comment]
同样问题，只要点了面板设置，网页就变成空白，这版有问题

**Comment by FranzKafkaYu** [comment]
> 同样问题，只要点了面板设置，网页就变成空白，这版有问题

@ayunhe 确定点击面板设置后会变成空白，还是`404 not found`，如果是后者请自行查看WIKI.另外是否通过其他浏览器，包括手机端进行测试，这些信息都很重要.

**Comment by FranzKafkaYu** [comment]
@ayunhe 可以尝试最新版本：https://github.com/FranzKafkaYu/x-ui/releases/tag/0.3.3.17

**Comment by Jerry-Young-23** [comment]
> 同样问题，只要点了面板设置，网页就变成空白，这版有问题

不一定是面板的问题，这个面板加入了新特性：第一次登录后自动生成面板根路径。意味着网站的url变了，点击面板设置后自然就显示不出来了。正确的做法是找到面板的路径，在浏览器输入http://+域名+面板端口+面板路径。

**Comment by FranzKafkaYu** [comment]
No more feedback,close as solved.
