### ISSUE TITLE
希望添加多用户分别统计流量

### ISSUE THREAD

**Issue by Jerry-Young-23** [FranzKafkaYu/x-ui#107]
目前虽然实现了单端口多用户功能，但流量统计依然只支持单端口统计，无法实习多用户分别统计，故希望添加多用户分别统计流量，限制流量，时间的功能

**Comment by FranzKafkaYu** [comment]
@mahdigh00 If you just wanna make a proxy for you and your friends,it is useful.If you want to make it as professional proxy manager and want to make money from it, it's useless.

**Comment by mahdigh00** [comment]
> @mahdigh00 If you just wanna make a proxy for you and your friends,it is useful.If you want to make it as professional proxy manager and want to make money from it, it's useless.

what different between 'get them all one link and one user' and 'make a user for every person' when you can't track users?
you can send for all of  your friends one link with one uuid.
there is bad internet situation in Iran and I want setup proxy for our employees in company because our programmers desperately need the Internet to continue their work. but because of this situation if too much people use this server and they suspect this server, they ban server IP address and it's annoying to change IP every day!
we want to only our employees use this proxy and don't share with other peoples, but i didn't get point of user managing for every inbound without any limit or observation system.

**Comment by Argo160** [comment]
Thank You Franz for the effort.
by single port and multi users, do you mean to create a single account for everyone?
because the it doesn't allow to make multi users with the same port!!

**Comment by FranzKafkaYu** [comment]
> ow to make multi users with th

@Argo160  did you try?It do support multi users with the same port but I have made a restriction that only maxium 3 users can create.

**Comment by mahdigh00** [comment]
> > > @mahdigh00 If you just wanna make a proxy for you and your friends,it is useful.If you want to make it as professional proxy manager and want to make money from it, it's useless.
> > 
> > 
> > what different between 'get them all one link and one user' and 'make a user for every person' when you can't track users? you can send for all of your friends one link with one uuid. there is bad internet situation in Iran and I want setup proxy for our employees in company because our programmers desperately need the Internet to continue their work. but because of this situation if too much people use this server and they suspect this server, they ban server IP address and it's annoying to change IP every day! we want to only our employees use this proxy and don't share with other peoples, but i didn't get point of user managing for every inbound without any limit or observation system.
> 
> `get them all one link and one user`：if one day you don't want one of these users to connect，you have to regenerate a new uuid and the reset of you have to update，but `make a user for every person` if you don‘t want someone to connect，just delete it,it‘s simple and the reset of you don‘t have to update.
> 
> you don't want your user share your proxies,just tell them your rules.And you can track every user's activities by email in logs,you just can't limit each user's traffic and time.if you really need such functions,find other tools instead.


Thank you for your answer. I get the point.
But it can be better if have option to restrict max connection per user or limit usage.
and if there is translation file I'll be happy to help and growth your perfect panel.
Thank you again for fixing problems of this panel.

**Comment by Argo160** [comment]
> 



> > ow to make multi users with th
> 
> @Argo160 did you try?It do support multi users with the same port but I have made a restriction that only maxium 3 users can be added.

Yes

> > ow to make multi users with th
> 
> @Argo160 did you try?It do support multi users with the same port but I have made a restriction that only maxium 3 users can be added.

Yes Franz. I did try it. only one user per ports are allowed. 
you say 3? wondering how
"current port is already in use" keeps pupping up for the second user with the same port

**Comment by Argo160** [comment]
> > > > @mahdigh00 If you just wanna make a proxy for you and your friends,it is useful.If you want to make it as professional proxy manager and want to make money from it, it's useless.
> > > 
> > > 
> > > what different between 'get them all one link and one user' and 'make a user for every person' when you can't track users? you can send for all of your friends one link with one uuid. there is bad internet situation in Iran and I want setup proxy for our employees in company because our programmers desperately need the Internet to continue their work. but because of this situation if too much people use this server and they suspect this server, they ban server IP address and it's annoying to change IP every day! we want to only our employees use this proxy and don't share with other peoples, but i didn't get point of user managing for every inbound without any limit or observation system.
> > 
> > 
> > `get them all one link and one user`：if one day you don't want one of these users to connect，you have to regenerate a new uuid and the reset of you have to update，but `make a user for every person` if you don‘t want someone to connect，just delete it,it‘s simple and the reset of you don‘t have to update.
> > you don't want your user share your proxies,just tell them your rules.And you can track every user's activities by email in logs,you just can't limit each user's traffic and time.if you really need such functions,find other tools instead.
> 
> Thank you for your answer. I get the point. But it can be better if have option to restrict max connection per user or limit usage. and if there is translation file I'll be happy to help and growth your perfect panel. Thank you again for fixing problems of this panel.

My guess is, it is not possible to make the max connections  restricted. or they would.
If i get lucky My VPSs are alive only for a week then the ip gets banned. because everyone keeps sharing and government finds it soon.
I ask my friends not to share but they got other friends whom dont have access to the internet so they try to help them and then boom. i can't blame them.
