### ISSUE TITLE
Create unlimited users on exact one port and see the each user traffic usage

### ISSUE THREAD

**Issue by m2tts2001** [FranzKafkaYu/x-ui#108]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Please add this feature to the next version
Creating unlimited users on exact one port for example port 80. Also I need to know each single user traffic usage. 
In current version we can only create 3 users on one port and the total traffic usage of these 3 users not separately. 
So this would be cool if we could see the each user traffic usage. 
Also it would be interesting if we could limit each users at the specific traffic. 
Thank you for your effort and ambitious. 

### Version of x-ui

Ubuntu 20

### x-ui log or xray log

Nothing

**Comment by miladrajabi2002** [comment]
i need it

**Comment by FranzKafkaYu** [comment]
> i need it

If you really need such function, please find other tools.
