### ISSUE TITLE
can not add new user

### ISSUE THREAD

**Issue by kasraak** [FranzKafkaYu/x-ui#109]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

firt thank you for your great service ! 

i would like to ask you i have a problem , when i add new user and im tryng to copy the link it doesnt work and when i try to generate new qr code it shows the following error  

" Failed to get QR code
The current node has not yet added a user, please add a user"

coud you please help me to solve this issue please ?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
![image](https://user-images.githubusercontent.com/38254177/197342313-7ed37f6e-854d-413a-b2b4-3255ebd0e867.png)  

@kasraak Are you sure you have added a user?

**Comment by kasraak** [comment]
yes its checked
