### ISSUE TITLE
Total User Connection per vmess port

### ISSUE THREAD

**Issue by einkaaf** [FranzKafkaYu/x-ui#111]
Hi ,
I have 2more question @FranzKafkaYu ! I hope you answer me again <3 

1. How see connected user ( or device ) per port  (Total User per Vmess)? Could you implement this in inbound list please ?
2. Could you implement api for (Create user, delete user, server status , ...) ?
 I will appreciate if you can implement this feature <3

**Comment by FranzKafkaYu** [comment]
@einkaaf Sorry. I have no plan to do that.

**Comment by einkaaf** [comment]
> @einkaaf Sorry. I have no plan to do that.

how about first one ? is it possible to see ?
