### ISSUE TITLE
Only one user(device) per inbound

### ISSUE THREAD

**Issue by sarahtuska** [FranzKafkaYu/x-ui#112]
hi. thx for amazing script
i have one issue : how can i set each QrCode im generating only allow one device connected to it only one . cause my friend use the same code and share with lots of people and server always under lots of pressure . is there any way that i can generate inbound for only one person and only one device allow to connect .
MerC

**Comment by FranzKafkaYu** [comment]
Once again,x-ui is designed for personal use，and I will never implement such functions here.

**Comment by abraham-sah** [comment]
Thanks

**Comment by hellofr13nd** [comment]
We can now define 3,5,10 users for an inbound now but only the first user gets a QRcode, which make defining multi users for an inbound useless.

**Comment by FranzKafkaYu** [comment]
@hellofr13nd inbounds->check->copy link,each user has a sharing link and QRCode.

**Comment by hellofr13nd** [comment]
@FranzKafkaYu Also thanks for the great panel. 🙏
