### ISSUE TITLE
traffic calculation issue

### ISSUE THREAD

**Issue by smartcdn** [FranzKafkaYu/x-ui#114]
Hi, 

It just calculates the users outbound traffic and not the inbound (Only user's uploaded data is being calculated).

Thanks in advance

**Comment by FranzKafkaYu** [comment]
@smartcdn Upload traffic will be passed through outbounds,and Download traffic will be passed through to inbounds.So all inbounds / outbounds traffic will be calculated.And actually you don't have to distinguish outbounds/inbounds,it may confused.Just upload and download will be good.

**Comment by smartcdn** [comment]
Just for clarification, when we limit a user's traffic for example to 1GB, the X-UI doesn't compare the user's download data with that traffic limit, it compares the upload traffic which is incorrect... .

**Comment by smartcdn** [comment]
The code by vaxilu doesn't have this issue, i'll need to look into the code to find out why...

**Comment by FranzKafkaYu** [comment]
> The code by vaxilu doesn't have this issue, i'll need to look into the code to find out why...

@smartcdn it seems only you have encountered this problem.

**Comment by FranzKafkaYu** [comment]
@smartcdn  are you using the lastest version?it seems have such bug,old version works fine.I am looking it.

**Comment by max4444** [comment]
Thanks for looking into the issue. yeah latest version...

**Comment by FranzKafkaYu** [comment]
@max4444 @smartcdn fixed，please re-install the latest version

**Comment by smartcdn** [comment]
Well done, it's all good now :)
