### ISSUE TITLE
user can ony connect via 1 device

### ISSUE THREAD

**Issue by kasraak** [FranzKafkaYu/x-ui#116]
![Untitled](https://user-images.githubusercontent.com/116443214/197409752-63d69e08-e172-4469-8522-d16bac9cd65c.png)
dear 

i would like to ask you how is possible to limit a user to connect only with one device to one port

i mean when i create a user "x" with the port 12345 can only connect to the port only with one device and one client can use each port and can not share with anyone else 

kindly find the screenshot of user settings attached
![Uploading Untitled.jpg…]()

**Comment by FranzKafkaYu** [comment]
Impossible.
