### ISSUE TITLE
Base path changes to some random strings after restart

### ISSUE THREAD

**Issue by smartcdn** [FranzKafkaYu/x-ui#117]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Whenever i perform  a panel restart (whether from command line or panel GUI), it adds a random string to the BasePath so the panel becomes unreachable. here is the output when i check panel info from terminal:

please input a legal number[0-16]: 7
[INF] 当前面板信息[current panel info]:
面板版本[version]: 0.3.3.17:20221024
用户名[username]: admin
密码[userpasswd]: ********
监听端口[port]: 54321
根路径[basePath]: /t5fc/ 

That base path is added by error, now when i try to open the panel, it keeps showing up 404 page not found

> I can confirm it is reachable through that new created Basepath, but why should it create new basepath's after panel restart?

Thank you

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@smartcdn you mean this version will generate a random bathPath when you restart panel every time？I can’t reproduce this problem and the mechanism for generating random path only when you have set base path to "/".

**Comment by smartcdn** [comment]
I just did a few more panel restarts and it looks like only when the BasePath is set to /  that will happen , so is that normal?

**Comment by FranzKafkaYu** [comment]
> I just did a few more panel restarts and it looks like only when the BasePath is set to / that will happen , so is that normal?

yes,this is for security concern,we donn't allow '/' as base path here.
