### ISSUE TITLE
Error: 404 page not found

### ISSUE THREAD

**Issue by MJamshidnejad** [FranzKafkaYu/x-ui#118]
I just installed the panel in Ubuntu 22.04. Everything was ok. but suddenly I got "404 page not found" on the browser page. 
I changed the port and restart the panel but I still doesn't work.

**Comment by FranzKafkaYu** [comment]
@MJamshidnejad Why not check issues and WIKI  document first?

**Comment by MJamshidnejad** [comment]
I checked. I couldn't find anything that point to this error. I reset panel and restart x-ui it got ok. but when I click on setting page error was displayed again.

**Comment by FranzKafkaYu** [comment]
@MJamshidnejad https://github.com/FranzKafkaYu/x-ui/wiki/Login

**Comment by MJamshidnejad** [comment]
Oh my bad! Sorry! and Thanks :)
