### ISSUE TITLE
Not working on mobile device

### ISSUE THREAD

**Issue by Dev-learn1** [FranzKafkaYu/x-ui#121]
Hello
i installed latest version of x-ui EN and created user on it and connected with v2rayn on pc but i cann't connect to my server on ios (tried oneclick, fairvpn, shadowlink)
may you help me?

PS: i have another server with xray 1.4.2 on it and working great with all devices but the lowest version on this script is v1.5.2

**Comment by FranzKafkaYu** [comment]
@Dev-learn1 Try v2rayNG,and if you enabled TLS, please use fullchain.cer

**Comment by FranzKafkaYu** [comment]
> there is no v2ray app for ios and it's simplest setting (no tls) ![Screenshot 2022-10-24 164457](https://user-images.githubusercontent.com/116567934/197534565-3ad260be-b90d-49f9-96ac-f75ad274bf6f.png)

@Dev-learn1 try ShadowRocket

**Comment by FranzKafkaYu** [comment]
Maybe you should ask these Client APP developers.Normally if v2rayN can connect,the server  is working well.
