### ISSUE TITLE
404 page not found error

### ISSUE THREAD

**Issue by seramo** [FranzKafkaYu/x-ui#122]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

after some time it gives a not found error when loading the page

x.x.x.x:8585/xui/setting
404 page not found

### Version of x-ui

The command has no output

### x-ui log or xray log

No journal files were found.

**Comment by seramo** [comment]
Os: Ubuntu 22.04 (LTS) x64
Ram: 1GB
Cpu: 1Core
Disk: 25GB

**Comment by FranzKafkaYu** [comment]
#118
