### ISSUE TITLE
trojan tcp+tls 模式下 部分网站证书报错

### ISSUE THREAD

**Issue by Meilinhost** [FranzKafkaYu/x-ui#124]
trojan tcp+tls 模式下 部分网站证书报错

测试总分支的脚本同配置 之前打不开的网站正常打开 
应该是trojan配置文件有BUG 

测试错误网址：wudiliu.com

![捕获](https://user-images.githubusercontent.com/3524108/197773591-cd4e2e96-cf26-4691-bdd5-352ab907f433.JPG)

![photo_2022-10-25_20-30-02](https://user-images.githubusercontent.com/3524108/197773651-12074538-ec3f-4420-9477-8bd74ceababf.jpg)

![photo_2022-10-25_18-51-36](https://user-images.githubusercontent.com/3524108/197773903-2896eb65-70c9-4c41-a9b8-fcf283e1b941.jpg)

**Comment by FranzKafkaYu** [comment]
@Meilinhost 请问该网站是否属于国内网站，以及你客户端是否属于全局模式，当前版本的配置模板内已经禁止访问国内的网站/IP

**Comment by Meilinhost** [comment]
> @Meilinhost网站是否属于国内网站以及您客户端是否属于请求配置的网站模式，当前版本的网站/IP是否已经禁止访问国内

我刚刚PING了下，确实是国内网站IP  新版的xui 配置了禁止访问国内网站/IP吗？ 
我试了全局也是打不开的 关掉代理可以打开，或者换其他不是xui搭建的trojan搭建的节点 都能正常访问
现在测试装总分支的版本 一切正常

**Comment by FranzKafkaYu** [comment]
> > @Meilinhost网站是否属于国内网站以及您客户端是否属于请求配置的网站模式，当前版本的网站/IP是否已经禁止访问国内
> 
> 我刚刚PING了下，确实是国内网站IP 新版的xui 配置了禁止访问国内网站/IP吗？ 我试了全局也是打不开的 关掉代理可以打开，或者换其他不是xui搭建的trojan搭建的节点 都能正常访问 现在测试装总分支的版本 一切正常

可以尝试将原版本的配置模板完整替换该版本的配置模板进行验证.

**Comment by Meilinhost** [comment]
> > > @Meilinhost网站是否属于国内网站以及您客户端是否属于请求配置的网站模式，当前版本的网站/IP是否已经禁止访问国内
> > 
> > 
> > 我刚刚PING了下，确实是国内网站IP 新版的xui 配置了禁止访问国内网站/IP吗？ 我试了全局也是打不开的 关掉代理可以打开，或者换其他不是xui搭建的trojan搭建的节点 都能正常访问 现在测试装总分支的版本 一切正常
> 
> 可以尝试将原版本的配置模板完整替换该版本的配置模板进行验证.

目前可以确定是该版本的配置文件有些许问题，导致部分网站证书错误无法访问

**Comment by FranzKafkaYu** [comment]
> > > > @Meilinhost网站是否属于国内网站以及您客户端是否属于请求配置的网站模式，当前版本的网站/IP是否已经禁止访问国内
> > > 
> > > 
> > > 我刚刚PING了下，确实是国内网站IP 新版的xui 配置了禁止访问国内网站/IP吗？ 我试了全局也是打不开的 关掉代理可以打开，或者换其他不是xui搭建的trojan搭建的节点 都能正常访问 现在测试装总分支的版本 一切正常
> > 
> > 
> > 可以尝试将原版本的配置模板完整替换该版本的配置模板进行验证.
> 
> 目前可以确定是该版本的trojan tcp+tls 配置文件有些许问题，导致部分网站证书错误无法访问

或许你可以试试还原一下配置模板试试（使用原版本的配置模板），服务端防止访问国内网站是一个有必要的策略。

**Comment by Meilinhost** [comment]
>或许你可以试试还原一下配置模板试试（使用原版本的配置模板），服务端防止访问国内网站是一个有必要的策略。

好的，防止访问国内网站,有什么说道吗

**Comment by FranzKafkaYu** [comment]
> > 或许你可以试试还原一下配置模板试试（使用原版本的配置模板），服务端防止访问国内网站是一个有必要的策略。
> 
> @FranzKafkaYu 好的，防止访问国内网站,有什么说道吗

https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165

**Comment by Meilinhost** [comment]
> > > 你可以还原一下配置模板（使用原版的配置模板），尝试服务端阻止访问国内网站是一个有必要的策略。
> > 
> > 
> > @FranzKafkaYu好，阻止访问国内网站，有什么办法吗
> 
> [XTLS/Xray-core#593（评论）](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165)

所以就很奇怪 这个ip是国内 我又开的绕过局域网和大陆ip 他居然不绕过直接代理访问

**Comment by FranzKafkaYu** [comment]
> > > > 你可以还原一下配置模板（使用原版的配置模板），尝试服务端阻止访问国内网站是一个有必要的策略。
> > > 
> > > 
> > > @FranzKafkaYu好，阻止访问国内网站，有什么办法吗
> > 
> > 
> > [XTLS/Xray-core#593（评论）](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165)
> 
> 所以就很奇怪 这个ip是国内 我又开的绕过局域网和大陆ip 他居然不绕过直接代理访问

跟你客户端的geo数据有关系，考虑更新一下，或者直接在服务端去掉限制(不推荐)

**Comment by aawwsslll** [comment]
这个直接干掉不让访问国内的ip,会导致无法使用挂梯子看tiktok。
希望可以取消默认，或者设置给个开关啥的。
