### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by EdenSpire** [FranzKafkaYu/x-ui#127]
Hello,

Everytime I access inbound menu / setting, the page will load a bit longer then throw 404 error afterwards.

I can not do anything (it will say error 404, even I restarted the vps or the x-ui), beside change the port to other port.

I have used English and Chinese version.

Any help is appreciate.

Thanks

**Comment by mohsenr7596** [comment]
You must read doc first,
Anyway , in terminal open x-ui console and press 7 for get information of path of x-ui panel

**Comment by mohsenr7596** [comment]
You must read doc first,
Anyway , in terminal open x-ui console and press 7 for get information of path of x-ui panel

**Comment by FranzKafkaYu** [comment]
> Hello,
> 
> Everytime I access inbound menu / setting, the page will load a bit longer then throw 404 error afterwards.
> 
> I can not do anything (it will say error 404, even I restarted the vps or the x-ui), beside change the port to other port.
> 
> I have used English and Chinese version.
> 
> Any help is appreciate.
> 
> Thanks

@EdenSpire why don't you see WIKI or Issues?

**Comment by EdenSpire** [comment]
I thought it was my VPS that caused this, anyway everything has been sorted.

I need to find a way to enable letsencrypt.

**Comment by FranzKafkaYu** [comment]
> I thought it was my VPS that caused this, anyway everything has been sorted.
> 
> I need to find a way to enable letsencrypt.

@
