### ISSUE TITLE
Speed is slower than Wireguard

### ISSUE THREAD

**Issue by EdenSpire** [FranzKafkaYu/x-ui#128]
Hello,

Is it normal that the speed of Vmess TCP and Vless TCP is much slower than Wireguard protocol?

I installed all of them on one exact server and the Wireguard protocol is faster.

Did I config it wrong? Or maybe someone can share their guide to create the best config for vmess/vless/trojan.

Any help is appreciated.

**Comment by FranzKafkaYu** [comment]
> Hello,
> 
> Is it normal that the speed of Vmess TCP and Vless TCP is much slower than Wireguard protocol?
> 
> I installed all of them on one exact server and the Wireguard protocol is faster.
> 
> Did I config it wrong? Or maybe someone can share their guide to create the best config for vmess/vless/trojan.
> 
> Any help is appreciated.

you should know the disadvantages and advantages of each protocol.Theoretically Wireguard is faster and it's UDP transport,while  vmess/vless/trojan have better resistance against firewall.If you need more faster proxy,try shadowsocks,hysteria etc.

**Comment by EdenSpire** [comment]
Hello FranzKafkaYu,

Please share how to make proper configuration for Vmess/Vless/Trojan 

I'm afraid I generate a wrong configuration because I'm trialing everything on my own.

**Comment by FranzKafkaYu** [comment]
Sorry,I can't.

**Comment by EdenSpire** [comment]
@FranzKafkaYu

**Comment by FranzKafkaYu** [comment]
https://xtls.github.io/config/#%E6%A6%82%E8%BF%B0
