### ISSUE TITLE
Panel crash when goes into settings menu...

### ISSUE THREAD

**Issue by gaweshkaushan** [FranzKafkaYu/x-ui#129]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I'm using latest x-ui english build.. but it crash when I click on panel settings menu.. I try to restart and reset panel.. but still have same problem.. I'm using ubuntu 22.04.. all ports are opened..

### Version of x-ui

0.3.3.17 English Version

### x-ui log or xray log

Oct 27 02:15:27 testing systemd[1]: Started x-ui Service.
Oct 27 02:15:27 testing x-ui[1774]: 2022/10/27 02:15:27 x-ui 0.3.3.17:20221024
Oct 27 02:15:27 testing x-ui[1774]: 2022/10/27 02:15:27 INFO - web server run http on [::]:54321
Oct 27 02:15:27 testing x-ui[1774]: Wait 2 seconds for telegram bot ready
Oct 27 02:15:29 testing x-ui[1774]: SSHLogin[2022-10-27 02:14:00] early than XUI start[2022-10-27 02:15:27],don't notify
Oct 27 02:15:43 testing x-ui[1774]: 2022/10/27 02:15:43 INFO - admin login success,Ip Address:112.134.140.2
Oct 27 02:15:43 testing x-ui[1774]: 2022/10/27 02:15:43 INFO - user 1 login success
Oct 27 02:15:51 testing x-ui[1774]: 2022/10/27 02:15:51 WARNING - stop server err: multierr: context canceled | close tcp [::]:54321: use of closed network connection |
Oct 27 02:15:51 testing x-ui[1774]: 2022/10/27 02:15:51 INFO - web server run http on [::]:54321
Oct 27 02:15:51 testing x-ui[1774]: Wait 2 seconds for telegram bot ready

**Comment by FranzKafkaYu** [comment]
https://github.com/FranzKafkaYu/x-ui/issues/127

Read WIKI and Issues first.

**Comment by gaweshkaushan** [comment]
Bro I read wiki.. but there are no solution for this :/
Always when I go to settings tab it says "404 page not found" I do everything but same issue..

**Comment by FranzKafkaYu** [comment]
@gaweshkaushan we don't allow setting root path to "/"
