### ISSUE TITLE
Requesting English X-UI Source Files

### ISSUE THREAD

**Issue by gaweshkaushan** [FranzKafkaYu/x-ui#132]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Can u release source files of x-ui english version?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
@FranzKafkaYu Would be awesome if you can. I saw once you've replied to a [source code request](https://github.com/FranzKafkaYu/x-ui/issues/94)  saying you don't have such a plan. Please be kind enough to release the source code.

**Comment by FranzKafkaYu** [comment]
@NidukaAkalanka I will implement more functions for my personal needs and before that I have no plan to release them. Sorry.
