### ISSUE TITLE
SSL certificate Error (ERR_SSL_Protocol_Error)

### ISSUE THREAD

**Issue by EdenSpire** [FranzKafkaYu/x-ui#133]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello,

Whenever I access some sites I always get error **Err_SSL_Protocol_Error**.

I'm using the latest version of X-UI from [FranzKafkaYu](https://github.com/FranzKafkaYu)
0.3.3.17:20221024
I also use the xray Core version 1.6.0

I have tried every protocol (VMESS, VLESS, Trojan, Shadowsocks).

but,
If I use the original X-UI (with the Chinese language), and xRay core version 1.4.2
Everything works flawlessly.

Anyone know what is wrong here and how to fix it?

Thank you.

### Version of x-ui

<details>

```console
$ x-ui version
# 面板版本[version]: 0.3.3.17:20221024
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@EdenSpire change xray config with the original one, because current the  default config has banned some websites( mainland China related)

**Comment by EdenSpire** [comment]
@FranzKafkaYu 

Hello,
How to do that? Please guide me.
