### ISSUE TITLE
x ray stop problem

### ISSUE THREAD

**Issue by turbovpn** [FranzKafkaYu/x-ui#136]
Hi
after using for a while i see x ray got stoped and it wont start with the menu
how can i check what is the cause and error?
i checked the x-ui log but noting usefull there
i need to start sray without losing users

**Comment by FranzKafkaYu** [comment]
> Hi after using for a while i see x ray got stoped and it wont start with the menu how can i check what is the cause and error? i checked the x-ui log but noting usefull there i need to start sray without losing users

In the status page,and xray status if not running,just put your mouse on it,you will see error logs produced by xray.
