### ISSUE TITLE
Limit Connection per user

### ISSUE THREAD

**Issue by makintach** [FranzKafkaYu/x-ui#137]
can we have limit connection per user?
we need have 30-50 users
but every one can share to others
when alot of people use this program
in that case it is possible to be filtered by for example iran government
 thanks

**Comment by dugong-lewat** [comment]
I agree

**Comment by LitenBuzzTh** [comment]
it would be so helpful

**Comment by TheMajidHeydari** [comment]
its actually helpful !

**Comment by hunter6698** [comment]
We hope this feature will be added soon.

**Comment by VISOHI** [comment]
yes i looking for this feature too

**Comment by FranzKafkaYu** [comment]
@hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach I think I have to make a clarification hereactually it is hard to limit users connections in x-ui,because we can't get more details for each user,such as IP/MAC addr etc.Unless we modify xray-core and expose such info to x-ui.Actually I can add connection restriction for each inbound,but it is hard to limit connection per user.

**Comment by VISOHI** [comment]
> 

thanks for your explanation if you add connection restriction for each inbound its solve our problem.
 if you want to this how long its take?

**Comment by LitenBuzzTh** [comment]
> @hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach I think I have to make a clarification here，actually it is hard to limit users connections in x-ui,because we can't get more details for each user,such as IP/MAC addr etc.Unless we modify xray-core and expose such info to x-ui.Actually I can add connection restriction for each inbound,but it is hard to limit connection per user.
It would be really nice if you add connection restriction per inbound (maybe not connection per user). thanks for your effort

**Comment by TiTAN-mu** [comment]
ip limit for inbound
https://github.com/vaxilu/x-ui/pull/179

**Comment by a7one** [comment]
It would be really nice if you add connection restriction per inbound

**Comment by VISOHI** [comment]
> ip limit for inbound [vaxilu#179](https://github.com/vaxilu/x-ui/pull/179)

this https://github.com/vaxilu/x-ui/pull/179 have a lot of bug after i install it my server crashed several times and ip limit not working corect

**Comment by FranzKafkaYu** [comment]
> ip limit for inbound [vaxilu#179](https://github.com/vaxilu/x-ui/pull/179)

this method is not efficient,I will take another way to realize this feature.

**Comment by VISOHI** [comment]
> > ip limit for inbound [vaxilu#179](https://github.com/vaxilu/x-ui/pull/179)
> 
> this method is not efficient,I will take another way to realize this feature.

thank you this very helpful especially in this situation that the internet is censored in my country.

**Comment by unknowedNp** [comment]
> > ip limit for inbound [vaxilu#179](https://github.com/vaxilu/x-ui/pull/179)
> 
> this method is not efficient,I will take another way to realize this feature.

Can you descipte whats your idea? may we can help you

**Comment by TheMajidHeydari** [comment]
@FranzKafkaYu also is it possible to add down/up speed to inbounds data grid?

**Comment by hossinasaadi** [comment]
@hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach @unknowedNp 
check the new version, it works without disabling Inbound, actually, it's an IP Restriction, [fork](https://github.com/hossinasaadi/x-ui)

**Comment by hunter6698** [comment]
> @hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach @unknowedNp check the new version, it works without disabling Inbound, actually, it's an IP Restriction, [fork](https://github.com/hossinasaadi/x-ui)

please send install bash link new version

**Comment by a7one** [comment]
> > @hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach @unknowedNp check the new version, it works without disabling Inbound, actually, it's an IP Restriction, [fork](https://github.com/hossinasaadi/x-ui)
> 
> please send install bash link new version

Here 
https://raw.githubusercontent.com/hossinasaadi/x-ui/master/install.sh

**Comment by kireiyume** [comment]
v2board plz

**Comment by hunter6698** [comment]
> > > @hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach @unknowedNp check the new version, it works without disabling Inbound, actually, it's an IP Restriction, [fork](https://github.com/hossinasaadi/x-ui)
> > 
> > 
> > please send install bash link new version
> 
> Here bash <(curl -Ls https://raw.githubusercontent.com/hossinasaadi/x-ui/master/install.sh)

3 devices with 3 different IPs

**Comment by hunter6698** [comment]
> > > @hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach @unknowedNp check the new version, it works without disabling Inbound, actually, it's an IP Restriction, [fork](https://github.com/hossinasaadi/x-ui)
> > 
> > 
> > please send install bash link new version
> 
> Here bash <(curl -Ls https://raw.githubusercontent.com/hossinasaadi/x-ui/master/install.sh)

I tested this last night, unfortunately it doesn't work.

vmess & vless + ws ===> 1count ip

3 devices with 3 different IPs

**Comment by a7one** [comment]
> > > > @hunter6698 @LitenBuzzTh @TheMajidHeydari @dugong-lewat @makintach @unknowedNp check the new version, it works without disabling Inbound, actually, it's an IP Restriction, [fork](https://github.com/hossinasaadi/x-ui)
> > > 
> > > 
> > > please send install bash link new version
> > 
> > 
> > Here bash <(curl -Ls https://raw.githubusercontent.com/hossinasaadi/x-ui/master/install.sh)
> 
> I tested this last night, unfortunately it doesn't work.
> 
> vmess & vless + ws ===> 1count ip
> 
> 3 devices with 3 different IPs

he updated it ...install new version

**Comment by FranzKafkaYu** [comment]
I have implemented a device limit in the latest pre-release version.In this version you can set device limit when you add Inbound,0 means no limitation here.And if you set device limit to 2,when ip1,ip2 connected already,while ip3/ip4 connect,it will keep 2 of them connected while close the reset of them.In short,this feature will limit concurrent IPs and kick off the reset,it won't disable the account.As I have said before,x-ui is designed for personal use,if you share your config with your friends and your friends share it with others,this feature will limit connection while you/your friends may be affected,while you and your friends still can access it if the concurrent ips don't meet the limitation.
