### ISSUE TITLE
TLS not working

### ISSUE THREAD

**Issue by LitenBuzzTh** [FranzKafkaYu/x-ui#141]
Hi,
I've successfully issued an ssl certificate, and I've put cert and key file in x-ui settings. x-ui web now loads with https

but the problem is, when I create a config (for example vmess) with tls (I correctly put my path to cert and path to key in vmess settings), but the connection on v2rayN client gives this error in log :

`2022/10/30 22:51:10 [Warning] [2504423531] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://site.example.com:25227/):  > context deadline exceeded transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://site.example.com:25227/):  > dial tcp: lookup site.example.com: operation was canceled] > common/retry: all retry attempts failed`

is there any solution to this?

**Comment by FranzKafkaYu** [comment]
@LitenBuzzTh this problem has nothing to do with x-ui,you should check your own settings.If you have no idea why this happened,plz find more tutorials about how to config.
