### ISSUE TITLE
single user config

### ISSUE THREAD

**Issue by TheMajidHeydari** [FranzKafkaYu/x-ui#142]
hey.
can i create single user config ?
thanks.

**Comment by FranzKafkaYu** [comment]
@TheMajidHeydari Just add one user in inbound. Actually I am not quite sure what you want here. it's simple if I didn't misunderstand here.

**Comment by TheMajidHeydari** [comment]
i creating a user in inbound but that can be used by many users.
i want to config that only one user at time can connect to it.
thanks

**Comment by FranzKafkaYu** [comment]
> i creating a user in inbound but that can be used by many users. i want to config that only one user at time can connect to it. thanks

not avaliable in X-UI,plz try other tools.
