### ISSUE TITLE
multi-user one-port

### ISSUE THREAD

**Issue by miladrajabi2002** [FranzKafkaYu/x-ui#143]
pleas add multi-user one-port option

in iran if have many active port filter server ip pleas add option to make user on ports 443 or 80 or 8080

**Comment by FranzKafkaYu** [comment]
@miladrajabi2002 current support 3 users on the same port, is it not enough?

**Comment by miladrajabi2002** [comment]
Yes, 3 people are enough, but
This part inside your panel is not useful at all
Because we cannot see the traffic of 3 users
There is no difference between activating and deactivating this section, this is everyone's problem

**Comment by FranzKafkaYu** [comment]
> Yes, 3 people are enough, but This part inside your panel is not useful at all Because we cannot see the traffic of 3 users There is no difference between activating and deactivating this section, this is everyone's problem

if you need such functions,plz use v2board or SSPanel instead. x-ui is developed for personal use. Won't support such features.I am sorry.

**Comment by miladrajabi2002** [comment]
i have 3 user and i want to show traffic and have same post as you said, it is possible, but it is not possible
