### ISSUE TITLE
add remark to Device IP Changed Alert

### ISSUE THREAD

**Issue by miladrajabi2002** [FranzKafkaYu/x-ui#145]
i wnat 
![Screenshot 2022-11-01 033959](https://user-images.githubusercontent.com/51949453/199132078-b907d7cd-c113-43ce-9585-fc1fa5dd328f.png)

I want to send the user remark in this text in addition to the port, can you help me? I searched all over the source, but I didn't find anything

**Comment by FranzKafkaYu** [comment]
@miladrajabi2002 check the latest pre-release version
