### ISSUE TITLE
Create all inbounds on specified port like 80, 443 and ...

### ISSUE THREAD

**Issue by unknown-qp** [FranzKafkaYu/x-ui#155]
Hi, I want to know how we can set custom port for 10 users (qr-code) on specified port like 80,443?
Because there is a strict restriction on the Internet and when different ports are connected, they block access to the server and filter the server IP!

**Comment by FranzKafkaYu** [comment]
it's impossible,you can add unlimited users in same port but you can't create all inbounds on the same port.
