### ISSUE TITLE
direct communicate all top level domain like .uk

### ISSUE THREAD

**Issue by unknown-qp** [FranzKafkaYu/x-ui#157]
hi, how can I set all .uk domains to communicate directly in v2ray routing section (server)? Do I need Regex? Thank you for your advice

**Comment by FranzKafkaYu** [comment]
@unknown-qp yes you can,please refer to official [document](https://xtls.github.io/config/routing.html#ruleobject) for more details,you should use regexp for matching all *.uk domains and edit config template in x-ui panel.

**Comment by unknown-qp** [comment]
@FranzKafkaYu Hi again, I read the document and try all ways about regexp in this section : 

> Regular expression: "regexp:"starts with and the rest is a regular expression. The rule takes effect when this regular expression matches the target domain name. For example "regexp:\\.goo.*\\.com " matches "www.google.com" or "fonts.googleapis.com", but not "google.com".

But unfortunately, none of these methods worked.

I even apart from these methods
I also tried [domain:uk], but it still didn't work.

can you guide me?
