### ISSUE TITLE
Add the xtls-rprx-vision support

### ISSUE THREAD

**Issue by kireiyume** [FranzKafkaYu/x-ui#159]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

the xtls-rprx-vision flow need server change the config：
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server.json
what's  the xtls-rprx-vision：
https://github.com/XTLS/Xray-core/discussions/1295

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@kireiyume check this latest pre-release version：https://github.com/FranzKafkaYu/x-ui/releases/tag/0.3.3.17-1112
