### ISSUE TITLE
tls not work

### ISSUE THREAD

**Issue by shahrooz1349** [FranzKafkaYu/x-ui#160]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello Since yesterday, vless and vemess have been disrupted in Iran. Scripts that work with tls have no problem. TLS does not connect in your panel. Fix the problem if possible Thanks

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by shahrooz1349** [comment]
twork connection
Nov 07 07:09:48 ubuntu-v2ray x-ui[27312]: 2022/11/07 07:09:4
8 http: TLS handshake error from 44.55.66.77:37278: EOF
Nov 07 17:16:57 ubuntu-v2ray x-ui[27312]: 2022/11/07 17:16:5
7 http: TLS handshake error from 44.55.66.77:37956: read t
cp 44.55.66.77:2610->44.55.66.77:37956: use of closed ne

**Comment by FranzKafkaYu** [comment]
@shahrooz1349 could you show more settings about your tls setting in panel settings?

**Comment by shahrooz1349** [comment]
![Uploading Screenshot_20221108_212535_com.android.chrome_edit_346694260750222.jpg…]()

**Comment by FranzKafkaYu** [comment]
can you tell me what's the concrete problem, can't access web panel via https or can't access via proxy with ws+tls?

**Comment by shahrooz1349** [comment]
dear developer
The panel is available on https and no problem with ssl I can't use a proxy It connects but does not give ping. If tls is turned off, the proxy works.
regard

**Comment by FranzKafkaYu** [comment]
> dear developer The panel is available on https and no problem with ssl I can't use a proxy It connects but does not give ping. If tls is turned off, the proxy works. regard

so did you have checked your cert settings are right? and did you have try different client app?such as v2rayN ( Windows)or v2rayNG( Android)

**Comment by shahrooz1349** [comment]
Installed ssl certificate without error from command #16. I tested with v2rayNG on Android and V2rayA for Windows, the problem is there

**Comment by shahrooz1349** [comment]
Unfortunately, I forgot to change the main domain in the screenshot Please remove the domain name in your reply so that it is not filtered. I have entered the correct half name of the domain in the server field I changed it to save my information
regard

**Comment by FranzKafkaYu** [comment]
> Unfortunately, I forgot to change the main domain in the screenshot Please remove the domain name in your reply so that it is not filtered. I have entered the correct half name of the domain in the server field I changed it to save my information regard

after correcting your server name,tls can work now?

**Comment by shahrooz1349** [comment]
not work dear

**Comment by FranzKafkaYu** [comment]
@shahrooz1349 plz provide xray logs,and this problem has nothing to do with x-ui
