### ISSUE TITLE
Listen IP Issue

### ISSUE THREAD

**Issue by ITheEqualizer** [FranzKafkaYu/x-ui#161]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

When I add any IP (123.456.789) or address to the listen ip part in inbound, the service stops working.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@ITheEqualizer no logs here, what can I do for you?

**Comment by ITheEqualizer** [comment]
@FranzKafkaYu This is the error: https://i.vgy.me/wNbWtt.png

**Comment by FranzKafkaYu** [comment]
@ITheEqualizer do you have multiple IPs in your servers?Leave blank would be OK.
