### ISSUE TITLE
如何通过修改配置文件进行节点配置

### ISSUE THREAD

**Issue by Coker-J** [FranzKafkaYu/x-ui#165]
我修改了/usr/local/x-ui/bin/目录下的配置文件，更换了相应节点的端口，但是重启x-ui后发现修改过的配置自动复原了。请问如何通过修改配置文件进行节点配置？（由于经常需要重装系统，导致通过面板网页进行配置的方法效率太低，故希望每次将配置文件保存下来，重装系统后直接更换配置文件，但是实测修改端口重新x-ui并不能使修改的配置文件生效，修改后的端口在重启x-ui后会自动复原）

**Comment by FranzKafkaYu** [comment]
无法手动修改config.json，会被还原，请直接备份/etc/x-ui/x-ui.db,重装系统后可以直接导入使用
