### ISSUE TITLE
Please add hysteria

### ISSUE THREAD

**Issue by 3H54N** [FranzKafkaYu/x-ui#167]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi 
Thanks for your nice project and keep it up!
if possible please add hysteria too
Regards

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@3H54N hi, it's impossible because x-ui use xray core  and can't support Hysteria.
