### ISSUE TITLE
Is there a way to backup and restore inbounds

### ISSUE THREAD

**Issue by sarahtuska** [FranzKafkaYu/x-ui#168]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

everything is perfect thanks to Developers 
i wanna know is there a way to backup and restores all inbounds when i need to reinstall the linux or move linux ?
MerC

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
backup / etc/x-ui/x-ui.db
