### ISSUE TITLE
新机器安装新版本x-ui后无法正常使用谷歌翻译和gmail等正常的谷歌服务

### ISSUE THREAD

**Issue by AuroraIO** [FranzKafkaYu/x-ui#169]
无法正常使用谷歌服务情形如下
![image](https://user-images.githubusercontent.com/74000837/201599761-22d4c36c-b958-414a-af7a-7e87ee04a912.png)
![image](https://user-images.githubusercontent.com/74000837/201599868-e5aeb681-86be-43cc-8936-184ebe5950a5.png)
均表现为进入此页面后就无法进行服务的正常使用，如登录谷歌的下一步无法点击或谷歌翻译毫无反应。
在将老版本x-ui的面板设置-x-ray设置复制粘贴到新版本x-ui中并重启面板后所有谷歌服务均可正常使用。似乎是新版本默认配置中block有问题？

**Comment by AuroraIO** [comment]
系统版本是debian11

**Comment by kireiyume** [comment]
> 系统版本是debian11

按下浏览器F12，若不是chrome，请打开调试模式，看看JavaScript是否存在报错

**Comment by AuroraIO** [comment]
> > 系统版本是debian11
> 
> 按下浏览器F12，若不是chrome，请打开调试模式，看看JavaScript是否存在报错

![image](https://user-images.githubusercontent.com/74000837/201612106-51423067-915f-4b34-9ec4-9f6ea1e5e3f9.png)
看起来似乎有报错？ 补充一下，服务器系统是debian11，本地是win11 22h2

**Comment by FranzKafkaYu** [comment]
@AuroraIO 当前配置模板中默认会屏蔽广告/以及国内网站与IP，有可能是该问题引起，如果恢复配置模板为原版没有该问题，可以进行恢复(不会影响功能使用)，再或者，更新一下Geo数据试试.

**Comment by AuroraIO** [comment]
> @AuroraIO 当前配置模板中默认会屏蔽广告/以及国内网站与IP，有可能是该问题引起，如果恢复配置模板为原版没有该问题，可以进行恢复(不会影响功能使用)，再或者，更新一下Geo数据试试.

更新了第三方geo文件后依然还是没法正常使用部分谷歌服务，我还是先使用原先的配置吧，谢谢dalao

**Comment by AuroraIO** [comment]
> > 
> 
> 屏蔽的都是涉及到用户隐私的链接，建议ctrl+F5重新刷新尝试，不行去掉面板中xray模板设置中geoip:private这条

![`QTPPL}F 4UYMX_A8U9KR(K](https://user-images.githubusercontent.com/74000837/201647780-7f90e1ea-ea49-4c85-94f5-9fd0849f4ceb.png)
![image](https://user-images.githubusercontent.com/74000837/201647838-986f8095-c818-4a9c-9815-1adbe3ef8f70.png)
ctrl+f5和去除掉模板中geoip：private这一条后依然是这些报错

**Comment by FranzKafkaYu** [comment]
判断为配置模板问题，用户可自行更改。
