### ISSUE TITLE
404 page not found after a day

### ISSUE THREAD

**Issue by MeysamFallah** [FranzKafkaYu/x-ui#170]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi,
I install ssl and add it to panel and vless after a day I get 404 error and I can't reach any page on x-ui.
sometimes without any ssl it happen after two day I get "404 page not found" on login page.

### Version of x-ui

0.3.3.18

### x-ui log or xray log

no log

**Comment by FranzKafkaYu** [comment]
@MeysamFallah 404 not found because x-ui will generate a random root path after your fitst login,you can enter x-ui control menu and type 7 to get the right root path,plz use the new root path login.
