### ISSUE TITLE
找不到xtls-rprx-vision流控选项

### ISSUE THREAD

**Issue by jiaoting** [FranzKafkaYu/x-ui#171]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

1.增加xtls-rprx-vision流控选项,该流控目前仅用于vless+tcp+tls, 在开启tls时可选择flow,同时需要将xray core版本切换为1.6.1以上方可生效；若选择none则不开启该流控

为啥我找不到呢？已经重新拉取并安装新文件了
![image](https://user-images.githubusercontent.com/12553424/202077242-daf0dca7-1fd6-4777-9dbf-0f94c74003b6.png)
![Uploading image.png…]()

### Version of x-ui

$ x-ui version
# Paste output here

### x-ui log or xray log

# paste log here

**Comment by jiaoting** [comment]
![image](https://user-images.githubusercontent.com/12553424/202077777-ddfca88d-7374-4ffd-9482-1c6dd72d91d9.png)
这里也没有

**Comment by FranzKafkaYu** [comment]
@jiaoting 你这是装错版本了吧……

**Comment by chengandpeng** [comment]
> ![image](https://user-images.githubusercontent.com/12553424/202077777-ddfca88d-7374-4ffd-9482-1c6dd72d91d9.png) 这里也没有

你好，你那边出来了吗？
我版本是最新的
`面板版本[version]: 0.3.3.18:20221116`
添加入站也没有flow的选项
