### ISSUE TITLE
监听IP问题

### ISSUE THREAD

**Issue by Fangliding** [FranzKafkaYu/x-ui#174]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

在甲骨文新开的机器 系统是自带的Ubuntu 没有做任何事情直接安装 完成后无法进入面板

lsof -i:54321得到回复
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
x-ui    2471 root    7u  IPv6  26243      0t0  TCP *:54321 (LISTEN)

似乎x-ui只监听了IPv6 于是我尝试为新机器分配一个ipv6地址 成功连接 顺便连x-ui的xray监听也是一样的状态 lsof一样的回复 只能使用v6连接

尝试使用各种手段尝试重置网卡(还把网玩崩了两次)还是没有用

### Version of x-ui

latest

### x-ui log or xray log

相关内容只有
INFO - web server run http on [::]:54321

**Comment by Chasing66** [comment]
理论上来讲，并不影响你使用。[::]对应的本地回环地址仍然是localhost。
如果访问 不了建议检查一下 `cat /etc/hosts`

```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
```

**Comment by tmzg0000** [comment]
我也是甲骨文 也是只有ipv6有监听  。本地
cat /etc/hosts
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1	ip6-localhost	ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
ff02::3	ip6-allhosts

修改为 # The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
重启后还是一样 只监听ipv6

**Comment by rocknjoekudo** [comment]
同样是甲骨文云，终于解决了这个问题。需要在GRUB的启动项里面加入：
ipv6.disable=1
到 GRUB_CMDLINE_LINUX 和 GRUB_CMDLINE_LINUX_DEFAULT
记得要update-grub
甲骨文云官方镜像里面大改的东西确实不少

> 我也是甲骨文 也是只有ipv6有监听 。本地 cat /etc/hosts 127.0.0.1 localhost
> # The following lines are desirable for IPv6 capable hosts
> 
> ::1 ip6-localhost ip6-loopback fe00::0 ip6-localnet ff00::0 ip6-mcastprefix ff02::1 ip6-allnodes ff02::2 ip6-allrouters ff02::3 ip6-allhosts
> 
> 修改为 # The following lines are desirable for IPv6 capable hosts ::1 localhost ip6-localhost ip6-loopback 重启后还是一样 只监听ipv6
