### ISSUE TITLE
Can the user check the remaining traffic and expiration time?

### ISSUE THREAD

**Issue by SepidGsm** [FranzKafkaYu/x-ui#178]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi dear
Can the user check the remaining traffic and expiration time?
What method do you suggest?
Can it be done with php or html?
users enter the port number and see account details ? (remaining traffic and expiration time)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
Not a valid issue and I can't give you any advice here.if you know how to develop a telegram bot,you can realize such function easily.

**Comment by SepidGsm** [comment]
Thank you for your answer. Please guide using php html.
Show the details inside a web page by entering the port
