### ISSUE TITLE
域名合法性校验失败,当前环境已有对应域名证书,不可重复申请,这种情况能不能在脚本加一个吊销证书的功能呢

### ISSUE THREAD

**Issue by ulifuqiang** [FranzKafkaYu/x-ui#179]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![截图_20221120210312](https://user-images.githubusercontent.com/25083314/202907858-e495729d-cf8e-457b-a9b7-5f627994b936.png)

我有看到说不能重复申请，想问一下，能不能把证书吊销做到脚本里面来呢？
### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
> 

可以自行使用acme脚本的命令吊销，欢迎pr。其实实现起来很简单，只是个人觉得再添加到脚本内有些没必要。

**Comment by ulifuqiang** [comment]
> > 
> 
> 可以自行使用acme脚本的命令吊销，欢迎pr。其实实现起来很简单，只是个人觉得再添加到脚本内有些没必要。

好的，我再想办法吧，谢谢了。
