### ISSUE TITLE
证书格式被墙

### ISSUE THREAD

**Issue by i5g5vip** [FranzKafkaYu/x-ui#180]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

用本脚本申请的证书节点不通，换成别的证书后正常。
对比发现不通的证书格式2048，
通的证书为ec-256,
2048证书不过墙则正常。当网页证书也正常。
怀疑证书被墙。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by i5g5vip** [comment]
后发现windows平台v2rayN节点可用，
可能安卓平台app不识别证书。

**Comment by FranzKafkaYu** [comment]
@i5g5vip 服务端请使用fullchain.cer
