### ISSUE TITLE
希望增加一个定期/手动更新geoip和geosite的功能

### ISSUE THREAD

**Issue by venkate123** [FranzKafkaYu/x-ui#182]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

V2rayN客户端有手动更新geoip和geosite的功能，我看这版X-UI相比原版Xray模板中增加了routing判定，但是geoip.dat和geosite.dat还是两年前的，所有希望增加一个定期/手动更新geoip和geosite的功能。

顺便给其他人贴一个现在更新的命令
```
wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -O /usr/local/x-ui/bin/geoip.dat
wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -O /usr/local/x-ui/bin/geosite.dat
```

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> V2rayN客户端有手动更新geoip和geosite的功能，我看这版X-UI相比原版Xray模板中增加了routing判定，但是geoip.dat和geosite.dat还是两年前的，所有希望增加一个定期/手动更新geoip和geosite的功能。
> 
> 顺便给其他人贴一个现在更新的命令
> 
> ```
> wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -O /usr/local/x-ui/bin/geoip.dat
> wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -O /usr/local/x-ui/bin/geosite.dat
> ```
> 
> ### Version of x-ui
> ### x-ui log or xray log

版本发布打包时都会自动更新geo数据，安装完成后用户可能需要自动设定更新geo.可以考虑在脚本或者在面板内部增加该选项。

**Comment by FranzKafkaYu** [comment]
@venkate123 在最新的脚本内已添加该功能，使用方法：输入`x-ui`进入控制菜单，选择选项`17`，即可选择自动更新geo数据，包括xray日志清理（前提是有配置日志），目前更新周期为两天一次，时间定在凌晨4点，更新完成同步重启x-ui.
