### ISSUE TITLE
禁止访问国内IP功能

### ISSUE THREAD

**Issue by Mike086** [FranzKafkaYu/x-ui#183]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

大佬，很多小白不知道如何在VPS上设置禁止访问国内IP，能否在X-UI界面增加一个该功能的开关？

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
latest

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```none

</details>

**Comment by FranzKafkaYu** [comment]
@Mike086 当前版本的配置模板内已设置禁止访问国内IP/网站。
