### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by taheri79** [FranzKafkaYu/x-ui#185]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

nothing works ....
im getting "err: database is locked" in my browser and in log file
such as 
disable invalid inbounds err: database is locked
StatsNotifyJob run failed: database is locked
get settings failed:  database is locked

### Version of x-ui

latest

### x-ui log or xray log

<details>

```
invalid inbounds err: database is locked
StatsNotifyJob run failed: database is locked
get settings failed:  database is locked
```

</details>

**Comment by NanFengXiangWan** [comment]
I have encountered the same problem, please tell me how to solve it

**Comment by aliafshany** [comment]
@taheri79 

is it fixed by now? with the new update? did you manage to fix it?

**Comment by taheri79** [comment]
no I'm facing it in 6/5 of every request. 
I think it because of the speed of hard drive on vps
I think the project should use another kind of database instead of file for example mysql.

**Comment by aliafshany** [comment]
> no I'm facing it in 6/5 of every request. I think it because of the speed of hard drive on vps I think the project should use another kind of database instead of file for example mysql.

it's because of IP Limitation feature. disable it for every user and everything will work fine as before

**Comment by taheri79** [comment]
what should I do if I need IP limitation? :)

**Comment by aliafshany** [comment]
wait for https://github.com/NidukaAkalanka/x-ui-english/ to fix it.
it's gonna take time but gonna be fixed for sure
