### ISSUE TITLE
面板自动生成根目录，但新目录都是空白页面

### ISSUE THREAD

**Issue by yuta2** [FranzKafkaYu/x-ui#186]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

安装后第一次进入面板成功，能看到监控页，但随即自动产生新的根目录并重新启动面板，
此后如果没有cache的浏览器或是InPrivate模式，显示的都是空白页面。
所有服务都正常，入站列表如有设定完毕也都可以正常连线，就只有监控页面全是空白。

### Version of x-ui

<details>

```console
$ x-ui version
面板版本[version]: 0.3.3.18:20221116
```

</details>

### x-ui log or xray log

<details>

```console
Nov 26 19:29:35 xray1 systemd[1]: Started x-ui Service.
Nov 26 19:29:35 xray1 x-ui[9651]: 2022/11/26 19:29:35 x-ui 0.3.3.18:20221116
Nov 26 19:29:35 xray1 x-ui[9651]: 2022/11/26 19:29:35 INFO - web server run http on [::]:8443
Nov 26 19:29:35 xray1 x-ui[9651]: Wait 2 seconds for telegram bot ready
Nov 26 19:29:37 xray1 x-ui[9651]: SSHLogin[2022-11-26 19:25:00] early than XUI start[2022-11-26 19:29:35],don't notify
```

</details>

**Comment by yuta2** [comment]
补充：试着安装0.3.3.17, 0.3.3.16都有此状况，安装回0.3.3.15版就正常了。

**Comment by FranzKafkaYu** [comment]
@yuta2 页面空间无任何错误提示么?是否尝试过清除浏览器缓存与Cookie?另外浏览器的语言设置确实会产生一些影响，如果界面未正常显示，可以F12查看是否有任何错误信息。

**Comment by yuta2** [comment]
@InfoMsg  中文没错，确实改为英文语系就正常了(chrome/firefox)。
@FranzKafkaYu 缓存都清除过还是一样，错误有一个但不知道有没有关连。不过有发现如果不是英文版，载入 xui 网页时，html仅会载入前面3x-4x行，原因不明，导致页面空白。
![2022-11-28_09-04-03](https://user-images.githubusercontent.com/9444104/204171058-0a712856-ae23-482a-98d2-8cbb384ba3b6.png)
![2022-11-28_09-04-39](https://user-images.githubusercontent.com/9444104/204171072-a21ba10c-22d4-40eb-94c6-b07d2c989f23.png)
