### ISSUE TITLE
xray频繁errror

### ISSUE THREAD

**Issue by 8ty** [FranzKafkaYu/x-ui#187]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

在gullo和webhorizon上的nat小鸡上都是这样子，就是无缘无故xray就error了，重启一下running了两分钟又error了
![](https://ldbbs.ldmnq.com/bbs/topic/attachment/2022-11/e78cd9b3-342b-4f1b-985c-4d7ad014b314.png)
日志里没有报错，只有ssh记录和登录面板记录

### Version of x-ui

最新

### x-ui log or xray log

<details>

```console
-

```

</details>

**Comment by FranzKafkaYu** [comment]
@8ty 鼠标指向问号的位置，可以看到xray输出的错误信息，需要提供这部分信息。

**Comment by 8ty** [comment]
> @8ty 鼠标指向问号的位置，可以看到xray输出的错误信息，需要提供这部分信息。
好的，不过已经解决了
