### ISSUE TITLE
在gullo的natvps上再次xray error

### ISSUE THREAD

**Issue by 8ty** [FranzKafkaYu/x-ui#188]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

reflect.Value.call({0xea73c0?, 0xc0001fe300?, 0x30?}, {0x10363d5, 0x4}, {0xc00101a4b0, 0x2, 0x18?})

reflect/value.go:584 +0x8c5 fp=0xc001159868 sp=0xc001159278 pc=0x496da5

reflect.Value.Call({0xea73c0?, 0xc0001fe300?, 0xf46220?}, {0xc00101a4b0?, 0xe4d8c0?, 0x0?})

reflect/value.go:368 +0xbc fp=0xc0011598e0 sp=0xc001159868 pc=0x49629c

github.com/xtls/xray-core/core.(*resolution).resolve(0xc001159b08?, {0xc00119a180?, 0x8?, 0x8?})

github.com/xtls/xray-core/core/xray.go:74 +0x41b fp=0xc001159a68 sp=0xc0011598e0 pc=0x6dc3db

github.com/xtls/xray-core/core.(*Instance).AddFeature(0xc0010efb80, {0x7ff9552d81c8?, 0xc000ffb200?})

github.com/xtls/xray-core/core/xray.go:315 +0x31e fp=0xc001159b40 sp=0xc001159a68 pc=0x6ddf1e

### Version of x-ui

<details>

```console
reflect.Value.call({0xea73c0?, 0xc0001fe300?, 0x30?}, {0x10363d5, 0x4}, {0xc00101a4b0, 0x2, 0x18?})

reflect/value.go:584 +0x8c5 fp=0xc001159868 sp=0xc001159278 pc=0x496da5

reflect.Value.Call({0xea73c0?, 0xc0001fe300?, 0xf46220?}, {0xc00101a4b0?, 0xe4d8c0?, 0x0?})

reflect/value.go:368 +0xbc fp=0xc0011598e0 sp=0xc001159868 pc=0x49629c

github.com/xtls/xray-core/core.(*resolution).resolve(0xc001159b08?, {0xc00119a180?, 0x8?, 0x8?})

github.com/xtls/xray-core/core/xray.go:74 +0x41b fp=0xc001159a68 sp=0xc0011598e0 pc=0x6dc3db

github.com/xtls/xray-core/core.(*Instance).AddFeature(0xc0010efb80, {0x7ff9552d81c8?, 0xc000ffb200?})

github.com/xtls/xray-core/core/xray.go:315 +0x31e fp=0xc001159b40 sp=0xc001159a68 pc=0x6ddf1e
```

</details>

### x-ui log or xray log

<details>

```console
reflect.Value.call({0xea73c0?, 0xc0001fe300?, 0x30?}, {0x10363d5, 0x4}, {0xc00101a4b0, 0x2, 0x18?})

reflect/value.go:584 +0x8c5 fp=0xc001159868 sp=0xc001159278 pc=0x496da5

reflect.Value.Call({0xea73c0?, 0xc0001fe300?, 0xf46220?}, {0xc00101a4b0?, 0xe4d8c0?, 0x0?})

reflect/value.go:368 +0xbc fp=0xc0011598e0 sp=0xc001159868 pc=0x49629c

github.com/xtls/xray-core/core.(*resolution).resolve(0xc001159b08?, {0xc00119a180?, 0x8?, 0x8?})

github.com/xtls/xray-core/core/xray.go:74 +0x41b fp=0xc001159a68 sp=0xc0011598e0 pc=0x6dc3db

github.com/xtls/xray-core/core.(*Instance).AddFeature(0xc0010efb80, {0x7ff9552d81c8?, 0xc000ffb200?})

github.com/xtls/xray-core/core/xray.go:315 +0x31e fp=0xc001159b40 sp=0xc001159a68 pc=0x6ddf1e
```

</details>

**Comment by FranzKafkaYu** [comment]
@8ty crash是属于xray core自身的，可以将/usr/local/x-ui/bin/config.json配置文件结合crash日志提交至xray core Issue区
