### ISSUE TITLE
Feature Request - Add NaiveProxy Protocol

### ISSUE THREAD

**Issue by kalhori124** [FranzKafkaYu/x-ui#190]
Hi, 

As firewalls easily block protocols such as VMESS, VLESS, Trojan.
Could you please add NaïveProxy ?

Best Regards,

**Comment by FranzKafkaYu** [comment]
@kalhori124 Hi，x-ui is based on xray core.So it's hard to support Naive here because xray doesn't support.You can try the latest xtls flow with utls in Client,plz ensure xray core version > 1.6.1
