### ISSUE TITLE
打开网页XUI面板报错！

### ISSUE THREAD

**Issue by wyshn** [FranzKafkaYu/x-ui#191]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

为啥安装以后，打开面板设置。会自动设置并重启！

关键还是设置不成功。。如下是报错信息日志：

**（重点想请问一下这句是啥意思啊？修改设置失败:  read tcp 10.0.19.2:8443->45.62.168.69:6747: read: connection reset by peer）**
![image](https://user-images.githubusercontent.com/29453433/204478388-c51b12c9-7ffc-4bbf-ac2c-6d71324c73b8.png)

### Version of x-ui

<details>

x-ui v0.3.3.18

</details>

### x-ui log or xray log

<details>

Nov 29 08:15:29 VM66637F37C751571 x-ui[128028]: 2022/11/29 08:15:29 WARNING - 修改设置失败:  read tcp 10.0.19.2:8443->45.62.168.68:11429: read: connection reset by peer
Nov 29 08:15:54 VM66637F37C751571 x-ui[128028]: 2022/11/29 08:15:54 WARNING - stop server err: multierr: context canceled | close tcp 0.0.0.0:8443: use of closed network connection |
Nov 29 08:15:54 VM66637F37C751571 x-ui[128028]: 2022/11/29 08:15:54 INFO - web server run http on 0.0.0.0:8443
Nov 29 08:15:54 VM66637F37C751571 x-ui[128028]: Wait 2 seconds for telegram bot ready
Nov 29 08:16:05 VM66637F37C751571 x-ui[128028]: 2022/11/29 08:16:05 WARNING - 修改设置失败:  read tcp 10.0.19.2:8443->45.62.168.69:6747: read: connection reset by peer

</details>

**Comment by FranzKafkaYu** [comment]
@wyshn 安装完成后第一次进入设置页面，会自动生成新的根路径并进行跳转，所以会自动重启。从日志来看`10.0.19.2`属于本地局域网地址，你是安装在什么机器上的，请提供一下服务器信息

**Comment by wyshn** [comment]
> 

那请问这是哪个地址啊？
45.62.168.69:6747

服务器是：Debian 11

**Comment by FranzKafkaYu** [comment]
@wyshn 45.62.168.69这个IP应该是接入x-ui所在服务器的IP，如果你没有挂代理，就应该是你本地的IP，如果你是挂了代理去登录X-UI，应该是代理的IP

**Comment by wyshn** [comment]
> 
没有挂代理，也不是本机IP。我所在的服务器也不是这个IP段。

**Comment by wyshn** [comment]
> @wyshn 45.62.168.69这个IP应该是接入x-ui所在服务器的IP，如果你没有挂代理，就应该是你本地的IP，如果你是挂了代理去登录X-UI，应该是代理的IP
老板，你说的对。是我的代理问题，感谢
