### ISSUE TITLE
add expire date for users

### ISSUE THREAD

**Issue by amirreza225** [FranzKafkaYu/x-ui#195]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

thank you for your great code. if it is possible add expire date for users,please.

### Version of x-ui

I use latest version

### x-ui log or xray log

Dec 03 09:04:53 638b1071487e6f00018c86a4 systemd[1]: Started x-ui Service.
Dec 03 09:04:53 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:04:53 x-ui 0.3.3.18:20221116
Dec 03 09:04:53 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:04:53 INFO - web server run http on [::]:443
Dec 03 09:04:53 638b1071487e6f00018c86a4 x-ui[2001]: Wait 2 seconds for telegram bot ready
Dec 03 09:04:55 638b1071487e6f00018c86a4 x-ui[2001]: SSHLogin[2022-12-03 09:03:00] early than XUI start[2022-12-03 09:04:53],don't notify
Dec 03 09:05:27 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:05:27 INFO - wrong username or password: "amirreza933@gmail.com" "1shiftandenterA@"
Dec 03 09:05:30 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:05:30 INFO - amirreza933 login success,Ip Address:5.202.17.127
Dec 03 09:05:30 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:05:30 INFO - user 1 login success
Dec 03 09:08:10 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:08:10 WARNING - stop server err: multierr: context canceled | close tcp [::]:443: use of closed network connection |
Dec 03 09:08:10 638b1071487e6f00018c86a4 x-ui[2001]: 2022/12/03 09:08:10 INFO - web server run http on [::]:443
Dec 03 09:08:10 638b1071487e6f00018c86a4 x-ui[2001]: Wait 2 seconds for telegram bot ready
Dec 03 09:11:30 638b1071487e6f00018c86a4 x-ui[2001]: get signal: terminated
Dec 03 09:11:30 638b1071487e6f00018c86a4 systemd[1]: Stopping x-ui Service...
Dec 03 09:11:31 638b1071487e6f00018c86a4 systemd[1]: x-ui.service: Deactivated successfully.
Dec 03 09:11:31 638b1071487e6f00018c86a4 systemd[1]: Stopped x-ui Service.
Dec 03 09:11:31 638b1071487e6f00018c86a4 systemd[1]: x-ui.service: Consumed 4.578s CPU time.
Dec 03 09:11:31 638b1071487e6f00018c86a4 systemd[1]: Started x-ui Service.
Dec 03 09:11:31 638b1071487e6f00018c86a4 x-ui[6748]: 2022/12/03 09:11:31 x-ui 0.3.3.18:20221116
Dec 03 09:11:31 638b1071487e6f00018c86a4 x-ui[6748]: 2022/12/03 09:11:31 INFO - web server run http on [::]:80
Dec 03 09:11:31 638b1071487e6f00018c86a4 x-ui[6748]: Wait 2 seconds for telegram bot ready
Dec 03 09:11:33 638b1071487e6f00018c86a4 x-ui[6748]: SSHLogin[2022-12-03 09:03:00] early than XUI start[2022-12-03 09:11:31],don't notify
Dec 03 09:12:30 638b1071487e6f00018c86a4 x-ui[6748]: get signal: terminated
Dec 03 09:12:30 638b1071487e6f00018c86a4 systemd[1]: Stopping x-ui Service...
Dec 03 09:12:30 638b1071487e6f00018c86a4 systemd[1]: x-ui.service: Deactivated successfully.
Dec 03 09:12:30 638b1071487e6f00018c86a4 systemd[1]: Stopped x-ui Service.
Dec 03 09:12:30 638b1071487e6f00018c86a4 systemd[1]: Started x-ui Service.
Dec 03 09:12:30 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:12:30 x-ui 0.3.3.18:20221116
Dec 03 09:12:30 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:12:30 INFO - web server run http on [::]:54321
Dec 03 09:12:31 638b1071487e6f00018c86a4 x-ui[6920]: Wait 2 seconds for telegram bot ready
Dec 03 09:12:33 638b1071487e6f00018c86a4 x-ui[6920]: SSHLogin[2022-12-03 09:03:00] early than XUI start[2022-12-03 09:12:30],don't notify
Dec 03 09:15:53 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:15:53 WARNING - stop server err: multierr: context canceled | close tcp [::]:54321: use of closed network connection |
Dec 03 09:15:53 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:15:53 INFO - web server run https on [::]:443
Dec 03 09:15:53 638b1071487e6f00018c86a4 x-ui[6920]: Wait 2 seconds for telegram bot ready
Dec 03 09:16:15 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:15 http: TLS handshake error from 168.100.11.229:41850: read tcp 168.100.9.125:443->168.100.11.229:41850: use of closed network connection
Dec 03 09:16:15 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:15 http: TLS handshake error from 168.100.11.229:41862: remote error: tls: unknown certificate
Dec 03 09:16:19 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:19 http: TLS handshake error from 168.100.11.229:41864: remote error: tls: unknown certificate
Dec 03 09:16:21 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:21 http: TLS handshake error from 168.100.11.229:41892: remote error: tls: unknown certificate
Dec 03 09:16:21 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:21 http: TLS handshake error from 168.100.11.229:41896: remote error: tls: unknown certificate
Dec 03 09:16:22 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:22 http: TLS handshake error from 168.100.11.229:41934: remote error: tls: unknown certificate
Dec 03 09:16:22 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:22 http: TLS handshake error from 168.100.11.229:41950: remote error: tls: unknown certificate
Dec 03 09:16:23 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:23 http: TLS handshake error from 168.100.11.229:41958: remote error: tls: unknown certificate
Dec 03 09:16:48 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:48 INFO - wrong username or password: "amirreza933" "1shiftandenterA!"
Dec 03 09:16:51 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:51 INFO - amirreza933 login success,Ip Address:168.100.11.229
Dec 03 09:16:51 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:16:51 INFO - user 1 login success
Dec 03 09:19:36 638b1071487e6f00018c86a4 x-ui[6920]: 2022/12/03 09:19:36 WARNING - add inbound failed:  current port is already in use: 2053

**Comment by FranzKafkaYu** [comment]
done,try latest release.
