### ISSUE TITLE
How to Change DNS?

### ISSUE THREAD

**Issue by VPNCI** [FranzKafkaYu/x-ui#196]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello developer, thank you.  I've searched v2ray and xray documentation but couldn't find information on how to change dns address.  The "dns" I added to the config: 
{
     "hosts": {
       "baidu.com": "127.0.0.1",
       "dns.google": ["8.8.8.8", "8.8.4.4"]
     },
 cloudflare dns is always active even though I add it.  How can I add it as DoH?  DNS Over Https ?  Thank you.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@VPNCI like this`"address": "https://1.1.1.1/dns-query"`

**Comment by VPNCI** [comment]
> "address": "https://1.1.1.1/dns-query"

yes i know that but how to add config?  can you give an example?  It would be great if there was a dns change field in the menu.  Thanks 🙏🏻

`
  "dns": {
    "hosts": {
    	"vpncidns.ml": "185.190.18.97"
    },
    "servers": [
        {
      	"address": "localhost",
      	"port": 53,
      	"domains": ["geosite:netflix"],
      	"skipFallback": false
        },
	"https+local://vpncidns.ml/dns-query",
        "localhost"
    ]
  },
`

Even though I add it this way, the dns server does not work.  It's still showing cloudflare.

**Comment by VPNCI** [comment]
> > > "address": "https://1.1.1.1/dns-query"
> > 
> > 
> > yes i know that but how to add config? can you give an example? It would be great if there was a dns change field in the menu. Thanks 🙏🏻
> > `"dns": { "hosts": { "vpncidns.ml": "185.190.18.97" }, "servers": [ { "address": "localhost", "port": 53, "domains": ["geosite:netflix"], "skipFallback": false }, "https+local://vpncidns.ml/dns-query", "localhost" ] },`
> > Even though I add it this way, the dns server does not work. It's still showing cloudflare.
> 
> sorry I can't help you more,plz read official document of xray core.

Thanks 🫡
