### ISSUE TITLE
增加utls选项

### ISSUE THREAD

**Issue by Re-Aqest** [FranzKafkaYu/x-ui#197]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

能否增加一个utls选项,导入配置之后能直接启用

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@Re-Aqest utls设置只会在客户端生效 2.目前没有任何协议的分享链接支持对utls的解析
