### ISSUE TITLE
面板修改uuid后，客户端不做修改仍可以联网

### ISSUE THREAD

**Issue by jwd1208** [FranzKafkaYu/x-ui#199]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

X-UI搭建的vmess节点 客户端连接上网。在面板里修改uuid后，clash的节点不做修改也可以正常联网。不知道是不是bug。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@jwd1208 修改后不会立即生效，会等待几秒钟。请确认生成的配置文件内(/usr/local/x-ui/bin/ config.json)UUID已经变更完成。
