### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by dopaemon** [FranzKafkaYu/x-ui#2]
https://github.com/FranzKafkaYu/x-ui/blob/444c9e98cfcd835971c16c263d944aa9fe1f9780/web/job/stats_notify_job.go#L41

Cherry Pick : https://github.com/dopaemon/x-ui/commit/4b8d8142deaa4e092190e0247826a229e146807f

**Comment by FranzKafkaYu** [comment]
> https://github.com/FranzKafkaYu/x-ui/blob/444c9e98cfcd835971c16c263d944aa9fe1f9780/web/job/stats_notify_job.go#L41
> 
> Cherry Pick : [dopaemon@4b8d814](https://github.com/dopaemon/x-ui/commit/4b8d8142deaa4e092190e0247826a229e146807f)

Thank you bro.I didn't find this syntax error and goformat didn't make any error info here.I will fixed it later

**Comment by dopaemon** [comment]
> > https://github.com/FranzKafkaYu/x-ui/blob/444c9e98cfcd835971c16c263d944aa9fe1f9780/web/job/stats_notify_job.go#L41
> > 
> > Cherry Pick: [dopaemon @ 4b8d814](https://github.com/dopaemon/x-ui/commit/4b8d8142deaa4e092190e0247826a229e146807f)
> 
> Cảm ơn người anh em, tôi không tìm thấy lỗi cú pháp này và goformat không đưa ra bất kỳ thông tin lỗi nào ở đây. Tôi sẽ sửa nó sau

Logout and Login agan . This will error . Cherry Pick this commit from me :))))

**Comment by FranzKafkaYu** [comment]
> > > https://github.com/FranzKafkaYu/x-ui/blob/444c9e98cfcd835971c16c263d944aa9fe1f9780/web/job/stats_notify_job.go#L41
> > > 
> > > Cherry Pick: [dopaemon @ 4b8d814](https://github.com/dopaemon/x-ui/commit/4b8d8142deaa4e092190e0247826a229e146807f)
> > 
> > 
> > Cảm ơn người anh em, tôi không tìm thấy lỗi cú pháp này và goformat không đưa ra bất kỳ thông tin lỗi nào ở đây. Tôi sẽ sửa nó sau
> 
> Logout and Login agan . This will error . Cherry Pick this commit from me :))))

Sorry,I have no such problem in my own Server,Could please provide more details?such as logs~

**Comment by dopaemon** [comment]
> > > > https://github.com/FranzKafkaYu/x-ui/blob/444c9e98cfcd835971c16c263d944aa9fe1f9780/web/job/stats_notify_job.go#L41
> > > > 
> > > > Cherry Pick: [dopaemon @ 4b8d814](https://github.com/dopaemon/x-ui/commit/4b8d8142deaa4e092190e0247826a229e146807f)
> > > 
> > > 
> > > Cảm ơn người anh em, tôi không tìm thấy lỗi cú pháp này và goformat không đưa ra bất kỳ thông tin lỗi nào ở đây. Tôi sẽ sửa nó sau
> > 
> > 
> > Logout and Login agan . This will error . Cherry Pick this commit from me :))))
> 
> Sorry,I have no such problem in my own Server,Could please provide more details?such as logs~

On amd64 this work but on RaspberryPI Arm64 this not work.
