### ISSUE TITLE
监听的ipv6地址，使用的电信网络不支持ipv6导致无法访问

### ISSUE THREAD

**Issue by linrol** [FranzKafkaYu/x-ui#200]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

监听的ipv6地址，使用的电信网络不支持ipv6导致无法访问

### Version of x-ui

![image](https://user-images.githubusercontent.com/18043615/205859997-dfa04d56-b25b-475d-bec1-6b24bc4c20bb.png)

### x-ui log or xray log

![image](https://user-images.githubusercontent.com/18043615/205860008-52b63fac-84e2-41aa-8d35-1f7a34dc474b.png)

**Comment by FranzKafkaYu** [comment]
@linrol 本身v6是兼容v4地址的，即使是监听v6，v4仍可以连接，如果开启内核选项BindIPv6Only才无法用v4连接。可以参考下图：  
![image](https://user-images.githubusercontent.com/38254177/205862051-e3ead912-d47b-416b-8b41-0305b11576f9.png)  

x-ui监听端口2096，服务端v4/v6都有，而客户端实际通过v4进行访问，开头ffff会做为v4转v6填充的内容。  

如果你无法访问，请参考WIKI文档中的常见问题说明。
