### ISSUE TITLE
404 Page Not Found (XUI)

### ISSUE THREAD

**Issue by khalequzzaman17** [FranzKafkaYu/x-ui#201]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

404 page not found - error on the XUI, checked all the pages, same issue.

also, I try updating, restarting and removing, and installing again but still the same!

it happens with the default credentials (port 54321 and with the custom)

the version I am using is 0.3.3.18

### Version of x-ui

<details>
DELETE FOR PRIVACY
```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console

```

</details>

**Comment by khalequzzaman17** [comment]
I think it's because of the "Panel root path". How can I modify it from the CLI? Can you please mention the config file name with the full path/destination?

**Comment by FranzKafkaYu** [comment]
@khalequzzaman17 I didn't add command to set the root path via bash.when you login in your panel first time,it will generate a random root path and you can find it in control menu,just type "x-ui" and "7" in  server side.

**Comment by khalequzzaman17** [comment]
ase-256-gem (changed the method to it and worked like a charm!)

thanks for making it english

**Comment by FranzKafkaYu** [comment]
@khalequzzaman17 I don't know whether outline has supported shadowsocks2022,you should use shadowsocksAEAD,or use other client APP to test,V2rayNG/V2rayN should be OK
