### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by OghabTeam** [FranzKafkaYu/x-ui#208]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Please put the option to limit the bandwidth on the clients. We want to provide service to customers from only one port.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@OghabTeam No.

**Comment by OghabTeam** [comment]
why?! :/

**Comment by FranzKafkaYu** [comment]
@OghabTeam I don't wanna develop such function while you guys make money from my free work.
