### ISSUE TITLE
pls add a device connection limite on vmess/vless+ws

### ISSUE THREAD

**Issue by xmohammad1** [FranzKafkaYu/x-ui#220]
hi there
can you pls add a device connection limite or IP Restrication Per Inbound
thanks in advance

**Comment by sarahtuska** [comment]
IP Restriction Per Inbound is not good for countries like Iran or chine or Russia ( cause, when We use another local server to forward traffics to this server and bypass the restriction when they limited internet connectivity ) but device connection per inbound is gonna be the key here . would be nice if they can implemented in for the future release .

**Comment by FranzKafkaYu** [comment]
impossible.
