### ISSUE TITLE
Set the web folder on install for security

### ISSUE THREAD

**Issue by iopq** [FranzKafkaYu/x-ui#223]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

The user should just set whatever web folder they want at install time like they do with the port. That way the admin UI isn't on / by default

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
now we have random settings for username/password and port，it’s enough.
