### ISSUE TITLE
xray和面板均无法正常运行启动

### ISSUE THREAD

**Issue by YeJoe** [FranzKafkaYu/x-ui#23]
**系统信息**：Arm64，Ubuntu20.04
![uname](https://user-images.githubusercontent.com/48477050/167640837-84a27c43-7512-4e5b-a563-a7fca59b0794.png)

**问题描述**：使用一键脚本运行后，正常输入账号密码及端口，然后脚本显示面板和xray状态都是未运行。rm x-ui/ /usr/local/x-ui/ /usr/bin/x-ui -rf 删除相关目录后，用手动安装模式也是一样的状态。
PS：使用原作者一键脚本可以正常运行，但没有bot提醒功能。顺便再问下作者，关于面板提醒这方面的功能，考虑接入[bark推送](https://github.com/Finb/Bark)吗
![211652](https://user-images.githubusercontent.com/48477050/167637355-9f6a541a-50f0-4723-9ef3-2d3ebe5cefd7.png)
**日志显示如下**：
![212234](https://user-images.githubusercontent.com/48477050/167638519-acf1a5f8-c9ad-43ec-b2af-531934267dfb.png)
**输入7 查看面板设置，显示如下**：

![212438](https://user-images.githubusercontent.com/48477050/167639160-05dd8201-ebb2-43c7-9a39-5622688df048.png)

**Comment by FranzKafkaYu** [comment]
> **系统信息**：Arm64，Ubuntu20.04 ![uname](https://user-images.githubusercontent.com/48477050/167640837-84a27c43-7512-4e5b-a563-a7fca59b0794.png)
> 
> **问题描述**：使用一键脚本运行后，正常输入账号密码及端口，然后脚本显示面板和xray状态都是未运行。rm x-ui/ /usr/local/x-ui/ /usr/bin/x-ui -rf 删除相关目录后，用手动安装模式也是一样的状态。 PS：使用原作者一键脚本可以正常运行，但没有bot提醒功能。顺便再问下作者，关于面板提醒这方面的功能，考虑接入[bark推送](https://github.com/Finb/Bark)吗 ![211652](https://user-images.githubusercontent.com/48477050/167637355-9f6a541a-50f0-4723-9ef3-2d3ebe5cefd7.png) **日志显示如下**： ![212234](https://user-images.githubusercontent.com/48477050/167638519-acf1a5f8-c9ad-43ec-b2af-531934267dfb.png) **输入7 查看面板设置，显示如下**：
> 
> ![212438](https://user-images.githubusercontent.com/48477050/167639160-05dd8201-ebb2-43c7-9a39-5622688df048.png)

请问安装的面板版本是最新版本么

**Comment by YeJoe** [comment]
> > **系统信息**：Arm64，Ubuntu20.04 ![uname](https://user-images.githubusercontent.com/48477050/167640837-84a27c43-7512-4e5b-a563-a7fca59b0794.png)
> > **问题描述**：使用一键脚本运行后，正常输入账号密码及端口，然后脚本显示面板和xray状态都是未运行。rm x-ui/ /usr/local/x-ui/ /usr/bin/x-ui -rf 删除相关目录后，用手动安装模式也是一样的状态。 PS：使用原作者一键脚本可以正常运行，但没有bot提醒功能。顺便再问下作者，关于面板提醒这方面的功能，考虑接入[bark推送](https://github.com/Finb/Bark)吗 ![211652](https://user-images.githubusercontent.com/48477050/167637355-9f6a541a-50f0-4723-9ef3-2d3ebe5cefd7.png) **日志显示如下**： ![212234](https://user-images.githubusercontent.com/48477050/167638519-acf1a5f8-c9ad-43ec-b2af-531934267dfb.png) **输入7 查看面板设置，显示如下**：
> > ![212438](https://user-images.githubusercontent.com/48477050/167639160-05dd8201-ebb2-43c7-9a39-5622688df048.png)
> 
> 请问安装的面板版本是最新版本么

安装完面板是未运行，无法启动，我访问不了面板。但用的是你的一键脚本，应该是最新的吧

**Comment by YeJoe** [comment]
> > > **系统信息**：Arm64，Ubuntu20.04 ![uname](https://user-images.githubusercontent.com/48477050/167640837-84a27c43-7512-4e5b-a563-a7fca59b0794.png)
> > > **问题描述**：使用一键脚本运行后，正常输入账号密码及端口，然后脚本显示面板和xray状态都是未运行。rm x-ui/ /usr/local/x-ui/ /usr/bin/x-ui -rf 删除相关目录后，用手动安装模式也是一样的状态。 PS：使用原作者一键脚本可以正常运行，但没有bot提醒功能。顺便再问下作者，关于面板提醒这方面的功能，考虑接入[bark推送](https://github.com/Finb/Bark)吗 ![211652](https://user-images.githubusercontent.com/48477050/167637355-9f6a541a-50f0-4723-9ef3-2d3ebe5cefd7.png) **日志显示如下**： ![212234](https://user-images.githubusercontent.com/48477050/167638519-acf1a5f8-c9ad-43ec-b2af-531934267dfb.png) **输入7 查看面板设置，显示如下**：
> > > ![212438](https://user-images.githubusercontent.com/48477050/167639160-05dd8201-ebb2-43c7-9a39-5622688df048.png)
> > 
> > 
> > 请问安装的面板版本是最新版本么
> 
> 安装完面板是未运行，无法启动，我访问不了面板。但用的是你的一键脚本，应该是最新的吧

手动部署的话，也是用的release里最新的arm64

**Comment by YeJoe** [comment]
刚才试了一下0.3.3.8这个，还是不行。尝试输入10重启显
![220520](https://user-images.githubusercontent.com/48477050/167648221-3bdb76d8-4e44-4254-937a-a9d6bed9fd9e.png)
示
日志和之前一样
![220603](https://user-images.githubusercontent.com/48477050/167648339-6f69fac1-6a4b-4d80-beea-14ab832b8b35.png)

**Comment by YeJoe** [comment]
/usr/local/x-ui/ /usr/bin/x-ui我确认已经删除干净了。不过我突然想起来之前手动安装的时候，执行过 cp -f x-ui/x-ui.service /etc/systemd/system/  这句命令，然后我到相应目录发现确实存在，然后删除，再试一下你的脚本，发现还是不能运行。之后重启服务器，确认 /usr/local/x-ui/    /usr/bin/x-ui      /etc/systemd/system/x-ui.service    /etc/systemd/system# ls /etc/systemd/system/multi-user.target.wants/x-ui.service   都不存在。然后再用一件脚本重新安装，还是不行。。可能是我服务器的问题，感谢作者耐心回复。

**Comment by YeJoe** [comment]
> > 刚才试了一下0.3.3.8这个，还是不行。尝试输入10重启显 ![220520](https://user-images.githubusercontent.com/48477050/167648221-3bdb76d8-4e44-4254-937a-a9d6bed9fd9e.png) 示 日志和之前一样 ![220603](https://user-images.githubusercontent.com/48477050/167648339-6f69fac1-6a4b-4d80-beea-14ab832b8b35.png)
> 
> 再次确认了一下，软件是没有问题的，目前只能怀疑你卸载没有卸载干净。请确认 /usr/local/x-ui 目录下的所有内容是否完全被清除掉，可以自行rm进行清除,然后再行安装。
/usr/local/x-ui/ /usr/bin/x-ui我确认已经删除干净了。不过我突然想起来之前手动安装的时候，执行过 cp -f x-ui/x-ui.service /etc/systemd/system/ 这句命令，然后我到相应目录发现确实存在，然后删除，再试一下你的脚本，发现还是不能运行。之后重启服务器，确认 /usr/local/x-ui/ /usr/bin/x-ui /etc/systemd/system/x-ui.service /etc/systemd/system# ls /etc/systemd/system/multi-user.target.wants/x-ui.service 都不存在。然后再用一件脚本重新安装，还是不行。。可能是我服务器的问题，感谢作者耐心回复。

**Comment by FranzKafkaYu** [comment]
> > > 刚才试了一下0.3.3.8这个，还是不行。尝试输入10重启显 ![220520](https://user-images.githubusercontent.com/48477050/167648221-3bdb76d8-4e44-4254-937a-a9d6bed9fd9e.png) 示 日志和之前一样 ![220603](https://user-images.githubusercontent.com/48477050/167648339-6f69fac1-6a4b-4d80-beea-14ab832b8b35.png)
> > 
> > 
> > 再次确认了一下，软件是没有问题的，目前只能怀疑你卸载没有卸载干净。请确认 /usr/local/x-ui 目录下的所有内容是否完全被清除掉，可以自行rm进行清除,然后再行安装。
> > /usr/local/x-ui/ /usr/bin/x-ui我确认已经删除干净了。不过我突然想起来之前手动安装的时候，执行过 cp -f x-ui/x-ui.service /etc/systemd/system/ 这句命令，然后我到相应目录发现确实存在x-ui.service，然后删除，再试一下你的脚本，发现还是不能运行。之后重启服务器，确认 /usr/local/x-ui/ /usr/bin/x-ui /etc/systemd/system/x-ui.service      /etc/systemd/system/multi-user.target.wants/x-ui.service 都不存在。然后再用一件脚本重新安装，还是不行。。可能是我服务器的问题，感谢作者耐心回复。

你好，请问你的系统是arm64架构的吗，我貌似找到原因了

**Comment by YeJoe** [comment]
> > > > 刚才试了一下0.3.3.8这个，还是不行。尝试输入10重启显 ![220520](https://user-images.githubusercontent.com/48477050/167648221-3bdb76d8-4e44-4254-937a-a9d6bed9fd9e.png) 示 日志和之前一样 ![220603](https://user-images.githubusercontent.com/48477050/167648339-6f69fac1-6a4b-4d80-beea-14ab832b8b35.png)
> > > 
> > > 
> > > 再次确认了一下，软件是没有问题的，目前只能怀疑你卸载没有卸载干净。请确认 /usr/local/x-ui 目录下的所有内容是否完全被清除掉，可以自行rm进行清除,然后再行安装。
> > > /usr/local/x-ui/ /usr/bin/x-ui我确认已经删除干净了。不过我突然想起来之前手动安装的时候，执行过 cp -f x-ui/x-ui.service /etc/systemd/system/ 这句命令，然后我到相应目录发现确实存在x-ui.service，然后删除，再试一下你的脚本，发现还是不能运行。之后重启服务器，确认 /usr/local/x-ui/ /usr/bin/x-ui /etc/systemd/system/x-ui.service      /etc/systemd/system/multi-user.target.wants/x-ui.service 都不存在。然后再用一件脚本重新安装，还是不行。。可能是我服务器的问题，感谢作者耐心回复。
> 
> 你好，请问你的系统是arm64架构的吗，我貌似找到原因了

是的，请问是什么原因？
