### ISSUE TITLE
cf域名解析的没问题，但是证书签发失败，不知道什么原因

### ISSUE THREAD

**Issue by rongguoxiao** [FranzKafkaYu/x-ui#24]
![屏幕截图 2022-05-11 104521](https://user-images.githubusercontent.com/71001341/167758829-2a3ca3fc-bf45-421e-80fb-d9c867393f30.png)

**Comment by FranzKafkaYu** [comment]
> ![屏幕截图 2022-05-11 104521](https://user-images.githubusercontent.com/71001341/167758829-2a3ca3fc-bf45-421e-80fb-d9c867393f30.png)

免费域名是无法通过DNS API进行申请证书的，请尝试使用其他方式进行申请。
