### ISSUE TITLE
关于客户端模式、透明代理、反向代理设置增加的请求

### ISSUE THREAD

**Issue by Febtw** [FranzKafkaYu/x-ui#25]
您好！
很冒昧，但是还是想提一下自己的请求
1、是否可以增加一个客户端模式，作为本地客户端的webui
2、如果可以实现 1 的话，还请适配路由器，并强烈请求增加透明代理的设置
3、可否增加反向代理的设置

**Comment by SymSym3** [comment]
> 

反代自行装个nginx，fallback回落到80端口就行了

**Comment by Febtw** [comment]
> > 
> 
> 反代自行装个nginx，fallback回落到80端口就行了

好吧，想着能利用 xray 设置 bridge/portal 来实现，把nginx省了

**Comment by SymSym3** [comment]
> 

确实也是个好主意，但是感觉作者懒，好久没来看issues板块了，哈哈哈。要不去去pull request板块提议一下？

**Comment by Febtw** [comment]
原作把issues关了，pull request板块还能提建议的吗

**Comment by SymSym3** [comment]
不知道，试一试吧

Febtw ***@***.***> 于2022年5月30日周一 22:05写道：
