### ISSUE TITLE
1 user 1 port

### ISSUE THREAD

**Issue by Havard20009** [FranzKafkaYu/x-ui#256]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello
i just read the issues ,and i couldn't find my answer
i can use one port for 3 users yes ?it means i can make 3 different users in same port ?
 but ill try to make it but received error. 
"add inbound failed: current port is already in use: 443"
i only add one user on this port
what should i do ?
thank you

### Version of x-ui

v1.7.3

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@Havard20009 You can add many users in one same port.but you can't add many inbound with same port. it's illegal.

**Comment by Havard20009** [comment]
thank you
