### ISSUE TITLE
Can't login to Panel

### ISSUE THREAD

**Issue by sepehrrostami** [FranzKafkaYu/x-ui#258]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi
Telegram Bot timeout would prevent you from login to panel
It is necessary to add a function that ignore it

### Version of x-ui

<details>

```console
$ x-ui version
# 0.3.2
```

</details>

### x-ui log or xray log

<details>

```console
# get tgbot error: Post "https://api.telegram.org/bot/getMe": dial tcp 10.10.34.36:443: i/o timeout
```

</details>

**Comment by FranzKafkaYu** [comment]
@sepehrrostami this error won't have any effect on logining, please provide more info.For example:404 not found error etc. Screenshot would be great.

**Comment by sepehrrostami** [comment]
It is interesting.
I tried again and this time I successfully logged into the panel. Before this, I tried several times but it is the first time working

2023/02/08 01:36:42 x-ui 0.3.2
2023/02/08 01:36:43 INFO - web server run http on [::]:54321
2023/02/08 01:36:44 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:36:47 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:36:50 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:36:52 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:36:53 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:36:56 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:36:57 INFO - admin login success,Ip Address:10.128.12.1
2023/02/08 01:36:59 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:02 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:05 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:08 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:11 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:14 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:17 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:20 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:23 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:26 [sessions] ERROR! securecookie: the value is not valid
get tgbot error: Post "https://api.telegram.org/bot/getMe": dial tcp 10.10.34.36:443: i/o timeout
2023/02/08 01:37:27 [sessions] ERROR! securecookie: the value is not valid
2023/02/08 01:37:27 INFO - user 1 login success

> @sepehrrostami this error won't have any effect on logining, please provide more info.For example:404 not found error etc. Screenshot would be great.

**Comment by FranzKafkaYu** [comment]
the problem is about Cookie, next time ylu can clear all of Cookies or change another browser first.
