### ISSUE TITLE
TLS version Changer Not working

### ISSUE THREAD

**Issue by lahirubro123** [FranzKafkaYu/x-ui#259]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

TLS change to 1.2 but nothing changed my ISP blocked tls 1.3

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
plz provide more details，how do you observe TLS version and what‘s your configuration.

**Comment by lahirubro123** [comment]
i use v2ray configs for bypass my isp . but they blocked TLS 1.3 then my configs were not able to connect . but using ssl - ws i can connect configs without any trouble after get blocked 1.3TLS

ssh clients have option to switch TLS in app 
![image](https://user-images.githubusercontent.com/72745298/217726774-10310bd4-a1d3-4f14-9166-627a28f21b2e.png)
 
But v2ray client doesn't  have that feature and i think it can change in server side ! , SSH configs working for this methode 
but not fast and stable like v2ray . so i wanna chnage my v2ray server TLS to  1.2 and bypass my isp

**Comment by FranzKafkaYu** [comment]
the tls version configuration in X-UI is for xray core, can't represent the tls version of SSH,if you relay your SSH traffic via Xray, it should be OK.
