### ISSUE TITLE
您好作者。

### ISSUE THREAD

**Issue by rianjskis** [FranzKafkaYu/x-ui#26]
请问可以回落吗。

**Comment by SymSym3** [comment]
> 请问可以回落吗。

可以的

**Comment by rianjskis** [comment]
> > 请问可以回落吗。
> 
> 可以的

请问是在xray配置文件修改，还是直接在面板fallbacks。 dest这里直接填写域名的回落端口就好了呀。

**Comment by SymSym3** [comment]
> 

面板里dest直接写就行，然后tls里alpn需要用http/1.1

**Comment by rianjskis** [comment]
> > 
> 
> 面板里dest直接写就行，然后tls里alpn需要用http/1.1

好的感谢。请问面板的fallback1 里的alpn要写http/1.1吗。

**Comment by SymSym3** [comment]
回落里的alpn参数可以写也可以不写

rianjskis ***@***.***> 于2022年6月3日周五 20:10写道：
