### ISSUE TITLE
单个用户流量超限后关闭，无法开启

### ISSUE THREAD

**Issue by zixu5u** [FranzKafkaYu/x-ui#261]
0.3.4.0版本，单个用户流量超限后自动关闭，然后无法开启该用户，只能更改email才能够开启。
![1](https://user-images.githubusercontent.com/33487755/217874625-32c7cfe9-226f-4f0f-bf0e-d938099bedc1.png)

**Comment by FranzKafkaYu** [comment]
@zixu5u 清除端口流量或者将用户流量限制调整为更大数值。
