### ISSUE TITLE
User creation limit

### ISSUE THREAD

**Issue by sedddigh** [FranzKafkaYu/x-ui#265]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi , can you increase the limit of creating users with one port? Now only I can create 10 users with each port.  thank you

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by sedddigh** [comment]
Hi, can you increase the limit of creating users with one port? Now only I can create 10 users with each port.  thank you

**Comment by FranzKafkaYu** [comment]
No.If you have such need,please contact me at loveme@duck.com
