### ISSUE TITLE
Add Expiry Date for each user

### ISSUE THREAD

**Issue by Bardiafa** [FranzKafkaYu/x-ui#267]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Add Expiry Date for each user would be so awesome

This update is soo great 😁

And add ults settings for each client in trojan protocol

### Version of x-ui

<details>

```console
$ x-ui version
0.3.4.0
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Bardiafa** [comment]
Please add it😔

**Comment by esmaeilch81** [comment]
Please add it😔

**Comment by abaqqal** [comment]
چه خبر؟ چیزی نگفته؟

**Comment by hossein-mohseni** [comment]
> چه خبر؟ چیزی نگفته؟

https://github.com/FranzKafkaYu/x-ui/discussions/271#discussioncomment-5019424

**Comment by FranzKafkaYu** [comment]
done
