### ISSUE TITLE
[Feature Request] auto fill cert files from UI panel setting

### ISSUE THREAD

**Issue by livingfree2023** [FranzKafkaYu/x-ui#268]
Can we autofill certificate and key path from UI panel settings when we create new rule? 
能否在新建入站规则时，自动从面版设置中获取证书和密钥路径作为默认路径填进去？这样只要填写一次就够了，大大减轻维护入站规则的负担

**Comment by Havard20009** [comment]
yes please.

**Comment by arash88** [comment]
+1

**Comment by cqjerry** [comment]
+1

**Comment by FranzKafkaYu** [comment]
当前版本已经实现。
