### ISSUE TITLE
伪装网址需求

### ISSUE THREAD

**Issue by coxlxd** [FranzKafkaYu/x-ui#27]
功能相当不错
由于墙也会探测服务器，急切需要面板加个伪装网址功能
当使用WS+TLS等协议时候，能支持正确路径走正常流量，不正确路径跳转去设置好的伪装网址，以免被探测识别，

**Comment by SymSym3** [comment]
> 
可以装个nginx反代到其他网站，面板里所有节点最后都fallback回落到80本机口给nginx

**Comment by FranzKafkaYu** [comment]
不支持。
