### ISSUE TITLE
浏缆器显示问题

### ISSUE THREAD

**Issue by gn73679** [FranzKafkaYu/x-ui#274]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

使用 chrome 浏缆器 ，登入帐密后会空白
![image](https://user-images.githubusercontent.com/70200185/219909466-c68841f5-9b7e-4626-8e20-a4744d74f16c.png)

使用 360 浏缆器，正常
![image](https://user-images.githubusercontent.com/70200185/219909477-017340e2-aab8-4f5d-8ca4-dce061319b9e.png)

### Version of x-ui

<details>
0.3.4
```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by zonbar** [comment]
清一下缓存

**Comment by gn73679** [comment]
> 清一下缓存

清 缓存 无效
满奇怪的一点
装 英文版   chrome 浏缆器 正常
中文版 chrome 浏缆器 没登入页

**Comment by myownhoney** [comment]
我也遇到了同样的问题，但我是edge和chrome都打不开，最后下了一个小众的浏览器才打得开

**Comment by sumuen** [comment]
同样问题，稳定复现，面板设置面板 url 根路径之后再用nginx proxy manger进行代理，title显示登录但是网页白屏

**Comment by FranzKafkaYu** [comment]
个人无法复现你们的问题，若页面显示存在问题，可尝试如下方法：
1.清除浏览器缓存或者使用其他之前未曾登录过的浏览器
2.尝试切换语言为英文/中文（简体）

若仍旧无法解决，可以F12查看页面是否有报错信息，提供报错信息

**Comment by sumuen** [comment]
> 同样问题，稳定复现，面板设置面板 url 根路径之后再用nginx proxy manger进行代理，title显示登录但是网页白屏

是我自己的问题，勾选了nginx proxy manager 的cache assets导致缓存不能及时更新，打扰了

**Comment by twu2** [comment]
看起來應該是 server 端的問題.

<a-input v-model.trim="user.username" placeholder='{{ i18n "username" }}'
以 login 的頁面來看, 由 server 送出的資料會斷在 placeholder=' 這邊, 應該是 i18n 那一段的處理不正確造成. (其他的頁面也一樣, 都是停在第一個 i18 處理的地方)
如果 header 的 Accept-Language 不是 zh-CN 的等級最高的話, 就會造成問題.

目前 github 上面, 除了說明跟 .sh 有更新外, 其他的程式碼並沒有更新, 所以看不到最新的代碼.
只能知道是 i18n 那一段有問題, 具體的問題就不清楚了.

**Comment by FranzKafkaYu** [comment]
这与浏览器语言选项有关，如果你安装中文版本，请设置浏览器语言为简体中文，当前的多语言适配是存在问题的。

Tommy Wu ***@***.***> 于2023年4月12日周三 12:21写道：

**Comment by twu2** [comment]
改瀏覽器的設定對使用者來說不算友善的解決方法. 因為那並不是只針對某個網站的設定. 會影響全部的網站.
如果多語言的問題無法簡單解決, 而要保留目前這種中文版本與英文版本分開的做法, 那不如程式那邊把 i18 拿掉, 直接把字串寫到 html 中, 反而不會有問題.

我目前是透過 nginx 的反向代理, 改掉 http 的 header 來避開這個問題.
proxy_set_header Accept-Language "zh-CN;q=0.9"
