### ISSUE TITLE
会增加新的 REALITY 吗

### ISSUE THREAD

**Issue by btmouse** [FranzKafkaYu/x-ui#275]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

会增加新的 REALITY 吗

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@btmouse 需等到上游发布正式版本，且提供配置信息与新的分享链接标准。

**Comment by LOVECHEN** [comment]
> 

https://github.com/XTLS/REALITY

**Comment by itdsgithub** [comment]
我想问一下，现在面板里，控流选项里没有LESS XTLS Vision选项，这个能添加进去吗

**Comment by FranzKafkaYu** [comment]
@itdsgithub 当前支持Vision流控，选择VLESS协议，传输层选择TCP，开启tls后可以在用户信息内选择flow,选择xtls-rprx-vision即可。

**Comment by k-fire** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.0

**Comment by FranzKafkaYu** [comment]
> https://github.com/XTLS/Xray-core/releases/tag/v1.8.0

已经完成差不多了，但还需要上游规范分享链接标准，**应该快了**

**Comment by Pacio** [comment]
赶紧支持吧，好激动，这下连域名钱都省了，爽

**Comment by itdsgithub** [comment]
> 

请教一下，我不太理解为什么不需要域名了。
按照之前的方式，国外放个服务器，配置好，国内访问都是由国外那台服务器访问到正确网页，中转过来，现在方式是有什么不同吗

**Comment by k-fire** [comment]
> > https://github.com/XTLS/Xray-core/releases/tag/v1.8.0
> 
> 已经完成差不多了，但还需要上游规范分享链接标准，**应该快了**

[v2rayN](https://github.com/2dust/v2rayN)内置分享链接

vless://id@address:8080?encryption=none&flow=xtls-rprx-vision&security=reality&sni=sni&fp=randomized&type=tcp&headerType=none&host=host#remarks

**Comment by FranzKafkaYu** [comment]
> > > https://github.com/XTLS/Xray-core/releases/tag/v1.8.0
> > 
> > 
> > 已经完成差不多了，但还需要上游规范分享链接标准，**应该快了**
> 
> [v2rayN](https://github.com/2dust/v2rayN)内置分享链接
> 
> vless://id@address:8080?encryption=none&flow=xtls-rprx-vision&security=reality&sni=sni&fp=randomized&type=tcp&headerType=none&host=host#remarks

这份分享链接缺少很多关键信息，使用者仍需手动在客户端补充部分信息，还得再等等。

**Comment by Fangliding** [comment]
> > > > https://github.com/XTLS/Xray-core/releases/tag/v1.8.0
> > > 
> > > 
> > > 已经完成差不多了，但还需要上游规范分享链接标准，**应该快了**
> > 
> > 
> > [v2rayN](https://github.com/2dust/v2rayN)内置分享链接
> > vless://id@address:8080?encryption=none&flow=xtls-rprx-vision&security=reality&sni=sni&fp=randomized&type=tcp&headerType=none&host=host#remarks
> 
> 这份分享链接缺少很多关键信息，使用者仍需手动在客户端补充部分信息，还得再等等。

xray已经更新分享链接标准了

**Comment by itdsgithub** [comment]
> > > > > https://github.com/XTLS/Xray-core/releases/tag/v1.8.0
> > > > 
> > > > 
> > > > 已经完成差不多了，但还需要上游规范分享链接标准，**应该快了**
> > > 
> > > 
> > > [v2rayN](https://github.com/2dust/v2rayN)内置分享链接
> > > vless://id@address:8080?encryption=none&flow=xtls-rprx-vision&security=reality&sni=sni&fp=randomized&type=tcp&headerType=none&host=host#remarks
> > 
> > 
> > 这份分享链接缺少很多关键信息，使用者仍需手动在客户端补充部分信息，还得再等等。
> 
> xray已经更新分享链接标准了

加油加油，辛苦作者，我也想用新的客户端试试了

**Comment by mmrabbani** [comment]
I think the sharing link standard is established. V2rayNG 1.8.1 and v2rayN 6.19 implemented it.

**Comment by imauzzc** [comment]
期待作者更新，支持支持

**Comment by xLordHerox** [comment]
> > > > https://github.com/XTLS/Xray-core/releases/tag/v1.8.0
> > > 
> > > 
> > > It's almost done, but the upstream specification sharing link standard is still needed, **it should be soon**
> > 
> > 
> > [v2rayN](https://github.com/2dust/v2rayN) has built-in sharing links
> > vless://id@address:8080?encryption=none&flow=xtls-rprx-vision&security=reality&sni=sni&fp=randomized&type=tcp&headerType=none&host=host#remarks
> Xray has updated the sharing link standard
> This sharing link lacks a lot of key information, and users still need to manually add some information in the client, and they have to wait.
>I think the sharing link standard is established. V2rayNG 1.8.1 and v2rayN 6.19 implemented it.

Hi there. @FranzKafkaYu Any update to support Reality ? We can't create vless Reality config on web panel.

**Comment by simplerick-simplefun** [comment]
@FranzKafkaYu 上游已经更新了分享链接标准：
https://github.com/XTLS/Xray-core/discussions/716

另外请问一下，可以手动修改设置的节点config吗？如果可以的话，就不必等您这里更新。

**Comment by DreamFerry** [comment]
等不及了，快点端上来吧！

**Comment by FranzKafkaYu** [comment]
请使用最新版本。

**Comment by xxSaeidxx** [comment]
> 请使用最新版本。

Does the last version support Reality?

**Comment by FranzKafkaYu** [comment]
@xxSaeidxx yes,but you need set up xray core to 1.8.0

**Comment by xxSaeidxx** [comment]
> @xxSaeidxx yes,but you need set up xray core to 1.8.0

Thanks.😊
