### ISSUE TITLE
TLS握手错误如何解决？

### ISSUE THREAD

**Issue by cmssky** [FranzKafkaYu/x-ui#278]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

之前安装了原版的x-ui，https://github.com/vaxilu/x-ui ，使用一直没问题，今天早上突然发现无法连接了，日志提示TLS握手错误，google找不到解决方案，就想着重装一下看能不能解决问题，刚好看到您的修改版想着试一下，结果问题依旧。
日志提示：
https://raw.githubusercontent.com/cmssky/images_cdn/0d1b1e0e6fdc35fa869eb401832336adab806329/images/x-ui-TLS-handshake-error.jpg

### Version of x-ui

<details>

面板版本[version]: 0.3.4.0:20230209

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
今天早上突然发现无法连接了，日志提示TLS握手错误

请问无法连接是指无法连接面板还是无法连接节点?

**Comment by cmssky** [comment]
> 今天早上突然发现无法连接了，日志提示TLS握手错误
> 
> 请问无法连接是指无法连接面板还是无法连接节点?

面板没有问题，节点无法连接

**Comment by FranzKafkaYu** [comment]
@cmssky 图中的日志为面板自身的日志，关于连接状态的日志需要自行修改配置模板，增加log字段，根据xray core的连接日志进行判断。此外，遇到此类问题，请先检查客户端日志，根据客户端日志先行判断。

**Comment by cmssky** [comment]
> @cmssky 图中的日志为面板自身的日志，关于连接状态的日志需要自行修改配置模板，增加log字段，根据xray core的连接日志进行判断。此外，遇到此类问题，请先检查客户端日志，根据客户端日志先行判断。

好的，谢谢您的解答
