### ISSUE TITLE
 user traffic limitation and statistics not working

### ISSUE THREAD

**Issue by Stevemoretz** [FranzKafkaYu/x-ui#279]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

First see that the config actually shows the usages:

<img width="570" alt="Screen Shot 1401-12-13 at 14 24 15" src="https://user-images.githubusercontent.com/27680142/222895971-eb6f0622-6af7-4715-8258-1d0c3cfa4f67.png">

Now you can see that for every user the used amount is `used : 0 B`

<img width="472" alt="Screen Shot 1401-12-13 at 14 22 56" src="https://user-images.githubusercontent.com/27680142/222895961-3d8e7910-8281-444f-9d27-50e2c177c6d5.png">

Limit doesn't work on those even though you have created a UI for limiting every single user.

### Version of x-ui

<details>

```console
$ /usr/local/x-ui/x-ui -v
0.3.4.0:20230209
</details>

### x-ui log or xray log

<details>

```console
Mar 04 10:49:43 parham x-ui[679]: get signal: terminated
Mar 04 10:49:43 parham systemd[1]: Stopping x-ui Service...
Mar 04 10:49:44 parham systemd[1]: x-ui.service: Deactivated successfully.
Mar 04 10:49:44 parham systemd[1]: Stopped x-ui Service.
Mar 04 10:49:44 parham systemd[1]: x-ui.service: Consumed 9h 41min 49.901s CPU time.
Mar 04 10:51:44 parham systemd[1]: Started x-ui Service.
Mar 04 10:51:44 parham x-ui[3780055]: 2023/03/04 10:51:44 x-ui 0.3.4.0:20230209
Mar 04 10:51:44 parham x-ui[3780055]: 2023/03/04 10:51:44 INFO - web server run http on [::]:2052
Mar 04 10:51:44 parham x-ui[3780055]: 2023/03/04 10:51:44 INFO - We got 1 members in client
Mar 04 10:51:44 parham x-ui[3780055]: 2023/03/04 10:51:44 INFO - We got 2 members in client
Mar 04 10:51:44 parham x-ui[3780055]: 2023/03/04 10:51:44 INFO - We got 2 members in client
Mar 04 10:51:44 parham x-ui[3780055]: 2023/03/04 10:51:44 INFO - Wait 2 seconds for telegram bot ready
Mar 04 10:51:46 parham x-ui[3780055]: SSHLogin[2023-03-04 10:51:00] early than XUI start[2023-03-04 10:51:44],don't notify```

</details>

**Comment by Stevemoretz** [comment]
This is related to the last thing on your CHANGELOG
`2023.02.09: Support user traffic limitation and statistics within a single port; support VLESS utls configuration and share link export`

**Comment by FranzKafkaYu** [comment]
what's your configuration,show me plz. Hint:you need to ensure the xray config template is correct, see my release note or WIKI.

**Comment by Stevemoretz** [comment]
Thank you so much I updated using the CLI and I just found the release note and read them :) It got enabled by adding just this:

```
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
}
```

Amazing project thank you so much!
