### ISSUE TITLE
xtls-rprx-vision is not in the flow list

### ISSUE THREAD

**Issue by leomoon** [FranzKafkaYu/x-ui#280]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

xtls-rprx-vision is not in the flow list so it could be selected again.
![image](https://user-images.githubusercontent.com/3268946/222931898-2a06ba5c-d8e8-4dbb-8467-bc2f53d70f21.png)

If someone changes flow for any reason, they won't be able to select vision again.

### Version of x-ui

<details>

```console
$ x-ui version 0.3.4.1:20230304
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
xtls-rprx-vision is optional when you enable tls not xtls.

**Comment by leomoon** [comment]
But when VLESS and XTLS is selected, it defaults to vision...

**Comment by FranzKafkaYu** [comment]
@leomoon it won't changed automatic ally,you need choose the flow by yourself if you wanna make changes.

**Comment by leomoon** [comment]
That is fine if it works but `VLESS +TCP + XTLS + VISION` does not work. So vision should not be shown as option if xtls is selected (screenshot above). It should switch the flow menu to `xtls-rprx-direct` if xtls is selected instead.

A user would create a new VLESS + TCP + XTLS connection without chaning flow and that would create a connection that will not work.

It shows this error in v2ray mobile client:
```
Fail to detect internet connection: io: read/write on closed pipe
```

I can provide more info if you need.

**Comment by FranzKafkaYu** [comment]
> That is fine if it works but `VLESS +TCP + XTLS + VISION` does not work. So vision should not be shown as option if xtls is selected (screenshot above). It should switch the flow menu to `xtls-rprx-direct` if xtls is selected instead.
> 
> A user would create a new VLESS + TCP + XTLS connection without chaning flow and that would create a connection that will not work.
> 
> It shows this error in v2ray mobile client:
> 
> ```
> Fail to detect internet connection: io: read/write on closed pipe
> ```
> 
> I can provide more info if you need.

The flow name defined by upstream,I know xtls-rprx-vision flow need to enable tls is kind of misleading but it's OK.

I know what the problem is,but xtls is deprecated and will be removed in xray core 1.8.0.At that time there is no xtls any more.

**Comment by FranzKafkaYu** [comment]
Yes.it may be a problem.I have updated the release.now the default flow
will be none.

Amin Persia ***@***.***> 于2023年3月5日周日 08:11写道：
