### ISSUE TITLE
很严重可能存在安全漏洞的问题

### ISSUE THREAD

**Issue by wzry623090** [FranzKafkaYu/x-ui#281]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

目前查x-ui面板没有添加防扫描机制 极易容易被扫描到IP或者端口，密码的话可以爆破或者直接尝试默认的密码即可被别人登进去，很严重的漏洞

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@wzry623090 当前有随机根路径，随机用户名，密码与端口，无法扫描。此外也有面板登录提醒。
