### ISSUE TITLE
关于协议的问题

### ISSUE THREAD

**Issue by wzry623090** [FranzKafkaYu/x-ui#282]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

怎么感觉？wmess 这个协议好像被识别，不知道什么原因。希望能增强一下啊，要么，可以增加这个协议的话就更好，但是感觉这个协议更有难度naive，这种就可以，但是完全，节点被封的可能性大于80%吧！

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@wzry623090 X-UI之前一个管理面板，协议由xray core核心提供。协议推荐使用VLESS tls xtls-rprx-vision,不推荐VMESS.
