### ISSUE TITLE
Bug in setting the expiry date for each user with trojan protocol

### ISSUE THREAD

**Issue by GoldExynos** [FranzKafkaYu/x-ui#283]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi.
After updating to the latest version, there is a bug while setting the expiry date with trojan protocol for each user of inbounds.
Every time you reload the panel or want to create a new inbound or user with trojan protocol, the box of expiry date for users, shows the current date and time and you can't delete or change the time in the box.
Could you please check the problem?
Thanks.

### Version of x-ui

<details>

```console
$ x-ui version
0.3.4.1
```

</details>

### x-ui log or xray log

<details>

```console
Mar 05 11:41:09 Server-X2-2 x-ui[2611539]: ConstructPortReplyKeyBoardRow: 9
Mar 05 11:41:14 Server-X2-2 x-ui[2611539]: close socket successfully,dst:xx.xx.xx.xx
Mar 05 11:41:14 Server-X2-2 x-ui[2611539]: close socket successfully,dst:xx.xx.xx.xx
Mar 05 11:41:19 Server-X2-2 x-ui[2611539]: close socket successfully,dst:xx.xx.xx.xx
Mar 05 11:41:24 Server-X2-2 x-ui[2611539]: close socket successfully,dst:xx.xx.xx.xx
Mar 05 11:41:39 Server-X2-2 x-ui[2611539]: ConstructPortReplyKeyBoardRow: 9
Mar 05 11:41:49 Server-X2-2 x-ui[2611539]: close socket successfully,dst:xx.xx.xx.xx
Mar 05 11:41:49 Server-X2-2 x-ui[2611539]: close socket successfully,dst:xx.xx.xx.xx
Mar 05 11:42:09 Server-X2-2 x-ui[2611539]: ConstructPortReplyKeyBoardRow: 9
```

</details>

**Comment by FranzKafkaYu** [comment]
@GoldExynos  fixed,plz reinstall the latest release.
