### ISSUE TITLE
咨询一个 设备限制的问题

### ISSUE THREAD

**Issue by ezreal130** [FranzKafkaYu/x-ui#284]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

想请问下面入站规则中的 设备限制是不是基于IP做的限制，比如我一个局域网内有200个用户，通过一个公网ip出口连接，是不是只会识别成1个设备数量？
![image](https://user-images.githubusercontent.com/24875836/223335228-4677c5b9-3d39-4d9f-932f-1e3e18df36e0.png)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@ezreal130 是的，根据IP来识别限制，
