### ISSUE TITLE
Showing one QR code for multiple inbounds

### ISSUE THREAD

**Issue by vahidxo** [FranzKafkaYu/x-ui#289]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![Screenshot (8)](https://user-images.githubusercontent.com/122749732/224156875-152514fa-666d-4491-a371-95d81fdd1642.png)
![Screenshot (7)](https://user-images.githubusercontent.com/122749732/224156896-c5870078-6926-4630-8d74-b9d9b5207fd2.png)

Hi, I made two different user for one inbound but it shows only one QR code. where could be the problem?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details

### x-ui log or xray log

<details>

```console
# paste log here
```

</details
![Screenshot (9)](https://user-images.githubusercontent.com/122749732/224157898-2799c8b9-e3f1-44de-9c4e-0b5b242e75c6.png)

**Comment by FranzKafkaYu** [comment]
@vahidxo Just my problem because I didn't make multiple QR code for each user,only each sharing link for each user.
