### ISSUE TITLE
升级xray1.8.0版本后，trojan分流节点会因为自动加上的流控参数"xtls-rprx-direct"，导致xray无法启动。

### ISSUE THREAD

**Issue by ylimys** [FranzKafkaYu/x-ui#291]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

您好，x-ui太好用，感谢。
如题，在更新xray1.8.0，碰到一个问题，导致xray无法启动。
![image](https://user-images.githubusercontent.com/20252583/224276233-d1913e6d-541d-4196-94c2-1a1c771454c5.png)
无法启动，说多了个"xtls-rprx-direct"
我的配置，配置两个节点，一个vless+tls+vision，回落端口trojan
![image](https://user-images.githubusercontent.com/20252583/224276774-3e556077-51b4-40fb-a35f-919080d6d5e9.png)

![image](https://user-images.githubusercontent.com/20252583/224276510-0615d467-890b-4b7f-a5a9-4700c0c58b85.png)
vless配置

![image](https://user-images.githubusercontent.com/20252583/224277102-ba83d903-5410-4dbf-9858-50cb01acf716.png)
trojan配置

trojan的配置没有写流控，但是他会自动加上一个，"xtls-rprx-direct"，删不掉，删了自动又加上了。导致xray1.8.0报错，无法启动。
![image](https://user-images.githubusercontent.com/20252583/224278375-d3d3764b-f50e-43cd-8070-9382c3c2e335.png)
xray1.7.5是正常的，不报错，升级1.8.0后，会无法启动。x-ui是最新版的。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ylimys** [comment]
> 180取消消掉了这个旧xtls流控了，加入了现实，等老大修复和增加现实设置吧，暂时退回175。

好的，谢谢。

**Comment by yoasab1** [comment]
升级到0.3.4.2依旧不支持

**Comment by FranzKafkaYu** [comment]
@yoasab1 需要把原来的之前的配置删除或者重新选择一下流控。

**Comment by FranzKafkaYu** [comment]
should be fixed now, closed
