### ISSUE TITLE
failed to update traffic for client

### ISSUE THREAD

**Issue by PouryaDe** [FranzKafkaYu/x-ui#292]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

i get this error logs in /var/log/syslog

how can i fix this?

`
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3442@x146504695.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3304@x494664915.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3144@x190705629.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:itbx.love@xray.com,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:2BfI.love@xray.com,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3367@x383583228.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3228@x162667427.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3296@x473605892.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:V6uO.love@xray.com,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3227@x629928884.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3366@x479549934.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:iTJy.love@xray.com,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3335@x281101111.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:tDri.love@xray.com,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.emailMar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - failed to update traffic for client:S3249@x143982962.vpn,inboundId:0
Mar 11 22:29:38 server3 x-ui[709]: 2023/03/11 22:29:38 WARNING - AddClientTraffic update data error: UNIQUE constraint failed: client_infos.email
`

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by PouryaDe** [comment]
> is the latest x-ui version?

yes
and xray version is 1.7.5

**Comment by FranzKafkaYu** [comment]
@PouryaDe what version of x-ui?

**Comment by PouryaDe** [comment]
> @PouryaDe what version of x-ui?

面板版本[version]: 0.3.4.0:20230209

**Comment by FranzKafkaYu** [comment]
@PouryaDe Dude, it's not the latest x-ui version.

**Comment by FranzKafkaYu** [comment]
plz update to the latest version of x-ui.old versions may have this problem.
