### ISSUE TITLE
对已有的节点进行操作--编辑后没有反应

### ISSUE THREAD

**Issue by yoasab1** [FranzKafkaYu/x-ui#293]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

如果新增节点，在添加用户前进行编辑是可行的。一旦添加用户会假死，之后无法再进行编辑。

### Version of x-ui

<details>

```console
1.7.5
```

</details>

### x-ui log or xray log

<details>

```console
paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@yoasab1 出现问题时浏览器页面按下F12，看看是否有报错信息
