### ISSUE TITLE
切换xray版本为V1.8.0后，xra状态为error

### ISSUE THREAD

**Issue by hymslien** [FranzKafkaYu/x-ui#294]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

切换xray版本为V.80后，xra状态为error。
![xray 状态](https://user-images.githubusercontent.com/102838557/224606077-7944350f-2548-4b67-8d7b-171434c338ba.jpg)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@hymslien 尚未完全适配xray 1.8.0,如果要使用1.8.0,请不要使用Trojan协议是使用VLESS协议时请勿使用xtls-rprx-origin/ xtls-rprx-direct流控

**Comment by hymslien** [comment]
VLESS使用的是xtls-rprx-vision流控。

**Comment by FranzKafkaYu** [comment]
@hymslien 请删除Trojan协议

**Comment by EdenSeven** [comment]
> VLESS使用的是xtls-rprx-vision流控。

不要是xtls协议。改用tls.

**Comment by yao71232** [comment]
这个版本的x-ui创建trojan时，默认会多一个flow: xtls-rprx-direct，所以才会报错，用另外一个版本的x-ui不会生成这个流控就可以升级1.8.0

**Comment by biderpan-ai** [comment]
> 这个版本的x-ui创建trojan时，默认会多一个flow: xtls-rprx-direct，所以才会报错，用另外一个版本的x-ui不会生成这个流控就可以升级1.8.0

另一个版本是哪个版本啊

**Comment by FranzKafkaYu** [comment]
可使用最新版本进行测试。
