### ISSUE TITLE
Not displaying users in the panel

### ISSUE THREAD

**Issue by wikilinux-ir** [FranzKafkaYu/x-ui#296]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello
In order to delete some users who were disabled, I tried to delete them through sql query, and after this, most of the users in the database are not shown in the panel, even though they exist in the database, and their connection is also disconnected. because they were not added in the config file

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> Hello In order to delete some users who were disabled, I tried to delete them through sql query, and after this, most of the users in the database are not shown in the panel, even though they exist in the database, and their connection is also disconnected. because they were not added in the config file
> 
> ### Version of x-ui
> ### x-ui log or xray log

If you manipulate database manually,it may cause some problems,and I don't know what you have done so I can't help you. Maybe you can send your database to my Email box and I can take a look.if you wanna solve this problem, plz send it to loveme@duck.com
