### ISSUE TITLE
用户流量统计功能异常

### ISSUE THREAD

**Issue by HyWell** [FranzKafkaYu/x-ui#305]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

现在单端口多用户
总流量统计一切正常，但是不同用户的流量一直都为0。页面显示对应用户已激活。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@HyWell 请自行查看WIKI文档，或者release note.

**Comment by HyWell** [comment]
查看过release note
<img width="939" alt="image" src="https://user-images.githubusercontent.com/21263451/226260715-99f682b1-f22a-4a49-93cb-7525a5d68a10.png">
现在config文件配置如下
<img width="497" alt="image" src="https://user-images.githubusercontent.com/21263451/226268542-835e3ec7-8292-4ea2-b849-dcbef56ba4b0.png">

**Comment by FranzKafkaYu** [comment]
> 查看过release note <img alt="image" width="939" src="https://user-images.githubusercontent.com/21263451/226260715-99f682b1-f22a-4a49-93cb-7525a5d68a10.png"> 现在config文件配置如下 <img alt="image" width="497" src="https://user-images.githubusercontent.com/21263451/226268542-835e3ec7-8292-4ea2-b849-dcbef56ba4b0.png">

你的config配置当前不支持对用户流量进行统计，请按照release note的配置添加到配置模板内，重启面板。

**Comment by HyWell** [comment]
按照release note 配置之后 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/21263451/226269857-cebe5761-69ff-4ad3-962c-9ebc245b1877.png">

重启之后，config.json会被重置。
<img width="577" alt="image" src="https://user-images.githubusercontent.com/21263451/226269886-a12dbfdd-5061-41ab-9a96-6e5614aa553c.png">

**Comment by FranzKafkaYu** [comment]
> 按照release note 配置之后 <img alt="image" width="478" src="https://user-images.githubusercontent.com/21263451/226269857-cebe5761-69ff-4ad3-962c-9ebc245b1877.png">
> 
> 重启之后，config.json会被重置。 <img alt="image" width="577" src="https://user-images.githubusercontent.com/21263451/226269886-a12dbfdd-5061-41ab-9a96-6e5614aa553c.png">

所以你需要进入面板，在面板配置内修改配置模板，然后重启面板，直接修改config.json会被自动覆盖。

**Comment by HyWell** [comment]
了解了，之前一直修改的是config.json。现在通过web修改之后 可以统计了。多谢
