### ISSUE TITLE
JavaScript not loading in firefox

### ISSUE THREAD

**Issue by iopq** [FranzKafkaYu/x-ui#308]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![Screenshot from 2023-03-23 17-17-06](https://user-images.githubusercontent.com/1817528/227158028-e7371ac0-ad37-46cf-abfa-c311c3efc2b2.png)

### Version of x-ui

<details>

```console
$ x-ui version
this command doesn't give the version, but it's the latest master
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
It's your browser's problem. Plz use other browser instead.
