### ISSUE TITLE
add user limitation

### ISSUE THREAD

**Issue by amin1374** [FranzKafkaYu/x-ui#311]
im using lastest version of your script but i have problem  i cant add user more than 10 in every in bound please fix it or maybe its a bug

**Comment by amin1374** [comment]
https://github.com/FranzKafkaYu/x-ui/wiki/%E8%8A%82%E7%82%B9%E7%AE%A1%E7%90%86

The current latest version already supports single-port multi-user of VMess, Vless, and Trojan. In order to avoid abuse, each port is limited to a maximum of 10 users. Each user

im want no limitation or incresess 10 how i can do?

**Comment by FranzKafkaYu** [comment]
> https://github.com/FranzKafkaYu/x-ui/wiki/%E8%8A%82%E7%82%B9%E7%AE%A1%E7%90%86
> 
> The current latest version already supports single-port multi-user of VMess, Vless, and Trojan. In order to avoid abuse, each port is limited to a maximum of 10 users. Each user
> 
> im want no limitation or incresess 10 how i can do?

you can contact me via Email: loveme@duck.com
