### ISSUE TITLE
باگ گرافیکی

### ISSUE THREAD

**Issue by OghabTeam** [FranzKafkaYu/x-ui#313]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام از وقتی گرافیک پنل رو تغییر دادید این باگ بوجود اومده! من بیشتر از 400 تا یوزر دارم اما فقط صد و خورده ایشو نشون میده! متن ارور هم داخل اسکرین شات مشخصه..

![image_2023-03-27_12-15-06](https://user-images.githubusercontent.com/34192561/227874721-771cee79-fc1c-43ab-b622-c8a7bf84dc75.png)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
?
