### ISSUE TITLE
Restarting only xray.

### ISSUE THREAD

**Issue by xSerioUsx78** [FranzKafkaYu/x-ui#314]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

Hi, i hope you have a good day.

I coulden't found a way to only restart xray service, without restarting the hole x-ui.

is there anyway to do that ?

**Comment by xSerioUsx78** [comment]
@FranzKafkaYu Is there any way to restart xray with command line ?

**Comment by FranzKafkaYu** [comment]
No way currently.
