### ISSUE TITLE
Help with database file

### ISSUE THREAD

**Issue by lahirubro123** [FranzKafkaYu/x-ui#316]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://user-images.githubusercontent.com/72745298/228319688-590a741f-3862-4e44-a2e7-d2dae88811a8.png)
  

hello im student developer please help me how turn this inbound values readable !!  please support me 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
What do you mean
