### ISSUE TITLE
SS2022的密码生成与分享链接问题

### ISSUE THREAD

**Issue by NeetHuang** [FranzKafkaYu/x-ui#317]
SS2022自动的密码生成和分享链接在一些客户端上无法正常连接使用
建议针对 
2022-blake3-aes-256-gcm  使用  openssl rand -base64 32 自动生成密码
2022-blake3-chacha20-poly1305 使用  openssl rand -base64 32 自动生成密码
2022-blake3-aes-256-gcm  使用  openssl rand -base64 16 自动生成密码
分享链接采用与其他SS协议相同的base64格式 
当前为:  
ss://2022-blake3-aes-256-gcm:7A+r6h/uQMrqYvi1UdYd/UqL5QJVKu3ibph8R39mrf0=@127.0.0.1:30000#
标准为：ss://MjAyMi1ibGFrZTMtYWVzLTI1Ni1nY206N0ErcjZoL3VRTXJxWXZpMVVkWWQvVXFMNVFKVkt1M2licGg4UjM5bXJmMD0=@127.0.0.1:30000

**Comment by FranzKafkaYu** [comment]
@NeetHuang 密码长度问题可以针对性修改，但是分享链接标准由上游提出，旧的SS与SS2022分享链接标准是不同的，无法统一

**Comment by NeetHuang** [comment]
分享链接的标准就是base64的，base64可以被所有客户端识别，反而当前的生成链接形式不被部分客户端识别。

**Comment by FranzKafkaYu** [comment]
@NeetHuang ss2022的分享链接标准要求不使用base64，请自行查看相关分享标准信息。
