### ISSUE TITLE
How to change x-ui database directory in source codes? 

### ISSUE THREAD

**Issue by flightlover** [FranzKafkaYu/x-ui#318]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello
I want to change the directory of databese which x-ui is using with. The current directory is `/etc/x-ui/x-ui.db` . Where can I change it in source code? I don't find it in source codes.
Thanks

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
No support for such question.

**Comment by flightlover** [comment]
exactly why??
