### ISSUE TITLE
installing two panel in one server

### ISSUE THREAD

**Issue by sydalihosini** [FranzKafkaYu/x-ui#319]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello i want too install multiple panel in one server 
in ubuntu os i wondering how can i do this 

### Version of x-ui

lastest

### x-ui log or xray log

xray is strated

**Comment by FranzKafkaYu** [comment]
@sydalihosini Not impossible for now.

**Comment by sydalihosini** [comment]
What about Docker? ,I heard that it can be done

**Comment by FranzKafkaYu** [comment]
@sydalihosini docker should be OK,you should try by yourself.

**Comment by sydalihosini** [comment]
yes i test it and its work fine just change some of folder and name of CONTAINER

**if this is normal installing with docker** 

mkdir x-ui && cd x-ui
docker run -itd --network=host \
    -v $PWD/db/:/etc/x-ui/ \
    -v $PWD/cert/:/root/cert/ \
    --name x-ui --restart=unless-stopped \
    enwaiax/x-ui:alpha

**you most change like this** 

mkdir x-ui1 && cd x-ui1
docker run -itd --network=host \
    -v $PWD/db2/:/etc/x-ui1/ \
    -v $PWD/cert1/:/root/cert1/ \
    --name x-ui1 --restart=unless-stopped \
    enwaiax/x-ui:alpha
