### ISSUE TITLE
可以去掉强制二级目录吗？根目录就可以了。

### ISSUE THREAD

**Issue by shhdz** [FranzKafkaYu/x-ui#324]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

可以去掉强制二级目录吗？根目录就可以了。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```最新

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```无

</details>

**Comment by FranzKafkaYu** [comment]
@shhdz 不可以
