### ISSUE TITLE
Device limit option is not working

### ISSUE THREAD

**Issue by Arad-Afzali** [FranzKafkaYu/x-ui#325]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

The device limit feature is not working well.
For example, I set the device limit on 1 but still I could connect with multiple devices.
Is there any solution?

### Version of x-ui

<details>

```console
$ x-ui version
0.3.4.1:20230305```



### x-ui log or xray log

<details>

```console
paste log here
```

</details>

**Comment by Arad-Afzali** [comment]
I tested more and the only effect is that connection is not stable.
for example telegram have a second of "connecting" moment or some Instagram videos cannot be loaded. but in general all devices can stay connected to the config.

**Comment by FranzKafkaYu** [comment]
As I said many times,device limit will drop connections while not reject connections，so ther would be constant “connecting”，it worked as design.
