### ISSUE TITLE
0.3.4.2 使用v2rayn 6.21扫码导入节点别名不显示

### ISSUE THREAD

**Issue by jelly0925** [FranzKafkaYu/x-ui#328]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

0.3.4.2 使用v2rayn 6.21扫码导入节点别名到Fingerprint参数位置
![image](https://user-images.githubusercontent.com/3022023/230776845-693db7cf-45e3-4a77-b093-a975bbdbf784.png)

### Version of x-ui

<details>

```console
$ x-ui version 0.3.4.2
# Paste output here
![image](https://user-images.githubusercontent.com/3022023/230776957-9b287b1a-bb35-4c0b-9415-41df84431faf.png)



</details>

### x-ui log or xray log

<details>
![image](https://user-images.githubusercontent.com/3022023/230777201-9478a77c-221a-488f-a53c-221e0b5ee20b.png)
</details>

**Comment by FranzKafkaYu** [comment]
@jelly0925  抱歉我个人没有使用v2rayN测试过，请问使用v2rayNG（内核需要1.8.0版本）扫码识别结果是正常的吗

**Comment by jelly0925** [comment]
> @jelly0925 抱歉我个人没有使用v2rayN测试过，请问使用v2rayNG（内核需要1.8.0版本）扫码识别结果是正常的吗

xray1.8内核，扫码导入连别名都没有呢。

**Comment by FranzKafkaYu** [comment]
@jelly0925 可以将分享链接脱敏后贴一下

**Comment by jelly0925** [comment]
> @jelly0925 可以将分享链接脱敏后贴一下

vless://297ef28e-2b1f-446a-e96d-4dbdacc020eb@b.abc.xyz:56221?type=tcp&security=reality&sni=www.microsoft.com&pbk=4comh-7Jm_wZXJQ5QiLSCbVGQIbMUzHUIBdb0aFtLzM&flow=xtls-rprx-vision&fp=chrome#🇺🇸 圣何塞CN2GIA|reality@xray.com

**Comment by FranzKafkaYu** [comment]
@jelly0925 尝试将分享链接中的图标/中文去掉

**Comment by jelly0925** [comment]
> @jelly0925 尝试将分享链接中的图标/中文去掉

试过的，还是一样的情况，现在配置都是手动配置的。

**Comment by FranzKafkaYu** [comment]
> 

刚测试了一下，v2rayNG可以正常识别

**Comment by jelly0925** [comment]
> > 
> 
> 刚测试了一下，v2rayNG可以正常识别

把国旗emoji和中文删除后可以扫码识别成功了。目前中文和国旗识别不了
![image](https://user-images.githubusercontent.com/3022023/230827955-27b3372f-06ed-43f6-ab0a-768c386d4037.png)

**Comment by FranzKafkaYu** [comment]
没有计划支持分享链接中包含中文/emoji等。
