### ISSUE TITLE
为什么我的x-ui 安装后过大概一小时，登录页面就404呢

### ISSUE THREAD

**Issue by Hikpy** [FranzKafkaYu/x-ui#330]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

为什么我的x-ui 安装后过大概一小时，登录页面就404呢,最新的版本

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>1

### x-ui log or xray log

<details>

```console
# paste log here
```1

</details>

**Comment by FranzKafkaYu** [comment]
WIKI/ ISSUE区都有说明，请自行查看。
