### ISSUE TITLE
Export users' data

### ISSUE THREAD

**Issue by om0504** [FranzKafkaYu/x-ui#331]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

請問一下
如何將x-ui內的所有用戶導出，方便匯入到另一個server的x-ui內?
謝謝。

### Version of x-ui

<details>

```console
$1
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
No

</details>

**Comment by FranzKafkaYu** [comment]
参考WIKI:
https://github.com/FranzKafkaYu/x-ui/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by om0504** [comment]
非常感謝，找到答案了，感恩~
