### ISSUE TITLE
发现面板url根路径设置的一个小问题

### ISSUE THREAD

**Issue by MINGAW** [FranzKafkaYu/x-ui#332]
面板url根路径无法设置成“/”，每次编辑完，会自动生成4位字符，并且立马自动保存和重启面板，不清楚是有意为之还是小问题，望解答，默认安装完成是“/”，只要有设置更改就会变成4位随机字符，老版的x-ui似乎没有这个问题，可以随意设置

**Comment by FranzKafkaYu** [comment]
@MINGAW 设计如此，避免默认根路径爆破。
