### ISSUE TITLE
xray 1.8.0 issue 

### ISSUE THREAD

**Issue by rouzbeh80** [FranzKafkaYu/x-ui#338]
After updating x-ui panel and xray to their latest versions, I get this error and xray fails to start. However, there is no such issue with v1.7.5. Since all my configs are trojan, I assume there must be a bug with trojan configurations on v1.8.0. 

<img width="270" alt="Screenshot 2023-04-10 at 21 16 12" src="https://user-images.githubusercontent.com/122862280/230960656-036c0b4c-493b-4ccd-8aba-d266e176e1c3.png">

**Comment by FranzKafkaYu** [comment]
@rouzbeh80 If you use Trojan, there's no need to use xray core 1.8.0, since xray core 1.8.0 doesn't support old XTLS flow any more while the default flow of Trojan is xtls-rprx-direct.
