### ISSUE TITLE
xui启动后无法访问，日志一直有warning

### ISSUE THREAD

**Issue by osongsongo** [FranzKafkaYu/x-ui#340]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

日志一直循环报错，面板无法连接，用的最新版本，系统为centos7，内核版本为：4.9.337 (KVM)

### Version of x-ui

<details>

```console
$ x-ui version
0.3.4.2:20230409
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
Apr 11 06:06:31 racknerd-56cfad x-ui[2101]: 2023/04/11 06:06:31 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
Apr 11 06:06:32 racknerd-56cfad x-ui[2101]: 2023/04/11 06:06:32 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
Apr 11 06:06:33 racknerd-56cfad x-ui[2101]: 2023/04/11 06:06:33 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
Apr 11 06:06:34 racknerd-56cfad x-ui[2101]: 2023/04/11 06:06:34 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
```

</details>

**Comment by FranzKafkaYu** [comment]
@osongsongo 这只是warning,不影响使用。无法访问的具体表现是什么，需要提供详细信息

**Comment by ussthp** [comment]
碰到和@osongsongo一样的warning，具体表现是面板打不开。我的系统是UBUNTU 20.04。

**Comment by ussthp** [comment]
我刚才重刷了一次系统从ubuntu换到CENTOS 8
Stream，然后全新安装x-ui以后发现问题依旧。我确认防火墙设置已经全部是放行的了。我用的是甲骨文ARM架构的VPS。
按照您的建议按了F12后请问在哪里看是否有报错信息？我暂时没看到有什么明显的信息提示，谢谢！
[image: image.png]


Yu FranzKafka ***@***.***> 于2023年4月13日周四 16:12写道：

**Comment by osongsongo** [comment]
@FranzKafkaYu 
![image](https://user-images.githubusercontent.com/78781938/231730115-f8b97417-a0ef-4356-86db-8851efc0a7d2.png)
网络显示503，不知道为什么

**Comment by V4444** [comment]
我也有，已经重装会旧版本了。另外，xray切换为1.4.2和1.4.3，就没问题。一旦超过这个版本号，我的vmess就无法连接

**Comment by FranzKafkaYu** [comment]
VMESS 已经启用AEAD，alterId需要保持为0，已经不再推荐使用旧版本。

**Comment by om0504** [comment]
我也碰到一樣的問題，webui 登入畫面有，登入後就加載不出來，換PC或browser都沒用

**Comment by FranzKafkaYu** [comment]
> 我也碰到一樣的問題，webui 登入畫面有，登入後就加載不出來，換PC或browser都沒用

浏览器设置语言为简体中文，繁体适配存在问题。

**Comment by om0504** [comment]
> > 我也碰到一樣的問題，webui 登入畫面有，登入後就加載不出來，換PC或browser都沒用
> 
> 浏览器设置语言为简体中文，繁体适配存在问题。

真的可以解決了，請問有辦法自己去調整解決這問題嗎? 比如說哪裡改成英文，就無關簡繁體了?

**Comment by FranzKafkaYu** [comment]
@om0504 下个版本我来解决适配问题。

**Comment by om0504** [comment]
> 

感恩大神~真心感謝!!

**Comment by FranzKafkaYu** [comment]
@shaw830 404 not found 的问题无论是ISSUE区还是WIKI还是Discuss区都有，是你自己不会用Github.

**Comment by FranzKafkaYu** [comment]
> > @shaw830 404 not found 的问题无论是ISSUE区还是WIKI还是Discuss区都有，是你自己不会用Github.
> 
> 我确实不太会用github，望大神指点。

Reference：https://github.com/FranzKafkaYu/x-ui/wiki/%E9%9D%A2%E6%9D%BF%E7%99%BB%E5%BD%95

**Comment by FranzKafkaYu** [comment]
close this issue,strictly it's not a real issue.
