### ISSUE TITLE
可否把源代码上传github，方便大家一起学习和一起完善？

### ISSUE THREAD

**Issue by simplerick-simplefun** [FranzKafkaYu/x-ui#341]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

可否把源代码上传github，方便大家一起学习和一起完善？

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by fireinrain** [comment]
大佬闭源了，哭死😭

**Comment by FranzKafkaYu** [comment]
@simplerick-simplefun 如果你有兴趣开发，请通过邮件联系我。

**Comment by simplerick-simplefun** [comment]
> @simplerick-simplefun 如果你有兴趣开发，请通过邮件联系我。

想学习一下。如果发现哪里有感兴趣的地方也许我也可以加一点代码。
请问您的代码有什么不能公开的原因吗？我看github上面做翻墙代理的代码repo都是公开的。

**Comment by FranzKafkaYu** [comment]
@simplerick-simplefun 因为不想成为为他人引流的工具。项目一开始是是为了向原仓库提交pr，原作者停止维护后就开始独立维护，这期间都是开源的。只是后来有人抄袭添加诱导链接，自此不再开源。

**Comment by simplerick-simplefun** [comment]
> @simplerick-simplefun 因为不想成为为他人引流的工具。项目一开始是是为了向原仓库提交pr，原作者停止维护后就开始独立维护，这期间都是开源的。只是后来有人抄袭添加诱导链接，自此不再开源。

可以理解，有利有弊。但我还是觉得开源的好处多一些。

翻墙社区这么多年，一个个项目薪火相传，靠的就是开源。从shadowsocks到v2ray到trojan到xray，如果没有开源，没有前人的基础，后面很多的开发会非常费时费力、缺乏思路，可能就不会出现。
另一方面，开源的项目，也方便大家帮助审查代码，查找bug，然后直接提供修改PR。
您说的本项目和原项目之间，不是也属于这种关系吗？

至于那些夹带私货的项目，无论是修改别人的项目，还是自己开发的，其实也都无法得到大众的认可。修改别人项目的没有开发能力，star也不会多，commit也没有，大家自然都会去找开发最好的项目分支使用。携带私货或恶意代码的项目，开源便会被人发现，也活不长久。从这方面看，开源社区这种系统本身就是打击不良行为的好办法。

**Comment by gallexy** [comment]
代码维护确实耗费精力，不过可以量力而行，更新慢一些大家也都能理解。
我以为不不妨碍开源的

**Comment by mading0817** [comment]
> @simplerick-simplefun 我同样认可你的说法，但我无意于维护这样一个开源项目。因为我知道维护开源项目需要花费很多的时间，无论是解决ISSUE，审核PR，开发新Feature都需要很多精力，原作者关闭ISSUE区应该也有部分原因在这里。在开源的期间内，抄袭的有不少，提新需求的也有很多，却无一人提交pr参与维护，所以我选择闭源后依据自己的喜好开发，按照自己的节奏添加自己喜欢的功能。不论怎样，如果你有兴趣学习/开发，或者作为主力维护者，都可以邮件联系我，并提供相应的能力证明，我们可以考虑重新开源，共同维护。

大佬, 难道这个https://github.com/vaxilu/x-ui是假的吗? 这个star还是咱们的一倍呢啊!我就说https://github.com/vaxilu/x-ui这个我搞半天也搞不定vless, 换了现在这个项目一下就搞定了.
