### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY如何与nginx 443共用端口

### ISSUE THREAD

**Issue by bulesky89857** [FranzKafkaYu/x-ui#345]
reality 协议没有path 设置，如何与nginx 443共用端口？

**Comment by spysir** [comment]
> reality 协议没有path 设置，如何与nginx 443共用端口？

确实，当端口为443时，Xray无法运行，应该是跟NGINX的443端口冲突了

**Comment by i72896** [comment]
nginx sni四层转发
