### ISSUE TITLE
Add vless Reality support for vless h2 and Trojan.

### ISSUE THREAD

**Issue by xxSaeidxx** [FranzKafkaYu/x-ui#346]
Hi @FranzKafkaYu 

The REALITY protocol is now support tcp, grpc and h2 on vless. But in the x-ui panel we can not create a vless config with the h2. Also I think creating Reality config is possible for trojan that not supported in panel till now.

Thanks.

**Comment by FranzKafkaYu** [comment]
@xxSaeidxx TROJAN REALITY is not supported by xray core officially, so I won't add this to TROJAN,but I will add H2 transport in next version.

**Comment by xxSaeidxx** [comment]
> @xxSaeidxx TROJAN REALITY is not supported by xray core officially, so I won't add this to TROJAN,but I will add H2 transport in next version.

Thank you.

**Comment by xxSaeidxx** [comment]
Dear @FranzKafkaYu 

I'm writing to you regarding of Spiderx in Reality. 
I don't see this section in x-ui panel. 
Can you provide this in the next update?

Thanks.

**Comment by FranzKafkaYu** [comment]
@xxSaeidxx Spiderx needs to be set up in Client,and it's a highly customized setting,I think there is no need to do this

**Comment by laaArmy** [comment]
> @xxSaeidxx TROJAN REALITY 不被 xray core 官方支持，所以我不会将其添加到 TROJAN 中，但我会在下一个版本中添加 H2 传输。

大佬，0.3.4.4是不是没加H2传输

**Comment by MrSaeid007** [comment]
> > @xxSaeidxx TROJAN REALITY 不被 xray core 官方支持，所以我不会将其添加到 TROJAN 中，但我会在下一个版本中添加 H2 传输。
> 
> 大佬，0.3.4.4是不是没加H2传输

I tested H2 for the Transport and it's wasn't good at speed. TCP gives more speed and it's stable too.
I also asked xray-reality developer to add a Quic protocol for Transport in vless Reality.
They said we will add it in the future.
https://github.com/XTLS/Xray-core/issues/2451#issuecomment-1708172622
