### ISSUE TITLE
[BUG]我尝试了如果新建的VLESS走TCP协议但是带伪装会出错

### ISSUE THREAD

**Issue by chaoscaros** [FranzKafkaYu/x-ui#348]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

新建一个VLESS，然后协议选择tcp，开启http伪装和reality后，创建完用户，复制链接到v2客户端，引入后无法连接上，查看设置里面的伪装类型为空,去掉HTTP伪装后倒是可以连上了，但是手动在客户端把伪装类型设置为http是连接不上的
相当于只能创建没有伪装的vless，带伪装的协议无法进行连接

### Version of x-ui

1.8.0

### x-ui log or xray log

无

**Comment by FranzKafkaYu** [comment]
@chaoscaros REALITY不支持http伪装。

**Comment by chaoscaros** [comment]
好的，主要是没有提示的情况，有时候按照平常习惯设置伪装，但是排查又排查不到问题就，所以感觉有必要问一下看看到底是什么情况
