### ISSUE TITLE
未检测到系统版本，请联系脚本作者！

### ISSUE THREAD

**Issue by vientito** [FranzKafkaYu/x-ui#358]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

My arch shows aarch64 which I think is same as arm64 but when I tried to follow installation procedure that message popped up

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by vientito** [comment]
Rewrite issue and add Debian in file to permit installation

**Comment by FranzKafkaYu** [comment]
@vientito please use `uname -a` command to check which arch you are using,and provide me this info,I will check it later.

**Comment by vientito** [comment]
No worry I bypass the check by editing my issue file and add Debian as keyword for my system. Installed perfectly here
