### ISSUE TITLE
Only 10 clients get added

### ISSUE THREAD

**Issue by Stevemoretz** [FranzKafkaYu/x-ui#360]
After adding 10 clients when I press add client button, nothing happens that sounds like a bug.

**Comment by FranzKafkaYu** [comment]
@Stevemoretz it's not a bug. it's expected behavior.

**Comment by Stevemoretz** [comment]
> @Stevemoretz it's not a bug. it's expected behavior.

I'm sorry I wasn't aware of that, what's the logic behind it? Is there any way to raise it to a higher number?

**Comment by FranzKafkaYu** [comment]
> > @Stevemoretz it's not a bug. it's expected behavior.
> 
> I'm sorry I wasn't aware of that, what's the logic behind it? Is there any way to raise it to a higher number?

because if I don't make restriction this tool may cause problem to me. It's designed for personal use and 10 users is enough.

**Comment by Stevemoretz** [comment]
> > > @Stevemoretz it's not a bug. it's expected behavior.
> > 
> > 
> > I'm sorry I wasn't aware of that, what's the logic behind it? Is there any way to raise it to a higher number?
> > I make restriction because this tool may cause problem to me. It's designed for personal use and 10 users is enough.

Thank you so much for explaining could you please point me to the file where that number 10 has been hard-coded in it?
That can be really helpful
