### ISSUE TITLE
Login panel blank

### ISSUE THREAD

**Issue by vientito** [FranzKafkaYu/x-ui#362]
My panel login page goes blank on my Samsung Note20 SM-N9810 Android ver. 13. I try it on two completely different browsers but still appear blank. The same login site appears elsewhere on one of my other tablets and on a PC Debian platform.

**Comment by adian2020** [comment]
我也一样，安卓谷歌浏览器和pc谷歌浏览器面板登录页面变成空白，可以用edge浏览器来打开面板，不知道为什么会出现这个错误

**Comment by FranzKafkaYu** [comment]
> My panel login page goes blank on my Samsung Note20 SM-N9810 Android ver. 13. I try it on two completely different browsers but still appear blank. The same login site appears elsewhere on one of my other tablets and on a PC Debian platform.

please check browser language setting options,if you Chinese Version please set the language to be Simplified Chinese,if not please set the language to be English.
