### ISSUE TITLE
panel API

### ISSUE THREAD

**Issue by mohamadaz** [FranzKafkaYu/x-ui#363]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

how can i use inbounds information in other place?
pls add API

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by pouyababaie** [comment]
if you are wiling to use it in clients side , you should consider this page
[for windows](https://github.com/2dust/v2rayN/releases/tag/6.23)
[for android] (https://github.com/2dust/v2flyNG/releases/tag/1.7.18)
and for iOS search for 
- "NapsternetV" 
- "FairVpn"
I hope it helped
