### ISSUE TITLE
用其它协议时xray就运行错误,用reality就没有问题

### ISSUE THREAD

**Issue by lgh200** [FranzKafkaYu/x-ui#364]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![2](https://user-images.githubusercontent.com/47652124/233893694-0d1c177d-4b7a-4a66-8d8b-9661f8bed937.png)
![1](https://user-images.githubusercontent.com/47652124/233893696-3888cb6b-c936-4b46-9cac-798eb28fbfe2.png)
只要删除，这个节点，xray立马就正常了

### Version of x-ui

1.8.1

### x-ui log or xray log

Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.

2023/04/23 23:29:41 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY

**Comment by FranzKafkaYu** [comment]
@lgh200 xray core 1.8.0及以上已经不再支持旧的xtls流控，如需使用旧的xlt流控（xtls-rprx-direct/xtls-rprx-origin）请将xray core版本切换至1.7.5及以下。需要注意的是，旧的xlts流控已经不再安全，不推荐使用。

**Comment by lgh200** [comment]
好的，谢谢
