### ISSUE TITLE
新版本导出链接会和邮箱也一起显示在节点后面。老版本不会

### ISSUE THREAD

**Issue by hubin92** [FranzKafkaYu/x-ui#365]
![image](https://user-images.githubusercontent.com/68316494/234181904-da4be167-6e8c-4a55-9e86-c9a9dd17011d.png)

**Comment by FranzKafkaYu** [comment]
@hubin92 设计如此，方便从链接中区分用户。

**Comment by hubin92** [comment]
感觉还是老版本的舒服没有显示邮箱
