### ISSUE TITLE
获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release

### ISSUE THREAD

**Issue by xuelide** [FranzKafkaYu/x-ui#366]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://user-images.githubusercontent.com/8680332/234350447-0fe66b15-dffe-4c59-8927-3b2c3b55f064.png)
全新用脚本安装的0.3.4.2:20230409，点击切换内核或者内核版本就提示错误。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```
0.3.4.2:20230409
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
Apr 26 00:53:40 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:53:40 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:53:46 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:53:46 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:55:42 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:55:42 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:56:59 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:56:59 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:57:03 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:57:03 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:57:07 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:57:07 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:57:10 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:57:10 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 00:58:05 instance-20220907-1458 x-ui[1183878]: 2023/04/26 00:58:05 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 01:00:07 instance-20220907-1458 x-ui[1183878]: 2023/04/26 01:00:07 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 01:01:00 instance-20220907-1458 x-ui[1183878]: 2023/04/26 01:01:00 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 01:02:47 instance-20220907-1458 x-ui[1183878]: 2023/04/26 01:02:47 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 01:03:35 instance-20220907-1458 x-ui[1183878]: 2023/04/26 01:03:35 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 01:03:54 instance-20220907-1458 x-ui[1183878]: 2023/04/26 01:03:54 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
Apr 26 01:03:55 instance-20220907-1458 x-ui[1183878]: 2023/04/26 01:03:55 WARNING - 获取版本失败:  json: cannot unmarshal object into Go value of type []service.Release
</details>

**Comment by fireinrain** [comment]
看看js接口请求的数据 和 返回失败的响应

**Comment by dragonwebs** [comment]
centos 7存在这个问题，centos 8没有。
