### ISSUE TITLE
Shadow socks security method

### ISSUE THREAD

**Issue by Saber88607** [FranzKafkaYu/x-ui#368]
why your panel  doesnt have all security method for shadowsocks?
<img width="246" alt="Screenshot 1402-02-06 at 4 56 43 PM" src="https://user-images.githubusercontent.com/131883765/234590586-777df245-260d-4fbf-b412-e59c2a19da25.png">

**Comment by FranzKafkaYu** [comment]
> why your panel doesnt have all security method for shadowsocks? <img alt="Screenshot 1402-02-06 at 4 56 43 PM" width="246" src="https://user-images.githubusercontent.com/131883765/234590586-777df245-260d-4fbf-b412-e59c2a19da25.png">

because some methods are not safe and there is no need to use them.
