### ISSUE TITLE
IOS小火箭无法识别这个版本的二维码？

### ISSUE THREAD

**Issue by CyberXfuck** [FranzKafkaYu/x-ui#373]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

更新了版本后功能更强大了， 但是小火箭识别不了了这个版本产生的二维码， 有人知道是什么原因吗？

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by roger2255** [comment]
小火箭还不支持reality 可以支持1. 75版本的协议

**Comment by CyberXfuck** [comment]
我用的是1.75的内核，搭建了一个Trojan。面板的版本是当前最新的。
