### ISSUE TITLE
No flow xtls rprx vision in panel.

### ISSUE THREAD

**Issue by mdsdtech** [FranzKafkaYu/x-ui#375]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I tried to create the VLess XTLS; xtls-rprx-vision but in the flow section, xtls-rprx-vision didnt show. 
Xray Core: v1.8.1

![Screenshot from 2023-05-02 22-24-01](https://user-images.githubusercontent.com/70020155/235698227-6ff5be56-9b72-4508-b7a1-750168253c72.png)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by xiyuvi** [comment]
> 

谢谢，添加后就有选项了
