### ISSUE TITLE
无法登入面板

### ISSUE THREAD

**Issue by Cysub** [FranzKafkaYu/x-ui#382]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

无法登入面板，浏览器显示打不开或无法处理请求
使用Vultr的CentOS，安装成功且显示运行正常，但无法在浏览器打开，确认地址设置无误，重新设置防火墙确认没问题，换了其他设备尝试，检查了端口、路径，重置系统重新尝试，依然无法解决。
![image](https://github.com/FranzKafkaYu/x-ui/assets/108491138/fdc10ed5-c8f9-4ca9-9dbe-b77755607e35)
![image](https://github.com/FranzKafkaYu/x-ui/assets/108491138/b294c8d4-c941-4615-8283-e64b79f3cf2e)
![IMG_0227](https://github.com/FranzKafkaYu/x-ui/assets/108491138/eb3f3126-19b5-4da4-bf29-a42025101aba)
![image](https://github.com/FranzKafkaYu/x-ui/assets/108491138/2f7b68c6-ed0e-41e6-8598-be9751221ebb)

### Version of x-ui

<details>

```console
$ x-ui version
#  0.3.4.2:20230409
```

</details>

### x-ui log or xray log

<details>

```console
# 不知道如何获取日志
```

</details>

**Comment by FranzKafkaYu** [comment]
@Cysub  使用`x-ui log`查看日志;确认端口开放可以使用ping.pe进行检查；使用其他浏览器进行尝试

**Comment by PingZi-Wing** [comment]
可能浏览器端口有限制，可以换一个低于一万的监听端口试试。

**Comment by Cysub** [comment]
> @Cysub 使用`x-ui log`查看日志;确认端口开放可以使用ping.pe进行检查；使用其他浏览器进行尝试

![image](https://github.com/FranzKafkaYu/x-ui/assets/108491138/1dc17820-d7fd-4d3b-8664-d2c59a924c7e)
![image](https://github.com/FranzKafkaYu/x-ui/assets/108491138/336ac9fd-992f-47bd-9d70-78b803b79ae9)
这代表什么？

**Comment by Cysub** [comment]
> 可能浏览器端口有限制，可以换一个低于一万的监听端口试试。

用的是低于一万，并且试了iPad Safari和Windows的Edge都不行

**Comment by FranzKafkaYu** [comment]
> > @Cysub 使用`x-ui log`查看日志;确认端口开放可以使用ping.pe进行检查；使用其他浏览器进行尝试
> 
> ![image](https://user-images.githubusercontent.com/108491138/237906736-1dc17820-d7fd-4d3b-8664-d2c59a924c7e.png) ![image](https://user-images.githubusercontent.com/108491138/237906797-336ac9fd-992f-47bd-9d70-78b803b79ae9.png) 这代表什么？

这代表8619端口未开放/或没有服务监听该端口，请再次检查你的防火墙设置。除了Linux系统自带的防火墙，也请检查VPS服务提供商控制面板内的防火墙。

**Comment by Cysub** [comment]
> > > @Cysub 使用查看日志;确认端口开放可以使用ping.pe进行检查；使用其他浏览器进行尝试`x-ui log`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/108491138/237906736-1dc17820-d7fd-4d3b-8664-d2c59a924c7e.png) ![image](https://user-images.githubusercontent.com/108491138/237906797-336ac9fd-992f-47bd-9d70-78b803b79ae9.png) 这代表什么？
> 
> 这代表8619端口未开放/或没有服务监听该端口，请再次检查你的防火墙设置。除了Linux系统自带的防火墙，也请检查VPS服务提供商控制面板内的防火墙。

谢谢，解决问题了

**Comment by JssDream** [comment]
@FranzKafkaYu 你好，能帮我看看这个是什么问题嘛？
服务启动正常，curl 127 没问题，就是外部ip+端口不能打开，测试端口是开放的，日志也没看出问题
![image](https://github.com/FranzKafkaYu/x-ui/assets/24471999/299f8da7-7b11-4c76-bf05-13615f529ca6)
![image](https://github.com/FranzKafkaYu/x-ui/assets/24471999/ab5ae87d-7d1b-4779-8501-5013c22f44f4)
![image](https://github.com/FranzKafkaYu/x-ui/assets/24471999/8913c6e0-409a-4e33-a287-4eb1d587484d)
![image](https://github.com/FranzKafkaYu/x-ui/assets/24471999/da075045-aab1-40f3-9ad2-81f075927a91)
![image](https://github.com/FranzKafkaYu/x-ui/assets/24471999/97083de8-1d07-4b08-8c33-c67444eb26e1)
