### ISSUE TITLE
Panel certificate key file path 

### ISSUE THREAD

**Issue by DoodleKhan** [FranzKafkaYu/x-ui#383]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I have installed X-UI with the Docker image of enwaiax/x-ui:alpha-zh
I am trying to give the certificate file path to the panel but no file path works!
error pops saying similar to this message . just link will change in the message:
 "  cert file </root/x-ui/cert/cert.crt> or key file </root/x-ui/cert/private.key> invalid: open /root/x-ui/cert/cert.crt: no such file or directory"

Actual location of private.key and cert.crt is as bellow:
/root/x-ui/cert/private.key
/root/x-ui/cert/cert.crt

I have tested all following:
cert/cert.crt
/cert/cert.crt
x-ui/cert/cert.crt.        and all combinations
what link shall i provide for panel? and what link for connections?? can i replace the files with cloudflare issued certificates ?
if u consider * as cert.crt or Private.key following links are tested and not working . e

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
You need  map cert files in docker with the real path and ensure you have the permission to read it.So I suggest you install x-ui directly to check whether it can work,then you can switch to docker.
