### ISSUE TITLE
 flow选项里没有xtls-rprx-vision

### ISSUE THREAD

**Issue by xiyuvi** [FranzKafkaYu/x-ui#384]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/FranzKafkaYu/x-ui/assets/38217058/ab8e7f04-3f59-4072-8bd7-9fcb7848be0b)
您好，我想使用wiki里的Vless+reality+tcp+xtls-rprx-vison，但是我的选项里没有xtls-rprx-vision，请问是额外要设置什么吗

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
开启reality且需要添加用户，flow选项在用户设置内。
