### ISSUE TITLE
使用reality协议报错

### ISSUE THREAD

**Issue by xiyuvi** [FranzKafkaYu/x-ui#385]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

我按照wiki的指引设置Vless+reality+tcp+xtls-rprx-vison后，客户端连接无法上网，报错：
```
2023/05/12 15:24:25 [Warning] [2194323916] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF] > common/retry: all retry attempts failed
2023/05/12 15:24:25 [Warning] [2194323916] proxy/http: failed to read response from 96.43.84.130:8898 > io: read/write on closed pipe
2023/05/12 15:24:26 [Warning] [3254285183] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF] > common/retry: all retry attempts failed
```
我的服务器配置和客户端配置如下图所示
![image](https://github.com/FranzKafkaYu/x-ui/assets/38217058/86bf2f30-02d7-417e-8cf0-e73a0cdabd9e)
![image](https://github.com/FranzKafkaYu/x-ui/assets/38217058/82234daa-821d-482d-bd9f-44199cf53d70)

### Version of x-ui

使用脚本安装的最新版

### x-ui log or xray log

x-ui日志
```
May 12 02:18:39 xiyu x-ui[1307]: 2023/05/12 02:18:39 INFO - text login success,Ip Address:12.12.12.12
May 12 02:18:39 xiyu x-ui[1307]: 2023/05/12 02:18:39 INFO - user 1 login success
May 12 02:18:40 xiyu x-ui[1307]: 2023/05/12 02:18:40 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:41 xiyu x-ui[1307]: 2023/05/12 02:18:41 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:42 xiyu x-ui[1307]: 2023/05/12 02:18:42 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:43 xiyu x-ui[1307]: 2023/05/12 02:18:43 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:44 xiyu x-ui[1307]: 2023/05/12 02:18:44 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:45 xiyu x-ui[1307]: 2023/05/12 02:18:45 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:46 xiyu x-ui[1307]: 2023/05/12 02:18:46 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 12 02:18:49 xiyu x-ui[1307]: 2023/05/12 02:18:49 WARNING - stop server err: multierr: close tcp [::]:8898: use of closed network connection |
May 12 02:18:49 xiyu x-ui[1307]: 2023/05/12 02:18:49 INFO - web server run http on [::]:8898
May 12 02:18:49 xiyu x-ui[1307]: 2023/05/12 02:18:49 INFO - Wait 2 seconds for telegram bot ready
May 12 02:30:19 xiyu x-ui[1307]: 2023/05/12 02:30:19 INFO - We got 1 members in client
May 12 02:44:29 xiyu x-ui[1307]: 2023/05/12 02:44:29 INFO - We got 1 members in client
May 12 02:44:29 xiyu x-ui[1307]: 2023/05/12 02:44:29 INFO - We got 1 members in client
May 12 03:19:39 xiyu x-ui[1307]: 2023/05/12 03:19:39 INFO - We got 1 members in client
May 12 03:19:39 xiyu x-ui[1307]: 2023/05/12 03:19:39 INFO - We got 1 members in client
May 12 03:19:39 xiyu x-ui[1307]: 2023/05/12 03:19:39 INFO - We got 1 members in client

```

**Comment by xiyuvi** [comment]
我在使用中没有安装ssl证书，请问一下reality协议需要申请证书吗

**Comment by FranzKafkaYu** [comment]
@xiyuvi 请确认客户端xray 版本，以及地址（address）栏的信息，这个`12.12.12.12`是脱敏的数据么

**Comment by xiyuvi** [comment]
> @xiyuvi 请确认客户端xray 版本，以及地址（address）栏的信息，这个`12.12.12.12`是脱敏的数据么

客户端xray版本是v1.7.5 已是最新版本。address栏填写的是服务器的ip，12.12.12.12是模拟信息，实际上填写是正确的。我使用x-ui的kcp协议已经连接成功了，就是reality协议无法上网，我可以将服务器连接信息发送给您吗

**Comment by FranzKafkaYu** [comment]
> > @xiyuvi 请确认客户端xray 版本，以及地址（address）栏的信息，这个`12.12.12.12`是脱敏的数据么
> 
> 客户端xray版本是v1.7.5 已是最新版本。address栏填写的是服务器的ip，12.12.12.12是模拟信息，实际上填写是正确的。我使用x-ui的kcp协议已经连接成功了，就是reality协议无法上网，我可以将服务器连接信息发送给您吗

使用reality需要xray core 1.8.0版本，1.7.5只支持xtls-rprx-vision

**Comment by FranzKafkaYu** [comment]
由于上游 xray core没有正式release REALITY，所以很多客户端也没有正式的版本支持（v2rayN/V2rayNG etc）,你可以去客户端官方repo下载pre-release版本，在v2rayN中也可以开启pre-release更新。

**Comment by xiyuvi** [comment]
> 由于上游 xray core没有正式release REALITY，所以很多客户端也没有正式的版本支持（v2rayN/V2rayNG etc）,你可以去客户端官方repo下载pre-release版本，在v2rayN中也可以开启pre-release更新。

感谢你的提醒，我已经开启了v2rayN的pre-release更新，更新到1.8.1后 kcp协议正常，reality协议还是报错
