### ISSUE TITLE
nginx做前置连接成功一下就断开！

### ISSUE THREAD

**Issue by sjkhsl** [FranzKafkaYu/x-ui#386]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

nginx做前置，连接能成功一下，刚连接成功时可以连接tg，测试连接成功，有暂时时间，然后立马就会断开，在点击测试连接会显示超时，之前的版本就没有这个问题！还有新版本配置名称和ws的路径会自动添加邮箱地址！

### Version of x-ui

<details>

```console
$ x-ui version   0.3.4.2:20230409
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by sjkhsl** [comment]
0.3.3.18:20221206这个版本的目前运行正常，前置nginx也正常！新版本卸载换vaxilu大佬原版也正常！

**Comment by FranzKafkaYu** [comment]
@sjkhsl 你需要检查的是xray core版本，而非x-ui版本，请确保xray版本一致情况下，对比两个x-ui版本生成的配置文件差异。

**Comment by sjkhsl** [comment]
> @sjkhsl 你需要检查的是xray core版本，而非x-ui版本，请确保xray版本一致情况下，对比两个x-ui版本生成的配置文件差异。

控制面板中xray的版本吗？目前旧版本正常的1.8.0、1.7.5、1.7.1都试过，新版本就是连接成功后瞬间就超时！

**Comment by FranzKafkaYu** [comment]
@sjkhsl 是的，需确认控制面板中xray的版本，请保持xray版本一致，协议配置一致，分别使用两个x-ui版本，对比生成的配置文件差异。

**Comment by sjkhsl** [comment]
> @sjkhsl 是的，需确认控制面板中xray的版本，请保持xray版本一致，协议配置一致，分别使用两个x-ui版本，对比生成的配置文件差异。

0.3.4.1:20230305版本1.7.5正常，0.3.4.2:20230409版本就不行，同样的nginx和同样的vless配置，vless都是监听127.0.0.1，传输协议ws！控制面板中未配置tls，证书在nginx配置中！

**Comment by sjkhsl** [comment]
昨天新配置了两台，都是一样的问题，其中一台卸载后，使用vaxilu大佬原版就可以正常连接，同样的vless配置，nginx配置和证书都没有动！

**Comment by FranzKafkaYu** [comment]
@sjkhsl 请自行对比两个x-ui版本生成的config.json配置文件差异，文件位于/usr/local/x-ui/bin/ config.json

**Comment by sjkhsl** [comment]
> @sjkhsl 请自行对比两个x-ui版本生成的config.json配置文件差异，文件位于/usr/local/x-ui/bin/ config.json

新版本比旧版本在配置文件中多了这些！其他除了ID外都一样！

  "policy": {
```
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
```

**Comment by FranzKafkaYu** [comment]
@sjkhsl 这部分也是官方配置内容，可在配置模板内修改。

**Comment by sjkhsl** [comment]
> @sjkhsl 这部分也是官方配置内容，可在配置模板内修改。

果然，删掉后重启就好了！

**Comment by sjkhsl** [comment]
那会儿好了，之后又连接时又不行了，查了一下，最近tls阻断很严重？然后去掉了tls，用vmess可以正常使用了！
