### ISSUE TITLE
grpc没有acceptProxyProtocol设置

### ISSUE THREAD

**Issue by PatsyLoughary** [FranzKafkaYu/x-ui#387]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

grpc缺少acceptProxyProtocol设置，例如下面的配置用不了
https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-uTLS-REALITY/config_server_shared_port.json

### Version of x-ui

<details>

```console
$ x-ui version
0.3.4.2:20230409
```
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> grpc缺少acceptProxyProtocol设置，例如下面的配置用不了 https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-uTLS-REALITY/config_server_shared_port.json
> 
> ### Version of x-ui
> ### x-ui log or xray log

```
 "sockopt": {
            "acceptProxyProtocol": true
       }  
```  
目前面板不支持`sockopt`配置,另外这份配置文件中sockopt配置应该是不需要的（透明代理相关）。
