### ISSUE TITLE
telegram通知配置错误导致面板启动失败

### ISSUE THREAD

**Issue by heqirong** [FranzKafkaYu/x-ui#39]
telegram通知配置正常使用的情况下，修改了错误的Token和ChatId后，即使“启用电报机器人”选项是关闭情况下，面板也无法启动

Jun 20 22:04:49 xui.localdomain systemd[1]: Started x-ui Service.
Jun 20 22:04:49 xui.localdomain x-ui[489]: 2022/06/20 22:04:49 x-ui 0.3.2.11
Jun 20 22:04:50 xui.localdomain x-ui[489]: 2022/06/20 22:04:50 INFO - web server run https on [::]:443
Jun 20 22:04:50 xui.localdomain x-ui[489]: 2022/06/20 22:04:50 INFO - telegram service ready to run
Jun 20 22:04:50 xui.localdomain x-ui[489]: 2022/06/20 22:04:50 INFO - TelegramService GetTgBotToken:***************************************
Jun 20 22:04:51 xui.localdomain x-ui[489]: 2022/06/20 22:04:51 INFO - telegram service start run failed,NewBotAPI fail:Unauthorized,tgBottoken:*********************************
Jun 20 22:04:51 xui.localdomain x-ui[489]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 20 22:04:51 xui.localdomain x-ui[489]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9f855c]
Jun 20 22:04:51 xui.localdomain x-ui[489]: goroutine 59 [running]:
Jun 20 22:04:51 xui.localdomain x-ui[489]: x-ui/web/service.(*TelegramService).StartRun(0xc0002e6710)
Jun 20 22:04:51 xui.localdomain x-ui[489]:         /home/runner/work/x-ui/x-ui/web/service/telegram.go:109 +0x2bc
Jun 20 22:04:51 xui.localdomain x-ui[489]: x-ui/web.(*Server).Start.func2()
Jun 20 22:04:51 xui.localdomain x-ui[489]:         /home/runner/work/x-ui/x-ui/web/web.go:393 +0x25
Jun 20 22:04:51 xui.localdomain x-ui[489]: created by x-ui/web.(*Server).Start
Jun 20 22:04:51 xui.localdomain x-ui[489]:         /home/runner/work/x-ui/x-ui/web/web.go:392 +0x915
Jun 20 22:04:51 xui.localdomain systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 20 22:04:51 xui.localdomain systemd[1]: x-ui.service: Failed with result 'exit-code'.

**Comment by FranzKafkaYu** [comment]
fixed
