### ISSUE TITLE
当通过x-ui面板申请第二个证书时，会删除上一个证书

### ISSUE THREAD

**Issue by TaoRone** [FranzKafkaYu/x-ui#392]
当通过x-ui面板申请第二个证书时，会直接在/root/cert/目录和  /root/.acme.sh/目录 删除上一个证书
也就是x-ui的面板仅能支持一个证书的申请
在特定时候会需要多个证书来支持作业，请求修改这个问题

**Comment by chentanwan** [comment]
请问一下，我误操作导致重复申请覆盖掉了证书，再申请提示当前环境已有证书，怎么解决

**Comment by FranzKafkaYu** [comment]
@chentanwan rm -rf   ~/.acme.sh

**Comment by FranzKafkaYu** [comment]
@TaoRone 已修复，可更新后进行测试。
