### ISSUE TITLE
按照教程配置了面板但遇到问题，求帮忙解决

### ISSUE THREAD

**Issue by zhuboqi** [FranzKafkaYu/x-ui#398]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

AWS上的Ubuntu  按照教程安装面板、申请证书、配置。客户端是V2RAYNG

但是按图配置Vless+reality+tcp+xtls-rprx-vison  一直不行，或者说是VLESS一直不行。看日志显示是证书有问题？但vmess+ws+tls 就可以，套CF也可以。这是为什么？

另请问如果想套AWS的CDN要怎么设置，我自己试了下没成功，能否出个教程？

### Version of x-ui

面板里的XRAY相关设置

{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

### x-ui log or xray log

查看X-UI日志里边 很多相同条目中的一条

2023/05/23 09:49:42 http: TLS handshake error from 1*********0:23196: remote error: tls: unknown certificate

**Comment by FranzKafkaYu** [comment]
@zhuboqi 请先行查看客户端日志。
