### ISSUE TITLE
从原版升级到该版本在vless模式下reality使用会报错，卸载后重新安装会解决，但是会导致节点失效

### ISSUE THREAD

**Issue by DR-lin-eng** [FranzKafkaYu/x-ui#399]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

从原版升级到该版本在vless模式下reality使用会报错，卸载后重新安装会解决，但是会导致节点失效

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by DR-lin-eng** [comment]
我后面多次重试了一下没有出现这个问题了，无法复现，抱歉。我之前看的估计是配置文件的冲突导致的。可能因为什么玄学问题。

**Comment by DR-lin-eng** [comment]
找到了，链接过程中一直报错： WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap

**Comment by FranzKafkaYu** [comment]
@DR-lin-eng 这只是Warning,不会有任何影响
