### ISSUE TITLE
关于在OpenVZ的NAT服务器无法正常启动的问题

### ISSUE THREAD

**Issue by Clown1i** [FranzKafkaYu/x-ui#40]
在woiden提供的免费NAT服务器上安装之后x-ui和xray都无法启动，vaxilu的可以正常使用。之前在hax的kvm机子上试过能正常启动

**Comment by FranzKafkaYu** [comment]
> 在woiden提供的免费NAT服务器上安装之后x-ui和xray都无法启动，vaxilu的可以正常使用。之前在hax的kvm机子上试过能正常启动

还请提供一下日志，输入x-ui进入脚本控制页面查看日志，提供一下错误截图

**Comment by Clown1i** [comment]
> > 在woiden NAT服务器上安装之后x-和xray都无法启动，vaxilu的正常使用。
> 
> 还请提供一下日志，输入x-ui进入脚本控制页面查看日志，提供错误截图

![image](https://user-images.githubusercontent.com/102837000/176329151-900c42f7-8324-4279-baf9-bf59ef46163d.png)

无法启动服务

**Comment by FranzKafkaYu** [comment]
> > > 在woiden NAT服务器上安装之后x-和xray都无法启动，vaxilu的正常使用。
> > 
> > 
> > 还请提供一下日志，输入x-ui进入脚本控制页面查看日志，提供错误截图
> 
> ![image](https://user-images.githubusercontent.com/102837000/176329151-900c42f7-8324-4279-baf9-bf59ef46163d.png)
> 
> 成功在网页登录的日志应该是原作的版本留下的

看错误应该是系统版本比较老旧，Readme中有介绍解决该问题的办法，可以尝试安装如下版本:
bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh) 0.3.3.9

**Comment by Clown1i** [comment]
> > > > 在woiden NAT服务器上安装之后x-和xray都无法启动，vaxilu的正常使用。
> > > 
> > > 
> > > 还请提供一下日志，输入x-ui进入脚本控制页面查看日志，提供错误截图
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/102837000/176329151-900c42f7-8324-4279-baf9-bf59ef46163d.png)
> > 成功在网页登录的日志应该是原作的版本留下的日志
> 
> 看错应该是系统比较旧，Readme里面有介绍解决该问题的版本的办法，可以尝试老安装如下版本： bash <(curl -Ls [https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/](https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh)安装.sh) [0.3.3.9](https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh)



> > > > 在woiden NAT服务器上安装之后x-和xray都无法启动，vaxilu的正常使用。
> > > 
> > > 
> > > 还请提供一下日志，输入x-ui进入脚本控制页面查看日志，提供错误截图
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/102837000/176329151-900c42f7-8324-4279-baf9-bf59ef46163d.png)
> > 成功在网页登录的日志应该是原作的版本留下的日志
> 
> 看错应该是比较旧的，Readme里面有介绍解决该问题的版本的办法，可以尝试老安装如下版本： bash <(curl -Ls [https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master /](https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh)安装.sh) [0.3.3.9](https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh)

好的。系统版本为 Centos7.9

**Comment by Clown1i** [comment]
换了系统好了
