### ISSUE TITLE
my x-ui  xray dose not working

### ISSUE THREAD

**Issue by sifz508** [FranzKafkaYu/x-ui#400]
how to fix this error ? get xray version failed: Get "https://api.github.com/repos/XTLS/Xray-core/releases": dial tcp: lookup api.github.com on 8.8.4.4:53: read udp 172.16.0.2:50291->8.8.4.4:53: i/o timeout

**Comment by FranzKafkaYu** [comment]
@sifz508 change your server DNS resolver to 8.8.8.8 or    1.1.1.1 to try
