### ISSUE TITLE
显示登陆成功，然后进入空白页面

### ISSUE THREAD

**Issue by yiyangitex** [FranzKafkaYu/x-ui#404]
显示登陆成功，然后进入空白页面

**Comment by FranzKafkaYu** [comment]
@yiyangitex 请检查浏览器语言设置，中文版本请使用简体中文，英文版本请设置为英文。

**Comment by yiyangitex** [comment]
已经解决了，麻烦了

Yu FranzKafka ***@***.***>于2023年5月25日 周四23:17写道：
