### ISSUE TITLE
单核CPU中出现问题

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [FranzKafkaYu/x-ui#405]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/FranzKafkaYu/x-ui/assets/60098441/4cd7dbba-e692-4e2f-8dee-043ccc616536)
一直提示这个，过了一段时间之后，整个前端界面就不显示404了，有好的办法解决这个问题吗？

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```
最新版
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
![image](https://github.com/FranzKafkaYu/x-ui/assets/60098441/f329733e-8eb3-428e-bd64-c55ef7b004e0)

</details>

**Comment by kuailedeluojie-sudo** [comment]
> 这只是警告，不会有任何影响。另外，你得问题是404 not found么

是的，网页404，进不去网页管理了，在shell 界面用x-ui终端也进不去

**Comment by FranzKafkaYu** [comment]
@kuailedeluojie-sudo 为什么不愿意看WIKI文档呢，Issues区与Discussion区都有说明

**Comment by kuailedeluojie-sudo** [comment]
> @kuailedeluojie-sudo 为什么不愿意看WIKI文档呢，Issues区与Discussion区都有说明

![image](https://github.com/FranzKafkaYu/x-ui/assets/60098441/f39aa22b-7e5f-4fd1-b6ee-be34df8fe8ce)
我是从那个老版本升级过来之后遇到了这个问题，然后我把那个老版本卸载了，用脚本重新安装了一次还是遇到这个问题，我在wiki 上看到这个，就提交了一下。。。

**Comment by FranzKafkaYu** [comment]
@kuailedeluojie-sudo 404 not found这是特性，不是问题，请使用新生成的根路径进行登录。

**Comment by kuailedeluojie-sudo** [comment]
> @kuailedeluojie-sudo 404 not found这是特性，不是问题，请使用新生成的根路径进行登录。

好的，谢谢你
