### ISSUE TITLE
发现一个设置outbounds的BUG

### ISSUE THREAD

**Issue by jyogyou** [FranzKafkaYu/x-ui#406]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

我发现只要设置了一个outbounds后，不管有没有设置routing，所有的流量都会走这个outbound，尤其是做内部反向代理的时候。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
该问题请参考xray core官方文档。
