### ISSUE TITLE
自动更新面板失败

### ISSUE THREAD

**Issue by weitfly** [FranzKafkaYu/x-ui#411]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

第一次进入面板后，点击面板设置，自动更新面板设置会失败：
![image](https://github.com/FranzKafkaYu/x-ui/assets/134786537/99c55e93-b881-49f8-bc59-5dba73180f66)

系统为：centos7.9
内核为：Linux 6.3.4-1.el7.elrepo.x86_64
状态：
[root@VM-0-17-centos ~]# x-ui status
● x-ui.service - x-ui Service
   Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2023-05-27 20:30:46 CST; 36min ago
 Main PID: 3098 (x-ui)
   CGroup: /system.slice/x-ui.service
           ├─ 3098 /usr/local/x-ui/x-ui
           └─15380 bin/xray-linux-amd64 -c bin/config.json

May 27 21:06:43 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:43 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:44 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:44 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:45 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:45 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:46 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:46 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:47 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:47 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:48 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:48 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:49 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:49 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:50 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:50 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:51 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:51 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap
May 27 21:06:52 VM-0-17-centos x-ui[3098]: 2023/05/27 21:06:52 WARNING - CpuStatusMonitorNotify run failed: key <cpulimitNotifyConfig> not in defaultValueMap

当前面板信息：
[INF] 当前面板信息[current panel info]:
面板版本[version]: 0.3.4.2:20230409
用户名[username]: admin
密码[userpasswd]: admin
监听端口[port]: 8001
根路径[basePath]: /

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by weitfly** [comment]
![image](https://github.com/FranzKafkaYu/x-ui/assets/134786537/33c18f83-46e2-4fd4-ba9e-aca1b044f4e5)

**Comment by FranzKafkaYu** [comment]
需关注是否有新的面板更路径生成，如生成了新的面板根路径，请直接以新的根路径进行登录；如没有生成，请检查网络状态或尝试更换浏览器
