### ISSUE TITLE
日志报错，管理后台无法打开

### ISSUE THREAD

**Issue by jackchang1025** [FranzKafkaYu/x-ui#412]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

日志报错，管理后台无法打开

### Version of x-ui

<img width="434" alt="微信截图_20230529161827" src="https://github.com/FranzKafkaYu/x-ui/assets/71494064/780cb1af-77ea-4a3d-8f51-f66f0d4557d9">

### x-ui log or xray log

<img width="806" alt="微信截图_20230529161635" src="https://github.com/FranzKafkaYu/x-ui/assets/71494064/bb93af16-23e1-47e7-9cbc-e0084e3bb3f5">

**Comment by FranzKafkaYu** [comment]
@jackchang1025 日志只是warning，没有任何影响。如页面空白，请确认浏览器语言是否与版本对应。如页面提示404 not found，请确认面板对应根路径。
