### ISSUE TITLE
x-ui状态错误，设置的节点也无法访问

### ISSUE THREAD

**Issue by CC342** [FranzKafkaYu/x-ui#413]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

 WARNING - CpuStatusMonitorNotify run failed: key <cpu>

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```
May 29 11:42:35 ubuntucc x-ui[7731]: 2023/05/29 11:42:35 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:35 ubuntucc x-ui[7731]: 2023/05/29 11:42:35 INFO - get xray version from database: v1.8.1
May 29 11:42:35 ubuntucc x-ui[7731]: 2023/05/29 11:42:35 INFO - xray Version from database is: v1.8.1

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
May 29 11:42:36 ubuntucc x-ui[7731]: 2023/05/29 11:42:36 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:37 ubuntucc x-ui[7731]: 2023/05/29 11:42:37 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:38 ubuntucc x-ui[7731]: 2023/05/29 11:42:38 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:39 ubuntucc x-ui[7731]: 2023/05/29 11:42:39 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:40 ubuntucc x-ui[7731]: 2023/05/29 11:42:40 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:41 ubuntucc x-ui[7731]: 2023/05/29 11:42:41 WARNING - CpuStatusMonitorNotify run failed: key <cpu>
May 29 11:42:42 ubuntucc x-ui[7731]: 2023/05/29 11:42:42 WARNING - CpuStatusMonitorNotify run failed: key <cpu>

</details>

**Comment by FranzKafkaYu** [comment]
这只是warning，实际无任何影响。节点问题请检查自身配置。
