### ISSUE TITLE
建议增加 ssl 证书 OCSP装订更新 代码 "ocspStapling": 3600

### ISSUE THREAD

**Issue by i-Eureka** [FranzKafkaYu/x-ui#416]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

OCSP 装订更新，与证书热重载的时间间隔。引用地址 ：[https://xtls.github.io/config/transport.html#realityobject](url)
虽然xtls官方说明“ocspStapling默认值为 3600，即一小时”，但是如果不配置该内容"ocspStapling": 3600，在https://www.ssllabs.com 测试 OCSP stapling 显示为 No ，反之为 yes。
下图为未配置"ocspStapling": "" 或 "ocspStapling": 3600 后的测试内容（亦是当前x-ui生成的配置状态）
![image](https://github.com/FranzKafkaYu/x-ui/assets/71005669/586cac1e-9291-46c5-a6e4-6aca85b86d74)
下图为配置"ocspStapling": 3600 后的测试内容
![image](https://github.com/FranzKafkaYu/x-ui/assets/71005669/8f299e09-fabe-43ac-8449-fdcfb49e0ae7)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@i-Eureka 最新版本已增加该设定。

**Comment by i-Eureka** [comment]
装订更新 生成配置"ocspStapling": "36000"，"36000" 不可加引号，应当为"ocspStapling": 3600
 > infra/conf/serial: failed to read config file at line 154 char 37 > json: cannot unmarshal string into Go struct field TLSCertConfig.inbounds.streamSettings.tlsSettings.certificates.ocspStapling of type uint6

**Comment by FranzKafkaYu** [comment]
已修复并更新binary,可再重新安装。
