### ISSUE TITLE
新版本出现端口重复绑定

### ISSUE THREAD

**Issue by 454592673** [FranzKafkaYu/x-ui#419]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/FranzKafkaYu/x-ui/assets/22283930/bff9f0b6-9924-40c7-8300-ae3ef4e63f27)
使用新版本搭建vless+reality出现端口重复绑定问题，试了很多次，一直这样

### Version of x-ui

<details>

```console
$ x-ui version 0.3.4.3
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by 454592673** [comment]
搭建第一个正常，到了第二个就这样，现在面打不开了404 page not found

**Comment by FranzKafkaYu** [comment]
无法复现该问题，请使用lsof 命令确认端口是否被其他服务占用。

**Comment by 454592673** [comment]
是新建/删除同一个端口、用户uid节点，相当于重复操作同配置，端口和uid相同

**Comment by 454592673** [comment]
比如，新建一个端口号为4123，uid为asd....的节点，创建成功后，删除掉，然后再新增一个端口号为4123，uid为asd...的节点，就报错了
