### ISSUE TITLE
issues with 'Add Inbound' page with FireFox

### ISSUE THREAD

**Issue by jpyNicolas** [FranzKafkaYu/x-ui#420]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [x] Yes, I have read all WIKI document,nothing can help me in my problem.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Dear FranzKafkaYu,

After update to lasest release, The "Add Inbound" page does not open on the Firefox browser.

x-ui: 0.3.4.3
firefox: 114.0.1

**Comment by ray777ray** [comment]
I have the same issue 
not just firefox but all other browsers 
tried many servers 
it happens with newly installed x-ui
please fix it

**Comment by FranzKafkaYu** [comment]
@jpyNicolas @ray777ray Chinese Version or En Version

**Comment by jpyNicolas** [comment]
En version

**Comment by ray777ray** [comment]
En version

**Comment by ray777ray** [comment]
I checked the Chinese version,it has the same problem

**Comment by FranzKafkaYu** [comment]
I test with Google Chrome and Duckduckgo,it works perfectly.So I guess u may check your language settings or try other browsers.

**Comment by jpyNicolas** [comment]
Yeah it works on chrome. But in firefox console debug i got this error:

```
ReferenceError: inModal is not defined
    openAddInbound https://example.com/xui/inbounds:399
    VueJS 4
        He
        n
        He
        $emit
    handleClick https://example.com/assets/ant-design-vue@1.7.2/antd.min.js:2
    VueJS 6
vue.min.js:6:11752
    VueJS 7
    handleClick https://example.com/assets/ant-design-vue@1.7.2/antd.min.js:2
    VueJS 159
    <anonymous> https://example.com/xui/inbounds:324

```

**Comment by FranzKafkaYu** [comment]
> Yeah it works on Chromium based browsers. But in Firefox console debug i got this error:
> 
> ```
> ReferenceError: inModal is not defined
>     openAddInbound https://example.com/xui/inbounds:399
>     VueJS 4
>         He
>         n
>         He
>         $emit
>     handleClick https://example.com/assets/ant-design-vue@1.7.2/antd.min.js:2
>     VueJS 6
> vue.min.js:6:11752
>     VueJS 7
>     handleClick https://example.com/assets/ant-design-vue@1.7.2/antd.min.js:2
>     VueJS 159
>     <anonymous> https://example.com/xui/inbounds:324
> ```

it is weired,in my Firefox it can work.My Fixfor version is  113.0.2 64bit.I have no idea why you will encounter such problems here.but if you can use other browsers,this issue can closed.

**Comment by arnnis** [comment]
on Brave browser, it works by disabling Brave Shields.
