### ISSUE TITLE
如何知道有哪些用户当前正连接到我的服务端

### ISSUE THREAD

**Issue by toyo2333** [FranzKafkaYu/x-ui#421]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

不知道是不是被盗链了。想知道如何看当前有几个用户（哪些IP）连接到vps上的服务端？

X-ui日志里的这个”Jun 10 13:03:52 ip-172-26-38-67 x-ui[576485]: 2023/06/10 13:03:52 INFO - We got 1 members in client
“
---这是客户端没有连接的时候打印出来的。我重启x-ui后就看到这个

这个代表什么呢？

### Version of x-ui

最新版

### x-ui log or xray log

NULL

**Comment by FranzKafkaYu** [comment]
最准确的方法是查看xray日志。
