### ISSUE TITLE
流量监控功能失效，需要帮助

### ISSUE THREAD

**Issue by AIDA64S** [FranzKafkaYu/x-ui#423]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

流量监控功能失效，日志提示流量检测失败，具体内容如下
使用协议VLESS+Reality

### Version of x-ui

`面板版本[version]: 0.3.4.3:20230610`
`Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)
`
以下是xray config文件
`{
  "log": null,
  "routing": null,
  "dns": null,
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "模板uuid",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.microsoft.com:443",
          "xver": 0,
          "serverNames": [
            "www.microsoft.com"
          ],
          "privateKey": "模板私钥",
          "minClientVer": "",
          "maxClientVer": "",
          "maxTimeDiff": 0,
          "shortIds": [
            ""
          ]
        }
      },
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "实际uuid",
            "email": "邮箱",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.microsoft.com:443",
          "xver": 0,
          "serverNames": [
            "www.microsoft.com"
          ],
          "privateKey": "实际私钥",
          "publicKey": "实际公钥",
          "minClient": "",
          "maxClient": "",
          "maxTimediff": 0,
          "shortIds": [
            ""
          ]
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          },
          "acceptProxyProtocol": false
        }
      },
      "tag": "inbound-443",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "transport": null,
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "reverse": null,
  "fakeDns": null
}`

### x-ui log or xray log

`Jun 11 22:33:24 iZt4navsqfn7j0stnnbgecZ x-ui[132404]: 2023/06/11 22:33:24 WARNING - get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
Jun 11 22:33:42 iZt4navsqfn7j0stnnbgecZ x-ui[132404]: 2023/06/11 22:33:42 WARNING - get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
Jun 11 22:34:00 iZt4navsqfn7j0stnnbgecZ x-ui[132404]: 2023/06/11 22:34:00 WARNING - get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"
`

**Comment by FranzKafkaYu** [comment]
@AIDA64S 请问是一直无法统计么，日志上来看rpc通信存在问题。

**Comment by AIDA64S** [comment]
> @AIDA64S 请问是一直无法统计么，日志上来看rpc通信存在问题。

是的，从我今天安装完毕到现在流量统计为0，我另一个使用vless+tls+ws的vps也是这样

**Comment by FranzKafkaYu** [comment]
@AIDA64S 可以尝试修改面板中的配置模板部分，将api使用的端口由`62789`改为其他未被使用的端口进行尝试

**Comment by AIDA64S** [comment]
> 

我好像没有找到在哪里修改x-ui的api端口

**Comment by FranzKafkaYu** [comment]
> > 
> 
> 我好像没有找到在哪里修改x-ui的api端口

进入面板设置部分，在xray 配置模板中，可以看到原本的API端口为62789,修改该端口为其他未被使用的端口进行尝试。

**Comment by AIDA64S** [comment]
> > > 
> > 
> > 
> > 我好像没有找到在哪里修改x-ui的api端口
> 
> 进入面板设置部分，在xray 配置模板中，可以看到原本的API端口为62789,修改该端口为其他未被使用的端口进行尝试。

我的模板中并未看到API端口的字段，我也尝试在Project X中的文档中找过，也没找到对应字段API
在服务器中`/usr/local/x-ui/bin/config.json`中也没看到

**Comment by FranzKafkaYu** [comment]
@AIDA64S 
```  
{
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
```

**Comment by FranzKafkaYu** [comment]
如果你自行修改过配置模板，导致模板中没有此部分设置，请卸载后重新安装

**Comment by AIDA64S** [comment]
> {
>         "address": "127.0.0.1"
>       },

谢谢您，我想我知道我的问题在哪里了
