### ISSUE TITLE
Clicking on Add Inbound doesn't work

### ISSUE THREAD

**Issue by houmie** [FranzKafkaYu/x-ui#424]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I installed the English version.
bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install_en.sh)

Clicking on "Add Inbound" button doesn't do anything.  Tested both on Safari and Firefox.

### Version of x-ui

<details>

No support for version.

```
x-ui              - Enter control menu
x-ui start        - Start x-ui
x-ui stop         - Stop  x-ui
x-ui restart      - Restart x-ui
x-ui status       - Show x-ui status
x-ui enable       - Enable x-ui on system startup
x-ui disable      - Disable x-ui on system startup
x-ui log          - Check x-ui logs
x-ui update       - Update x-ui
x-ui install      - Install x-ui
x-ui uninstall    - Uninstall x-ui
------------------------------------------
```

</details>

### x-ui log or xray log

<details>

```
Jun 12 10:39:18 gymmotivator x-ui[46368]: 2023/06/12 10:39:18 INFO - houmie login success,Ip Address:xxxx
Jun 12 10:39:18 gymmotivator x-ui[46368]: 2023/06/12 10:39:18 [sessions] ERROR! securecookie: the value is not valid
Jun 12 10:39:18 gymmotivator x-ui[46368]: 2023/06/12 10:39:18 INFO - user 1 login success
```

</details>

**Comment by FranzKafkaYu** [comment]
similar issue is [here](https://github.com/FranzKafkaYu/x-ui/issues/420),my suggestions:  
1.change other browsers to try,I test it with Chrome/Firefox/Duckduckgo,it can work perfectly  
2.clear caches and cookies then retry
