### ISSUE TITLE
最新0.3.4.3存在掉用户端口情况

### ISSUE THREAD

**Issue by sk007** [FranzKafkaYu/x-ui#428]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

系统：Debian11 
问题描述：
多开几个账户 运行一段时间 
个别用户会掉线 查看端口是关闭状态  不能连接

解决方案：
需要手动面板重启Xray才可以
上个版本没问题 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@sk007 是否开启了设备限制?

**Comment by sk007** [comment]
没有

**Comment by sk007** [comment]
流量和设备限制都没开

**Comment by FranzKafkaYu** [comment]
1.出现无法连接时请查看xray状态，请确认其处于运行状态  
2.检查`/usr/local/x-ui/bin/config.json`内容,请确认对应节点与用户配置都正常  
3.检查端口监听情况与防火墙状态

**Comment by sk007** [comment]
运行状态都正常 json配置都正确 防火墙都是关闭的
就是运行不到一天 个别账户会掉线 需要重启xray后就正常了
谢谢大佬及时回复

**Comment by sk007** [comment]
然后不一定 什么时候又掉了 不确定时间的

**Comment by FranzKafkaYu** [comment]
> 个别账户会掉线

是同一个端口下的不同用户，个别用户会掉线无法链接么

**Comment by sk007** [comment]
> > 个别账户会掉线
> 
> 是同一个端口下的不同用户，个别用户会掉线无法链接么

端口掉了 一个端口下就一个用户

**Comment by FranzKafkaYu** [comment]
> > > 个别账户会掉线
> > 
> > 
> > 是同一个端口下的不同用户，个别用户会掉线无法链接么
> 
> 端口掉了 一个端口下就一个用户

如何出现问题时配置文件内仍旧存在相应端口的配置，则不存在`端口掉了`的问题，你是如何判断端口掉了的呢

**Comment by sk007** [comment]
不能连接时 
用ping.pe进行测试 国内外都不通 
面板重启xray后 都通了

**Comment by sk007** [comment]
好的 感谢大佬
