### ISSUE TITLE
页面能否增加ip白名单，http和socks5类型，有白名单ip的不需要身份验证

### ISSUE THREAD

**Issue by zhulinzi0812** [FranzKafkaYu/x-ui#429]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

ip白名单是比较常用的，很多的ip代理公司，在用户买的ip代理账号的时候，有专门的白名单设置，添加后，用户使用他们给的ip就不需要身份验证。其中有一个常见爬虫的问题，selenium是通过控制浏览器驱动操作浏览器行为的爬虫框架，selenium在使用ip代理的时候，如果是http和socks5需要身份验证，浏览器会跳出弹出框手动输入用户名和密码，操作系统可能出于安全问题的考虑才会这样的，尝试很多方法都避免不了，如果很白名单就很方便了。

### Version of x-ui

<details>

当前版本

</details>

### x-ui log or xray log

<details>

无，功能上的扩展

</details>

**Comment by FranzKafkaYu** [comment]
IP白名单内的用户登录无需账户名与密码么，不会支持。  
如果你是指IP白名单内的用户才能进行登录，可以考虑。
