### ISSUE TITLE
一直都是loading状态

### ISSUE THREAD

**Issue by MichaelYang1125** [FranzKafkaYu/x-ui#431]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

1.添加节点后，点击保存，一直是loading状态。刷新后没有保存成功。
2.面板设置页面，添加证书路径，或者第一次面板路径自动修改后，都是一直是loading状态。
![2023-06-16_135949](https://github.com/FranzKafkaYu/x-ui/assets/97076222/10802cb3-6908-4747-bc71-1f363ee9006d)
![2023-06-16_135851](https://github.com/FranzKafkaYu/x-ui/assets/97076222/f7e9910d-d693-44ba-8dc9-d471b98bee3a)

### Version of x-ui

**_[INF] 当前面板信息[current panel info]:
面板版本[version]: 0.3.4.3:20230610_**

### x-ui log or xray log

<details>

```console
admin login success,Ip Address:21.21.21.21
6月 16 13:58:01 us01.123.com x-ui[1654]: 2023/06/16 13:58:01 [sessions] ERROR! securecookie: the value is not valid
6月 16 13:58:01 us01.123.com x-ui[1654]: 2023/06/16 13:58:01 INFO - user 1 login success
6月 16 13:58:14 us01.123.com x-ui[1654]: 2023/06/16 13:58:14 INFO - RecordXrayVersion: v1.8.1
6月 16 14:01:44 us01.123.com x-ui[1654]: 2023/06/16 14:01:44 INFO - user 1 logout
6月 16 14:12:28 us01.123.com x-ui[1654]: 2023/06/16 14:12:28 WARNING - stop server err: multierr: context canceled | close tcp [::]:54321: use of closed network connection |
6月 16 14:12:28 us01.123.com x-ui[1654]: 2023/06/16 14:12:28 INFO - web server run http on [::]:54321
6月 16 14:12:28 us01.123.com x-ui[1654]: 2023/06/16 14:12:28 INFO - Wait 2 seconds for telegram bot ready
6月 16 14:12:55 us01.123.com x-ui[1654]: 2023/06/16 14:12:55 WARNING - 修改设置失败:  read tcp 123.123.123.123:54321->21.21.21.21:10397: read: connection reset by peer
```

</details>

**Comment by FranzKafkaYu** [comment]
1.请尽量保证浏览器语言设置与版本相对应。
2.更换浏览器就行常识。

**Comment by MichaelYang1125** [comment]
> 1.请尽量保证浏览器语言设置与版本相对应。 2.更换浏览器就行常识。

谢谢 @FranzKafkaYu 您的回复。

关于：
1和2 出现的现象我在服务器端安装的都是中文版本的脚本，服务器时间也都设定到GMT+8,  浏览器页面语言设置中文或者英文都不行，都是一直loading的状态，我估计是服务器端某些问题或者版本，我更换到Azure的服务器，同样的安装步骤和浏览设置方式，却可以完成。虽然更换服务器可以解决，但还是想在现有的服务器上找到原因。。 目前reinstall系统 centos7 和debian 10 还是一直是loading的状态，会不会是服务器端某些设置，或者权限，让修改的路径或者添加的服务器节点配置，不能存储呢？

谢谢。

**Comment by MichaelYang1125** [comment]
> 1.请尽量保证浏览器语言设置与版本相对应。 2.更换浏览器就行常识。

谢谢 @FranzKafkaYu  您的回复。

关于：
1和2 出现的现象我在服务器端安装的都是中文版本的脚本，服务器时间也都设定到GMT+8, 浏览器页面语言设置中文或者英文都不行，都是一直loading的状态，我估计是服务器端某些问题或者版本，我更换到Azure的服务器，同样的安装步骤和浏览设置方式，却可以完成。虽然更换服务器可以解决，但还是想在现有的服务器上找到原因。。 目前reinstall系统 centos7 和debian 10 还是一直是loading的状态，会不会是服务器端某些设置，或者权限，让修改的路径或者添加的服务器节点配置，不能存储呢？

谢谢。

**Comment by FranzKafkaYu** [comment]
@MichaelYang1125 不存在你说的此类问题，建议检测服务器设置。
