### ISSUE TITLE
Chrome访问面板只会显示标签页标题，页面空白

### ISSUE THREAD

**Issue by kobehuanghai** [FranzKafkaYu/x-ui#433]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

原版x-ui不会出现这个问题，chrome有问题，edge无问题，感觉是浏览器设置的问题，但是搜了半天找不到是chrome什么设置导致的问题，求教，感谢

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
1.浏览器语言设定  
2.尝试清除浏览器缓存与cookie

**Comment by kobehuanghai** [comment]
> 1.浏览器语言设定 2.尝试清除浏览器缓存与cookie

果然是语言设置的问题。。。感谢

**Comment by zygame** [comment]
我也遇到过，重启面板有效

Yu FranzKafka ***@***.***>于2023年6月18日 周日21:58写道：
