### ISSUE TITLE
配置Reality设置uTLS设置项未写入配置文件

### ISSUE THREAD

**Issue by toyo2333** [FranzKafkaYu/x-ui#437]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

在XUI创建一个vless+reality节点
+user里面utls选项选择chrome。

但最终保存的配置文件里reality setting里 没有找到   "fingerprint": "chrome",这一项。

请问这是为啥呢? 

那我客户端再配置fingerprint里选了chrome会怎样？

盼望答复。

### Version of x-ui

最新

### x-ui log or xray log

null

**Comment by FranzKafkaYu** [comment]
@toyo2333 utls设置用于客户端，服务端无需配置。

**Comment by toyo2333** [comment]
> @toyo2333 utls设置用于客户端，服务端无需配置。

非常感谢！x-ui真好用！
