### ISSUE TITLE
vless用户如果填写了邮箱的话流量显示会失效

### ISSUE THREAD

**Issue by ashton2914** [FranzKafkaYu/x-ui#438]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

> trojan协议下无问题 vless协议下有问题

## 目前的状况
1. Vless协议新建用户并填写邮箱，下方此用户的流量显示变为NaN
![IMG_8080 Copy](https://github.com/FranzKafkaYu/x-ui/assets/17692778/60ad496d-e951-4acc-8702-b7ecd5707cb2)

2. 把邮箱删掉，下方正常显示0，但实际这个0不会随用户使用变化。
![IMG_8081](https://github.com/FranzKafkaYu/x-ui/assets/17692778/62d65790-7c5e-4a45-9295-83dd74a823e8)

## 期待的状况
1. 填写邮箱正常显示此邮箱对应用户的流量
2. 删除邮箱显示NaN

### Version of x-ui

<details>

```console
$ x-ui version
# 面板版本[version]: 0.3.4.3:20230610
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@ashton2914   
针对问题1：Vless协议新建用户并填写邮箱，下方此用户的流量显示变为NaN    
新建用户时尚未开启统计（无未激活字样）,面板默认显示NaN，只要用户开始使用，就会进行统计。   
针对问题2：把邮箱删掉，下方正常显示0，但实际这个0不会随用户使用变化  
此时已经成功添加用户（存在已激活字样），不会随用户使用而变化正式由于没有填写邮箱导致，请务必填写邮箱并确保其全局唯一。

**Comment by ashton2914** [comment]
感谢🙏，问题出在全局唯一上，我在两个出站里面的账号填写的是同一邮箱，修改为不同邮箱后一切恢复正常。
