### ISSUE TITLE
可以增加一些新协议吗

### ISSUE THREAD

**Issue by a1564471347** [FranzKafkaYu/x-ui#441]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

希望加入新协议

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by shah123455** [comment]
@a1564471347 Friends, how do I close server ads? I have a Turkish server, it brings a lot of ads into YouTube
But I have an Emirates server, it doesn't show any ads

**Comment by FranzKafkaYu** [comment]
@a1564471347  当前xray core支持的协议都已支持，不存在“新协议”

**Comment by a1564471347** [comment]
> @a1564471347 Friends, how do I close server ads? I have a Turkish server, it brings a lot of ads into YouTube
> But I have an Emirates server, it doesn't show any ads
ios or macos use surge，loon，quantumultx，shadowrocket，https://raw.githubusercontent.com/Maasea/sgmodule/master/YoutubeAds.sgmodule

**Comment by a1564471347** [comment]
> @a1564471347 当前xray core支持的协议都已支持，不存在“新协议”

比如hysteria，tuic，tuic v5，snell
