### ISSUE TITLE
单端口多用户下，个别账户会失效，端口连接不上，修改端口后正常

### ISSUE THREAD

**Issue by 907904228** [FranzKafkaYu/x-ui#444]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

不知道为什么，很奇怪

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@907904228  请确认对应账户的流量、时间限制未生效；另无法连接时请提供相关报错日志进行排查

**Comment by 907904228** [comment]
> @907904228 请确认对应账户的流量、时间限制未生效；另无法连接时请提供相关报错日志进行排查

感谢大佬回复。没有流量、时间限制，重启x-ui后也无法恢复。以下是部分日志：

Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 x-ui 0.3.4.3:20230610
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - web server run http on [::]:54321
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 1 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 1 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 3 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 10 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 3 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 10 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - We got 6 members in client
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - delete disabled client,index: 3
Jul 06 21:38:33 racknerd-e53e88 x-ui[4214]: 2023/07/06 21:38:33 INFO - Wait 2 seconds for telegram bot ready

**Comment by FranzKafkaYu** [comment]
@907904228 从x-ui日志来看，存在用户限制生效的情况，另外无法连接时需要的是客户端日志。

**Comment by 907904228** [comment]
@FranzKafkaYu 我不会看客户端的日志，sorry，只能找到这个记录。用户限制生效是因为我刚才添加了时间限制，但对最终结果没有影响，不论有没有时间限制，都是更改端口后就可以正常访问了

<img width="515" alt="image" src="https://github.com/FranzKafkaYu/x-ui/assets/24412137/178126d6-8711-4557-918b-ba3f29404490">
<img width="515" alt="image" src="https://github.com/FranzKafkaYu/x-ui/assets/24412137/37ecbc78-f4aa-49ee-bd67-f72af5be95be">

**Comment by FranzKafkaYu** [comment]
@907904228 确认是该端口下部分用户无法连接而其他用户则可以么，如果是简单的更换端口即恢复更怀疑是端口被Q，更换客户端使用也有类似情况么

**Comment by 907904228** [comment]
@FranzKafkaYu 你好，确认这个端口下的所有用户都无法连接，其他端口可以，跟换其他客户端也是一样的。可能是因为流量太大了导致端口被墙？但总共也才两个G的流量消耗。很奇怪，我还是单人单端口试试。

**Comment by FranzKafkaYu** [comment]
很大可能是端口被墙，请通过`ping.pe`进行测试，尽可能使用安全的协议组合;`vless+xtls-rprx-vision+reality`
