### ISSUE TITLE
无法进入面板

### ISSUE THREAD

**Issue by ZuesTao** [FranzKafkaYu/x-ui#445]
系统 Ubuntu 18.04.2 LTS (GNU/Linux 4.4.0-1128-aws x86_64)

System has not been booted with systemd as init system (PID 1). Can't operate.
面板状态: 未运行
是否开机自启: 是
xray 状态: 未运行

请输入选择 [0-17],查看面板登录信息请输入数字[7:12](https://www.youtube.com/watch?v=hvQ376tyZZM&t=432s)
System has not been booted with systemd as init system (PID 1). Can't operate.
No journal files were found.

设置端口后提示如下：
set port 7777 success面板端口设定完成
System has not been booted with systemd as init system (PID 1). Can't operate.
Created symlink /etc/systemd/system/multi-user.target.wants/x-ui.service → /etc/systemd/system/x-ui.service.
System has not been booted with systemd as init system (PID 1). Can't operate.

**Comment by FranzKafkaYu** [comment]
@ZuesTao 你的系统未支持`systemd`，建议更换更新的系统。

**Comment by ZuesTao** [comment]
已收到您的邮件!

**Comment by ZuesTao** [comment]
我这个vps无法升级系统，只能使用ubantu18.04.2，大佬能否更新版本向下兼容一下我这个版本的系统，感激不尽

**Comment by FranzKafkaYu** [comment]
没有精力也没有意义去向下兼容，你的内核太老了，不支持systemd，建议放弃。
