### ISSUE TITLE
IptablesCreateOwnChain create failed,error Info exit status 1

### ISSUE THREAD

**Issue by RonaldinhoL** [FranzKafkaYu/x-ui#446]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

远程无法访问面板端口，搜了一下代码好像没找到这条日志哪里打出来的？

### Version of x-ui

0.3.4.3:20230610

### x-ui log or xray log

systemd[1]: Started x-ui Service.
systemd[1]: Starting x-ui Service...
x-ui[16770]: 2023/07/09 03:27:26 x-ui 0.3.4.3:20230610
x-ui[16770]: 2023/07/09 03:27:26 INFO - web server run http on [::]:8080
x-ui[16770]: IptablesCreateOwnChain create failed,error Info exit status 1
x-ui[16770]: 2023/07/09 03:27:26 WARNING - start xray warnging,create x-ui own chain failed
x-ui[16770]: 2023/07/09 03:27:26 INFO - We got 1 members in client
x-ui[16770]: 2023/07/09 03:27:26 INFO - Wait 2 seconds for telegram bot ready
x-ui[16770]: SSHLogin[2023-07-09 02:51:00] early than XUI start[2023-07-09 03:27:26],don't notify

**Comment by FranzKafkaYu** [comment]
@RonaldinhoL iptables相关报错只会影响设备限制功能，其他无影响，请从其他方面排查。

**Comment by scramjetFoam** [comment]
> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> 远程无法访问面板端口，搜了一下代码好像没找到这条日志哪里打出来的？
> 
> ### Version of x-ui
> 0.3.4.3:20230610
> 
> ### x-ui log or xray log
> systemd[1]: Started x-ui Service. systemd[1]: Starting x-ui Service... x-ui[16770]: 2023/07/09 03:27:26 x-ui 0.3.4.3:20230610 x-ui[16770]: 2023/07/09 03:27:26 INFO - web server run http on [::]:8080 x-ui[16770]: IptablesCreateOwnChain create failed,error Info exit status 1 x-ui[16770]: 2023/07/09 03:27:26 WARNING - start xray warnging,create x-ui own chain failed x-ui[16770]: 2023/07/09 03:27:26 INFO - We got 1 members in client x-ui[16770]: 2023/07/09 03:27:26 INFO - Wait 2 seconds for telegram bot ready x-ui[16770]: SSHLogin[2023-07-09 02:51:00] early than XUI start[2023-07-09 03:27:26],don't notify

我也遇到了这个问题，请问您是怎么解决的？

**Comment by RonaldinhoL** [comment]
> > ### Welcome
> > * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> > * [x]  Yes, I'm using the supported system. Only such systems are supported.
> > * [x]  Yes, I have read all WIKI document,nothing can help me in my problem.
> > * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> > * [x]  Yes, I've included all information below (version, config, log, etc).
> > 
> > ### Description of the problem,screencshot would be good
> > 远程无法访问面板端口，搜了一下代码好像没找到这条日志哪里打出来的？
> > 
> > ### Version of x-ui
> > 0.3.4.3:20230610
> > 
> > ### x-ui log or xray log
> > systemd[1]: Started x-ui Service. systemd[1]: Starting x-ui Service... x-ui[16770]: 2023/07/09 03:27:26 x-ui 0.3.4.3:20230610 x-ui[16770]: 2023/07/09 03:27:26 INFO - web server run http on [::]:8080 x-ui[16770]: IptablesCreateOwnChain create failed,error Info exit status 1 x-ui[16770]: 2023/07/09 03:27:26 WARNING - start xray warnging,create x-ui own chain failed x-ui[16770]: 2023/07/09 03:27:26 INFO - We got 1 members in client x-ui[16770]: 2023/07/09 03:27:26 INFO - Wait 2 seconds for telegram bot ready x-ui[16770]: SSHLogin[2023-07-09 02:51:00] early than XUI start[2023-07-09 03:27:26],don't notify
> 
> 我也遇到了这个问题，请问您是怎么解决的？

我是iptables拦截了
