### ISSUE TITLE
中文版本部署后，在全英文环境下无法访问，似乎存在国际化适配问题

### ISSUE THREAD

**Issue by ihategfw** [FranzKafkaYu/x-ui#449]
### Description of the problem,screencshot would be good

1. 部署版本为`0.3.4.3` `x-ui-linux-amd64.tar.gz`
2. 访问环境为全英文，系统设置地区为美国；当浏览器环境为中文时无此问题
3. 访问登陆页，HTML加载到第64行`<a-input v-model.trim="user.username" placeholder='`就戛然而止，似乎在替换`{{ i18n "username" }}`时遇到了问题

### Version of x-ui

0.3.4.3

**Comment by Mydong** [comment]
确实是这个问题，我还以为是怎么了。
![image](https://github.com/FranzKafkaYu/x-ui/assets/14023137/f5234375-6f5e-4bea-ba8c-4f65d50c8c7e)

**Comment by adamlau98** [comment]
同样，用Edge就打不开，Chrome可以

**Comment by FranzKafkaYu** [comment]
请设置浏览器语言为En(US),个人无法复现你们的问题。

**Comment by Mydong** [comment]
> 请设置浏览器语言为En(US),个人无法复现你们的问题。
![image](https://github.com/FranzKafkaYu/x-ui/assets/14023137/b748bcbd-c587-42ca-b947-e569a3db369c)
 
当默认是 EN 时，会出现。
