### ISSUE TITLE
发现一个关于ipv4和ipv6同时使用情况下的节点创建问题（疑似BUG）

### ISSUE THREAD

**Issue by TaoRone** [FranzKafkaYu/x-ui#450]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

机器同时有ipv4 ipv6双栈
默认xray文件情况下，x-ui创建节点，开tls和证书验证，V4一切正常
V6创建任何节点，使用ws，开tls，创建任何协议都失败，包括SS……折腾了很久
偶然发现如果切换为vmess协议，先不要创建用户，点击详细信息的查看，再点击创建用户，就可以连通

很神奇

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hdchieh** [comment]
It never happened to me.
