### ISSUE TITLE
请问证书的公钥和密钥路径默认是在哪呢？

### ISSUE THREAD

**Issue by nihaohani** [FranzKafkaYu/x-ui#451]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

请问证书的公钥和密钥路径默认是在哪呢？

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>0.3.4.3

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>n/a

**Comment by FranzKafkaYu** [comment]
@nihaohani 使用脚本自带的证书申请功能，证书将安装在/root/cert/目录

**Comment by nihaohani** [comment]
> @nihaohani使用脚本自带的证书申请功能，证书将安装在/root/cert/目录

好的感谢！但是我在面板里无法保存路径。![屏幕截图 2023-07-15 024319](https://github.com/FranzKafkaYu/x-ui/assets/50644202/b246dc8b-bd80-4b6b-9770-ea4e6016925f)
