### ISSUE TITLE
因为www.microsoft.com 变成tls1.2 导致节点用不了的问题

### ISSUE THREAD

**Issue by Sevenagn** [FranzKafkaYu/x-ui#452]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

今天因为www.microsoft.com 变成tls1.2 导致节点用不了，所以需要修改这个地址，面板上有【目标网站】和【可选域名】两个地方需要写域名，请问应该改哪个？这两个是否有关联？
![image](https://github.com/FranzKafkaYu/x-ui/assets/28440998/ec7890ea-b412-4011-8459-f136854b5863)

### Version of x-ui

<details>

```console
0.3.4.3 [Latest]

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
参考:
![IMG_20230715_215601_402](https://github.com/FranzKafkaYu/x-ui/assets/38254177/81d3e192-e33a-4d5c-bc63-24a433c4fe83)
![IMG_20230715_215513_678](https://github.com/FranzKafkaYu/x-ui/assets/38254177/de2760f3-0237-4a31-96da-69881d8bf9bf)
