### ISSUE TITLE
默认reality协议的目标域名建议更改为google

### ISSUE THREAD

**Issue by jiaoting** [FranzKafkaYu/x-ui#453]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

默认的目标域名是Microsoft的网站，但是目前发现，会出现sni封闭，导致无法连接，更改成dl.google.com后就好了，不知道为啥，建议更改默认网站

### Version of x-ui

最新版

### x-ui log or xray log

启动服务(2023/7/16 12:16:26)...
Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 windows/amd64)
A unified platform for anti-censorship.
2023/07/16 12:16:27 [Info] infra/conf/serial: Reading config: stdin:
2023/07/16 12:16:27 [Warning] core: Xray 1.8.3 started
2023/07/16 12:16:27 127.0.0.1:62316 accepted //www.google.com:443 [http1183 -> proxy1183]
2023/07/16 12:16:29 127.0.0.1:62329 accepted tcp:127.0.0.1:0 [api -> api]
2023/07/16 12:16:31 [Warning] failed to handler mux client connection > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF] > common/retry: all retry attempts failed

**Comment by FranzKafkaYu** [comment]
@jiaoting https://github.com/XTLS/Xray-core/issues/2330#issuecomment-1636661384

**Comment by FranzKafkaYu** [comment]
https://github.com/XTLS/Xray-core/discussions/2302
