### ISSUE TITLE
一键申请SSL证书-申请失败

### ISSUE THREAD

**Issue by JssDream** [FranzKafkaYu/x-ui#454]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

域名是.link 免费的，dns托管cf的，cf中a.xxx.link 已经解析到服务器ip
x-ui 
选择16
选择 1
输入域名 a.xxx.link
安装失败，报错：

[Mon Jul 17 07:23:11 UTC 2023] Pending, The CA is processing your order, please just wait. (1/30)
[Mon Jul 17 07:23:15 UTC 2023] a.xxx.xxx:Verify error:2606:4700:3031::ac43:80f2: Invalid response from http://a.xxx.xxx/.well-known/acme-challenge/-2bVN7SR3u1sMudbTBqRpkO9kZvrEGgS--AxUSOtVr4: 521
[Mon Jul 17 07:23:15 UTC 2023] Please add '--debug' or '--log' to check more details.
[Mon Jul 17 07:23:15 UTC 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[ERR] 证书申请失败,原因请参见报错信息 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here

面板版本[version]: 0.3.4.3:20230610

```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
[Mon Jul 17 07:23:11 UTC 2023] Pending, The CA is processing your order, please just wait. (1/30)
[Mon Jul 17 07:23:15 UTC 2023] a.xxx.xxx:Verify error:2606:4700:3031::ac43:80f2: Invalid response from http://a.xxx.xxx/.well-known/acme-challenge/-2bVN7SR3u1sMudbTBqRpkO9kZvrEGgS--AxUSOtVr4: 521
[Mon Jul 17 07:23:15 UTC 2023] Please add '--debug' or '--log' to check more details.
[Mon Jul 17 07:23:15 UTC 2023] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[ERR] 证书申请失败,原因请参见报错信息 

</details>

**Comment by FranzKafkaYu** [comment]
@JssDream `Invalid response from xxxx:521`,从报错信息来看是校验的server offline了,请在其他时间段进行尝试或者使用standalone模式。

**Comment by donkeykangwang10** [comment]
我也和楼主一样的问题，最新版本。唯一的不同是x-ui log的错误代码是404，另外使用的是standalone模式，求教了。谢谢

**Comment by FranzKafkaYu** [comment]
> 我也和楼主一样的问题，最新版本。唯一的不同是x-ui log的错误代码是404，另外使用的是standalone模式，求教了。谢谢

请贴出相应的log日志

**Comment by donkeykangwang10** [comment]
> > 我也和楼主一样的问题，最新版本。唯一的不同是x-ui log的错误代码是404，另外使用的是standalone模式，求教了。谢谢
> 
> 请贴出相应的log日志

补充在楼上了，谢谢
