### ISSUE TITLE
 微软没tls1.3，把 reality 中默认www.microsoft.com改一下吧。。

### ISSUE THREAD

**Issue by moxuanyuan** [FranzKafkaYu/x-ui#456]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

 微软没tls1.3，把 reality 中默认www.microsoft.com改一下吧。。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by 454592673** [comment]
这不是更新了嘛

**Comment by FranzKafkaYu** [comment]
@moxuanyuan https://github.com/FranzKafkaYu/x-ui/releases/tag/0.3.4.4
