### ISSUE TITLE
无法生成新的面板根路径

### ISSUE THREAD

**Issue by trifolium-wang** [FranzKafkaYu/x-ui#457]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

您好，我在安装成功后，点击设置重新生根路径重启后新路径并没有生效，在命令行中查看basePath依然是/， 新的路径是404页面。

### Version of x-ui

<details>

```console
$ x-ui version
# 输入 x-ui version 命令输出主菜单，并没有输出版本号码。
```
</details>

### x-ui log or xray log

<details>

```console
Jul 20 05:15:53 ip-172-31-30-37 x-ui[16788]: 2023/07/20 05:15:53 WARNING - stop server err: multierr: context canceled | close tcp [::]:18081: use of closed network connection |
Jul 20 05:15:53 ip-172-31-30-37 x-ui[16788]: 2023/07/20 05:15:53 INFO - web server run http on [::]:18081
Jul 20 05:15:53 ip-172-31-30-37 x-ui[16788]: 2023/07/20 05:15:53 INFO - Wait 2 seconds for telegram bot ready
Jul 20 05:16:02 ip-172-31-30-37 x-ui[16788]: 2023/07/20 05:16:02 WARNING - 修改设置失败:  read tcp 172.31.30.37:18081->45.33.35.95:62168: read: connection reset by peer
```
</details>

**Comment by FranzKafkaYu** [comment]
@trifolium-wang 请更换网络环境进行尝试，如开启代理的情况下请尝试先关闭代理。

**Comment by trifolium-wang** [comment]
@FranzKafkaYu 感谢支持，已经解决了，一直不知道代理还会造成这个问题，但是为什么这个tcp(ws)连接为什么因为代理会无法连接这个我没能理解,是不是可以改成http轮询会好一些。

**Comment by FranzKafkaYu** [comment]
常规情况下连接代理登录面板进行操作不会有问题，具体问题取决于你个人的网络环境。
