### ISSUE TITLE
根路径为空能否增加开关

### ISSUE THREAD

**Issue by 12189108** [FranzKafkaYu/x-ui#460]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

我有其他方法能保证他无法通过直接访问ip的方式扫描到xui面板，能否增加根路径为空的开关，让我不用一次次去查询根路径

### Version of x-ui

-

### x-ui log or xray log

-

**Comment by FranzKafkaYu** [comment]
为什么要一次次查询，你可以自定义根路径。
