### ISSUE TITLE
SSL证书申请报错

### ISSUE THREAD

**Issue by SpoonerCake** [FranzKafkaYu/x-ui#465]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

请问大佬们这是什么原因导致的？

[Sat Jul 29 19:25:16 CST 2023] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[Sat Jul 29 19:25:17 CST 2023] Domains not changed.
[Sat Jul 29 19:25:17 CST 2023] Skip, Next renewal time is: 2023-07-29T16:39:48Z
[Sat Jul 29 19:25:17 CST 2023] Add '--force' to force to renew.
[ERR] 证书签发失败,脚本退出 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@SpoonerCake 当前环境已有证书
