### ISSUE TITLE
Creating V2Ray App with WebSocket Integration or something like that

### ISSUE THREAD

**Issue by einkaaf** [FranzKafkaYu/x-ui#467]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi everyone! I'm new to V2Ray and looking to build a personal V2Ray app. I want to connect to vmess or vless via this app, but I'm unsure how to go about it. Any guidance, resources, or examples would be highly appreciated! Thank you in advance! 😊 #githubissue #v2ray #websocket

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
v2rayNG based on xray core,plz refer to this [link](https://github.com/2dust/v2rayNG)

**Comment by einkaaf** [comment]
> v2rayNG based on xray core,plz refer to this [link](https://github.com/2dust/v2rayNG)

Sorry for miss understanding , i want to develop my own ( based on flutter ) and don't know how to connect the vpn via vmess or vless ! i know there is app base on kotlin or java !
