### ISSUE TITLE
Bug “添加入站”按鈕無法觸發彈窗Modal事件

### ISSUE THREAD

**Issue by Josh-Zhen** [FranzKafkaYu/x-ui#468]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

系統：CentOS Stream 9
Kernel: Linux 5.14.0-325.el9.x86_64
X-ui日志無報錯。

Bug：前端無法點擊“添加入站”按鈕，Chrome控制台提醒“vue.min.js:6 ReferenceError: inModal is not defined”
![image](https://github.com/FranzKafkaYu/x-ui/assets/29705007/d8b2e924-6f09-4835-a08c-bfddd778fff9)
切換Edge也是如此
![image](https://github.com/FranzKafkaYu/x-ui/assets/29705007/012c4954-8cd3-4176-9f92-1cc21fa94c25)

嘗試重啓X-ui，重啓系統，重裝X-ui均無法解決該問題

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@Josh-Zhen 浏览器语言设置为简体中文
