### ISSUE TITLE
点击入站相关全部无反应

### ISSUE THREAD

**Issue by azumi765** [FranzKafkaYu/x-ui#471]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

点击入站相关的按键全部无响应，之前使用的https://github.com/vaxilu/x-ui/，两天前升级完没什么问题，目前无法建立无法编辑等等。重启程序没有用，切换xray版本也没有用

### Version of x-ui

[version]: 0.3.4.4:20230717
xray1.8.3

### x-ui log or xray log

ー

**Comment by FranzKafkaYu** [comment]
@azumi765 浏览器语言是如何设置的

**Comment by azumi765** [comment]
> @azumi765瀏覽器語言是如何設置的

繁体中文

**Comment by FranzKafkaYu** [comment]
@azumi765 请修改为简体中文

**Comment by azumi765** [comment]
> @azumi765 请修改为简体中文

解决了。感谢
