### ISSUE TITLE
代码与Release包不一致

### ISSUE THREAD

**Issue by voideluyi** [FranzKafkaYu/x-ui#472]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

    经测试,main分支908de646687857a7d8b78e859e3a95df00b29398 commit 上tag为0.3.4.4与release中0.3.4.4 https://github.com/FranzKafkaYu/x-ui/releases/download/0.3.4.4/x-ui-linux-arm64.tar.gz中实际代码不符具体表现为:
1. 没有 setting -show true等参数
2. version为0.3.2

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@voideluyi  https://github.com/FranzKafkaYu/x-ui/issues/341
