### ISSUE TITLE
使用armbian系统，在0.3.4.4/arm64版本中安装完毕后使用x-ui命令会报错，只有手动修改才能正确启动x-ui命令

### ISSUE THREAD

**Issue by dyxp520** [FranzKafkaYu/x-ui#473]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

<img width="724" alt="1690961244535" src="https://github.com/FranzKafkaYu/x-ui/assets/72800884/a79e602d-2688-4a49-97c3-83e1a8cd377c">

### Version of x-ui

0.3.4.4

### x-ui log or xray log

无

**Comment by FranzKafkaYu** [comment]
@dyxp520 PR is welcome,U can help me to add this OS

**Comment by TJT-JTJ** [comment]
I have the same issue with the OrangePi arm64 Ubuntu build...
