### ISSUE TITLE
设备限制

### ISSUE THREAD

**Issue by dongshanxia** [FranzKafkaYu/x-ui#474]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

找不到 0.3.4.4  的源码包

### Version of x-ui

<details>

```console
$ x-ui version 0.3.4.4
# Paste output here
```

</details>

### x-ui log or xray log

<details>
0.3.4.4
```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@dongshanxia https://github.com/FranzKafkaYu/x-ui/issues/341
