### ISSUE TITLE
0.3.3.4

### ISSUE THREAD

**Issue by dongshanxia** [FranzKafkaYu/x-ui#476]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/FranzKafkaYu/x-ui/assets/22125431/02ca402f-14a1-4fbc-8765-3533b4183432)

https://github.com/FranzKafkaYu/x-ui/archive/refs/tags/0.3.4.4.zip  这下载下来 没有自动重置 设备提醒 设备限制
https://github.com/FranzKafkaYu/x-ui/releases/download/0.3.4.4/x-ui-linux-amd64.tar.gz  部署的确有

### Version of x-ui

<details>

```console
自己编译的0.3.2
直接运行的  0.3.3.4 
所以找不到 0.3.3.4  麻烦大佬给下地址
```

</details>

### x-ui log or xray log

<details>

```console
0.3.3.4
```

</details>

**Comment by FranzKafkaYu** [comment]
it's not open source any more.
