### ISSUE TITLE
为什么单端口多用户情况下，流量统计都是0？

### ISSUE THREAD

**Issue by shyboy0415** [FranzKafkaYu/x-ui#478]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

为什么单端口多用户情况下，流量统计都是0？有什么限制吗？
![image](https://github.com/FranzKafkaYu/x-ui/assets/61101714/223ecb7d-6dde-46e8-b7c4-cf3bab0b8e30)
端口下的统计是正常的
![image](https://github.com/FranzKafkaYu/x-ui/assets/61101714/9d0f705d-a21b-40e9-b2cf-b8135340b861)

### Version of x-ui

<details>
[INF] 当前面板信息[current panel info]:
面板版本[version]: 0.3.4.4:20230717
</details>

### x-ui log or xray log

<details>
-- Logs begin at Wed 2023-08-02 12:36:44 EDT. --
Aug 02 20:43:31 racknerd-6567e1 x-ui[30352]: ClearTrafficByPort,port id 2
Aug 02 20:43:34 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:43:34 INFO - We got 2 members in client
Aug 02 20:43:34 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:43:34 INFO - We got 1 members in client
Aug 02 20:43:34 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:43:34 INFO - We got 1 members in client
Aug 02 20:43:34 racknerd-6567e1 x-ui[30352]: ClearTrafficByPort,port id 3
Aug 02 20:43:44 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:43:44 INFO - We got 2 members in client
Aug 02 20:43:44 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:43:44 INFO - We got 1 members in client
Aug 02 20:50:54 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:50:54 INFO - We got 2 members in client
Aug 02 20:50:54 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:50:54 INFO - We got 1 members in client
Aug 02 20:50:54 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:50:54 INFO - We got 1 members in client
Aug 02 20:51:24 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:24 INFO - We got 2 members in client
Aug 02 20:51:24 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:24 INFO - We got 1 members in client
Aug 02 20:51:32 racknerd-6567e1 x-ui[30352]: ClearTrafficByPort,port id 3
Aug 02 20:51:34 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:34 INFO - We got 2 members in client
Aug 02 20:51:34 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:34 INFO - We got 1 members in client
Aug 02 20:51:34 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:34 INFO - We got 1 members in client
Aug 02 20:51:49 racknerd-6567e1 x-ui[30352]: ClearTrafficByPort,port id 2
Aug 02 20:51:54 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:54 INFO - We got 2 members in client
Aug 02 20:51:54 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:54 INFO - We got 1 members in client
Aug 02 20:51:54 racknerd-6567e1 x-ui[30352]: 2023/08/02 20:51:54 INFO - We got 1 members in client
Aug 02 21:07:24 racknerd-6567e1 x-ui[30352]: 2023/08/02 21:07:24 INFO - We got 1 members in client
Aug 02 21:07:24 racknerd-6567e1 x-ui[30352]: 2023/08/02 21:07:24 INFO - We got 1 members in client
Aug 02 21:07:24 racknerd-6567e1 x-ui[30352]: 2023/08/02 21:07:24 INFO - We got 1 members in client
</details>

**Comment by FranzKafkaYu** [comment]
请检查配置模板的设置，开启单个用户的流量统计需要配置policy，如下所示：  
```  
 "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },  
```  
完整配置参考：  
```
{
"log": {
    "access": "/usr/local/x-ui/bin/access.log",
    "error": "/usr/local/x-ui/bin/error.log",
    "loglevel": " debug",
    "dnsLog": true
 },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
 "dns": {
      "servers": [
      "127.0.0.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blocked"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockedByIp"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockedByDomain"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "hybrid",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "blockedByIp",
        "type": "field"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn",
          "geosite:tld-cn",
          "geosite:private",
          "geosite:category-games@cn"
        ],
        "outboundTag": "blockedByDomain"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}  
```

**Comment by shyboy0415** [comment]
谢谢
