### ISSUE TITLE
使用一段时间后会断网失去连接

### ISSUE THREAD

**Issue by Idealisten** [FranzKafkaYu/x-ui#479]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

机器是AWS的Debian10，使用XUI的节点在观看油管一段时间（大约1小时）后节点会断连，有时候10分钟后会自动恢复，有时一直不会自动恢复，手动重启后恢复正常，非GFW端口屏蔽

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
该问题通常跟你的协议配置、服务器与本地网络状态相关，与x-ui自身无关。
