### ISSUE TITLE
X-UI的xray服务已经停止，入站规则已经非启用状态，但是分享出去的节点还能上网走流量

### ISSUE THREAD

**Issue by MartinGuo** [FranzKafkaYu/x-ui#481]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

X-UI的xray服务已经停止，入站规则已经非启用状态，但是分享出去的节点还能上网走流量

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```
面板版本[version]: 0.3.4.4:20230717
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
web server run http on [::]:10001
 x-ui[27399]: 2023/08/12 14:53:42 INFO - Wait 2 seconds for telegram bot ready
0 x-ui[27399]: SSHLogin[2023-08-12 14:25:00] early than XUI start[2023-08-12 14:53:42],don't notify
 x-ui[27399]: 2023/08/12 14:53:45 INFO - get xray version from database: v1.8.3
 x-ui[27399]: 2023/08/12 14:53:45 INFO - need to switch xray version from v1.7.5 to:v1.8.3
 x-ui[27399]: 2023/08/12 14:53:46 INFO - RecordXrayVersion: v1.8.3
</details>

**Comment by FranzKafkaYu** [comment]
无法复现该问题
