### ISSUE TITLE
shadowrocket 只支持vmess咋回事

### ISSUE THREAD

**Issue by shhdz** [FranzKafkaYu/x-ui#483]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

shadowrocket 只支持vmess咋回事，用其它协议上不了，

### Version of x-ui

<details>

```console
$ x-ui version最新版
# Paste output here
```

</details>

### x-ui log or xray log

<details>
没有
```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@shhdz 相同的服务端配置，可以尝试使用不同的客户端，如Android v2rayNG,Win v2rayN,如这些客户端也无法使用，则检查服务端配置；如这些客户端可以使用，一般属于客户端适配问题，请咨询客户端开发者
