### ISSUE TITLE
最新0.3.4.4版 ，在 chrome 115版，点 添加入站 流量重置 批量导出 无反应

### ISSUE THREAD

**Issue by gn73679** [FranzKafkaYu/x-ui#485]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/FranzKafkaYu/x-ui/assets/70200185/e42da0d2-c026-4473-86bb-6164b353b24a)

### Version of x-ui

<details>

```console
$ x-ui version
3.4.4
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
浏览器语言请设置为简体中文。

**Comment by gn73679** [comment]
> 浏览器语言请设置为简体中文。

感谢，改了有效
