### ISSUE TITLE
求助，面板安装成功，后台显示也在运行。但是打不开面板。

### ISSUE THREAD

**Issue by DSKing377** [FranzKafkaYu/x-ui#487]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

面板安装成功，后台显示也在运行。但是打不开面板。已经更换过Debian10，Ubuntu20.04系统，都是一样的情况。
![2023-08-25_084817](https://github.com/FranzKafkaYu/x-ui/assets/25481384/de18229b-4ddf-497e-b443-3930d8bda593)
![2023-08-25_084923](https://github.com/FranzKafkaYu/x-ui/assets/25481384/550251a5-94ab-4bfd-a2fc-8db525d84fb0)
![2023-08-25_085031](https://github.com/FranzKafkaYu/x-ui/assets/25481384/e4673486-15a6-4a92-9063-1f7f08d82351)
![2023-08-25_085409](https://github.com/FranzKafkaYu/x-ui/assets/25481384/13fa03c3-3591-4c29-8d80-cf4b1d42a6a6)

### Version of x-ui

请输入选择 [0-17],查看面板登录信息请输入数字7:7
[INF] 当前面板信息[current panel info]:
面板版本[version]: 0.3.4.4:20230717
用户名[username]: 
密码[userpasswd]: 
监听端口[port]: 10000
根路径[basePath]: /

### x-ui log or xray log

-- Logs begin at Fri 2023-08-25 05:43:22 CST. --
Aug 25 08:46:29 SlimySuperior-VM x-ui[18243]: get signal: terminated
Aug 25 08:46:29 SlimySuperior-VM systemd[1]: Stopping x-ui Service...
Aug 25 08:46:29 SlimySuperior-VM systemd[1]: x-ui.service: Succeeded.
Aug 25 08:46:29 SlimySuperior-VM systemd[1]: Stopped x-ui Service.
Aug 25 08:46:29 SlimySuperior-VM systemd[1]: Started x-ui Service.
Aug 25 08:46:29 SlimySuperior-VM x-ui[25982]: 2023/08/25 08:46:29 x-ui 0.3.4.4:20230717
Aug 25 08:46:29 SlimySuperior-VM x-ui[25982]: 2023/08/25 08:46:29 INFO - web server run http on [::]:10000
Aug 25 08:46:29 SlimySuperior-VM x-ui[25982]: IptablesCreateOwnChain create failed,error Info exit status 1
Aug 25 08:46:29 SlimySuperior-VM x-ui[25982]: 2023/08/25 08:46:29 WARNING - start xray warnging,create x-ui own chain failed
Aug 25 08:46:29 SlimySuperior-VM x-ui[25982]: 2023/08/25 08:46:29 INFO - Wait 2 seconds for telegram bot ready
Aug 25 08:46:31 SlimySuperior-VM x-ui[25982]: SSHLogin[2023-08-25 08:45:00] early than XUI start[2023-08-25 08:46:29],don't notify

**Comment by FranzKafkaYu** [comment]
@DSKing377 开启代理了么，如开启了代理可以先行关闭，或者更换其他代理

**Comment by DSKing377** [comment]
没有走代理，IP没有被墙

**Comment by FranzKafkaYu** [comment]
> 没有走代理，IP没有被墙

浏览器报错信息是SSL相关问题，面板是否配置了证书，是否尝试过清除浏览器缓存

**Comment by DSKing377** [comment]
我刚试了一下，我的浏览器清除缓存也还是打不开，手机也打不开，但是把链接发微信聊天上可以打开。试了下别人的电脑，有的能打开，有的打不开。。。。不知道问题在哪，现在已经配置了证书。
