### ISSUE TITLE
关于添加禁止ip访问功能的请求

### ISSUE THREAD

**Issue by 7tianv** [FranzKafkaYu/x-ui#49]
利用大佬的脚本搭建好节点之后分享给其他人用，经常有人试图通过服务器破解我的后台密码。请求大佬能够添加禁止特定IP访问的功能

**Comment by Fangliding** [comment]
@7tianv 直接加个路径让别人找不到你的面板就行了

**Comment by FranzKafkaYu** [comment]
> 利用大佬的脚本搭建好节点之后分享给其他人用，经常有人试图通过服务器破解我的后台密码。请求大佬能够添加禁止特定IP访问的功能

请参照WIKI说明进行相应设置，可以保证面板使用安全：https://github.com/FranzKafkaYu/x-ui/wiki/%E5%AE%89%E5%85%A8%E7%99%BB%E5%BD%95
