### ISSUE TITLE
0.3.4.4 繁體中文語言 點擊 "添加入站" "二維碼" "編輯"都沒有反應

### ISSUE THREAD

**Issue by jasonwu1994** [FranzKafkaYu/x-ui#490]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

0.3.4.4繁體中文語言 點擊 "添加入站" "二維碼" "編輯"都沒有反應(不會跳出框框)
使用簡體中文語言就可以

### Version of x-ui

<details>

```console
$ x-ui version
0.3.4.4
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
已知问题，对繁体中文的支持并不完善，请尽量使用简体中文。
