### ISSUE TITLE
面板设置TG通知无法保存

### ISSUE THREAD

**Issue by sklf** [FranzKafkaYu/x-ui#5]
腾讯轻量云，试过ubuntu18.04.1和debian10.2，按照脚本自动安装后，进入面板设置tg通知无法保存设置，一直显示loading转圈，设置面板证书配置时也是loading转圈，刷新后设置项为空。已经尝试更换浏览器和清除缓存，无法解决。

**Comment by FranzKafkaYu** [comment]
可否提供一下xui运行log，帮助我更好地诊断现在的问题。

此外，由于目前默认安装的版本为最新版本(0.3.3.9)，为了兼容老的系统GLIBC版本过于老旧而使用静态链接，可能会导致数据库异常。

鉴于此，建议你还可以通过以下几个步骤进行操作:
1.ldd --version查看当前系统的glibc版本是否>2.28
2.如>2.28，可以卸载掉当前面板，重新通过bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh 0.3.3.8)安装0.3.3.8版本，在清除cookie与浏览器缓存后，再试试该版本是否可以正常工作。

**Comment by sklf** [comment]
0.3.3.9 运行日志：
`Apr 28 15:41:15 VM-0-12-debian x-ui[1857]: 2022/04/28 15:41:15 INFO - sklf login success,Ip Address:*.*.*.*
Apr 28 15:41:15 VM-0-12-debian x-ui[1857]: 2022/04/28 15:41:15 INFO - user 1 login success
Apr 28 15:42:18 VM-0-12-debian x-ui[1857]: 2022/04/28 15:42:18 INFO - sklf login success,Ip Address:*.*.*.*
Apr 28 15:42:18 VM-0-12-debian x-ui[1857]: 2022/04/28 15:42:18 INFO - user 1 login success
Apr 28 15:44:04 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:04 INFO - sklf login success,Ip Address:*.*.*.*
Apr 28 15:44:04 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:04 INFO - user 1 login success
Apr 28 15:44:13 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:13 INFO - sklf login success,Ip Address:*.*.*.*
Apr 28 15:44:13 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:13 INFO - user 1 login success
Apr 28 15:45:15 VM-0-12-debian x-ui[1857]: 2022/04/28 15:45:15 [sessions] ERROR! securecookie: the value is not valid
Apr 28 15:53:41 VM-0-12-debian x-ui[1857]: 2022/04/28 15:53:41 WARNING - 修改设置失败:  read tcp 10.0.0.12:443->*.*.*.*:23865: read: connection reset by peer
Apr 28 15:56:08 VM-0-12-debian x-ui[1857]: 2022/04/28 15:56:08 WARNING - 修改设置失败:  read tcp 10.0.0.12:443->*.*.*.*:15343: read: connection reset by peer
Apr 28 16:01:45 VM-0-12-debian x-ui[1857]: 2022/04/28 16:01:45 WARNING - 修改设置失败:  read tcp 10.0.0.12:443->*.*.*.*:2779: read: connection reset by peer
Apr 28 16:04:41 VM-0-12-debian x-ui[1857]: 2022/04/28 16:04:41 WARNING - 修改设置失败:  read tcp 10.0.0.12:443->*.*.*.*: read: connection reset by peer
`
glibc版本为2.28
回退到 0.3.3.8 后出现无法登录面板的情况，输入密码后显示“登录成功”然后又回到输入密码界面，此时后台log有一句：
`tgbot not found`

再次卸载重装0.3.3.9 后问题似乎解决，可以正常设置tg 通知，原因未知

**Comment by FranzKafkaYu** [comment]
> 0.3.3.9 运行日志： `Apr 28 15:41:15 VM-0-12-debian x-ui[1857]: 2022/04/28 15:41:15 INFO - sklf login success,Ip Address:*.*.*.* Apr 28 15:41:15 VM-0-12-debian x-ui[1857]: 2022/04/28 15:41:15 INFO - user 1 login success Apr 28 15:42:18 VM-0-12-debian x-ui[1857]: 2022/04/28 15:42:18 INFO - sklf login success,Ip Address:*.*.*.* Apr 28 15:42:18 VM-0-12-debian x-ui[1857]: 2022/04/28 15:42:18 INFO - user 1 login success Apr 28 15:44:04 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:04 INFO - sklf login success,Ip Address:*.*.*.* Apr 28 15:44:04 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:04 INFO - user 1 login success Apr 28 15:44:13 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:13 INFO - sklf login success,Ip Address:*.*.*.* Apr 28 15:44:13 VM-0-12-debian x-ui[1857]: 2022/04/28 15:44:13 INFO - user 1 login success Apr 28 15:45:15 VM-0-12-debian x-ui[1857]: 2022/04/28 15:45:15 [sessions] ERROR! securecookie: the value is not valid Apr 28 15:53:41 VM-0-12-debian x-ui[1857]: 2022/04/28 15:53:41 WARNING - 修改设置失败: read tcp 10.0.0.12:443->*.*.*.*:23865: read: connection reset by peer Apr 28 15:56:08 VM-0-12-debian x-ui[1857]: 2022/04/28 15:56:08 WARNING - 修改设置失败: read tcp 10.0.0.12:443->*.*.*.*:15343: read: connection reset by peer Apr 28 16:01:45 VM-0-12-debian x-ui[1857]: 2022/04/28 16:01:45 WARNING - 修改设置失败: read tcp 10.0.0.12:443->*.*.*.*:2779: read: connection reset by peer Apr 28 16:04:41 VM-0-12-debian x-ui[1857]: 2022/04/28 16:04:41 WARNING - 修改设置失败: read tcp 10.0.0.12:443->*.*.*.*: read: connection reset by peer ` glibc版本为2.28 回退到 0.3.3.8 后出现无法登录面板的情况，输入密码后显示“登录成功”然后又回到输入密码界面，此时后台log有一句： `tgbot not found`
> 
> 再次卸载重装0.3.3.9 后问题似乎解决，可以正常设置tg 通知，原因未知

tgbot not found不会影响面板的正常使用，只是会影响tg的消息推送。0.3.3.8版本加强了会话管理，在开启cookie的情况下过期的cookie会导致重复回到登录界面，需要清除cookie后再登录，0.3.3.9已经去掉这个内容。综合来看，你的问题应该还是出在浏览器上，cookie清除与浏览器缓存清除是很重要的一个细节，可能是这里某个环节出现问题。不过既然重装已经已经可以使用，暂时关闭该issue
