### ISSUE TITLE
迁移服务器的时候数据库文件是哪个，以及流量是否可以一键清空所有节点的流量呢，就像v2-ui一样

### ISSUE THREAD

**Issue by Hikpy** [FranzKafkaYu/x-ui#50]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

迁移服务器的时候数据库文件是哪个，就是我应该复制哪个文件?
以及是否可以一键清空所有节点的流量呢，就像v2-ui一样或者定期清空所有节点的流量

**Comment by FranzKafkaYu** [comment]
> 任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug
> 
> 如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助
> 
> 提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
> 
> 迁移服务器的时候数据库文件是哪个，就是我应该复制哪个文件? 以及是否可以一键清空所有节点的流量呢，就像v2-ui一样或者定期清空所有节点的流量

关于数据迁移请看WIKI文档常见问题，支持一键清空所有流量。
