### ISSUE TITLE
面板点击添加入站无反应

### ISSUE THREAD

**Issue by RomanovCaesar** [FranzKafkaYu/x-ui#507]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

如题，服务器装了x-ui后，过了半个月，现在在面板上点击添加入站没有反应

https://github.com/FranzKafkaYu/x-ui/assets/88546123/50910712-2aee-4618-a13a-5075641796d1

### Version of x-ui

x-ui version 0.3.4.4

### x-ui log or xray log

-- Logs begin at Fri 2023-09-22 12:36:19 UTC. --
Sep 22 12:38:56 vm821189.akkocloud.com systemd[1]: Started x-ui Service.
Sep 22 12:38:56 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:38:56 x-ui 0.3.4.4:20230717
Sep 22 12:38:56 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:38:56 INFO - web server run http on [::]:2005
Sep 22 12:38:56 vm821189.akkocloud.com x-ui[1063]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 22 12:38:56 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:38:56 WARNING - start xray warnging,create x-ui own chain failed
Sep 22 12:38:56 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:38:56 INFO - Wait 2 seconds for telegram bot ready
Sep 22 12:38:58 vm821189.akkocloud.com x-ui[1063]: SSHLogin[2023-09-22 12:38:00] early than XUI start[2023-09-22 12:38:56],don't notify
Sep 22 12:39:11 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:39:11 [sessions] ERROR! securecookie: the value is not valid
Sep 22 12:39:15 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:39:15 INFO - caesar311 login success,Ip Address:185.217.109.188
Sep 22 12:39:15 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:39:15 [sessions] ERROR! securecookie: the value is not valid
Sep 22 12:39:15 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:39:15 INFO - user 1 login success
Sep 22 12:40:03 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:40:03 WARNING - stop server err: multierr: close tcp [::]:2005: use of closed network connection |
Sep 22 12:40:03 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:40:03 INFO - web server run http on [::]:2005
Sep 22 12:40:03 vm821189.akkocloud.com x-ui[1063]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 22 12:40:03 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:40:03 WARNING - start xray warnging,create x-ui own chain failed
Sep 22 12:40:03 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:40:03 INFO - Wait 2 seconds for telegram bot ready
Sep 22 12:41:01 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:41:01 WARNING - stop server err: multierr: close tcp [::]:2005: use of closed network connection |
Sep 22 12:41:01 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:41:01 INFO - web server run http on [::]:2005
Sep 22 12:41:01 vm821189.akkocloud.com x-ui[1063]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 22 12:41:01 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:41:01 WARNING - start xray warnging,create x-ui own chain failed
Sep 22 12:41:01 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:41:01 INFO - Wait 2 seconds for telegram bot ready
Sep 22 12:44:58 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:44:58 [sessions] ERROR! securecookie: the value is not valid
Sep 22 12:44:58 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:44:58 [sessions] ERROR! securecookie: the value is not valid
Sep 22 12:45:00 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:45:00 INFO - caesar311 login success,Ip Address:223.104.67.96
Sep 22 12:45:00 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:45:00 [sessions] ERROR! securecookie: the value is not valid
Sep 22 12:45:00 vm821189.akkocloud.com x-ui[1063]: 2023/09/22 12:45:00 INFO - user 1 login success
-- Reboot --
Sep 22 12:46:27 vm821189.akkocloud.com systemd[1]: Started x-ui Service.
Sep 22 12:46:27 vm821189.akkocloud.com x-ui[409]: 2023/09/22 12:46:27 x-ui 0.3.4.4:20230717
Sep 22 12:46:27 vm821189.akkocloud.com x-ui[409]: 2023/09/22 12:46:27 INFO - web server run http on [::]:2005
Sep 22 12:46:27 vm821189.akkocloud.com x-ui[409]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 22 12:46:27 vm821189.akkocloud.com x-ui[409]: 2023/09/22 12:46:27 WARNING - start xray warnging,create x-ui own chain failed
Sep 22 12:46:29 vm821189.akkocloud.com x-ui[409]: 2023/09/22 12:46:29 INFO - Wait 2 seconds for telegram bot ready

**Comment by RomanovCaesar** [comment]
原版就没有这个问题

**Comment by FranzKafkaYu** [comment]
@RomanovCaesar 浏览器语言请选择简体中文

**Comment by RomanovCaesar** [comment]
好我试试

**Comment by LiMoon** [comment]
> @RomanovCaesar 浏览器语言请选择简体中文

可以為瀏覽器語言繁體中文支援嗎?
原版x-ui沒這問題
