### ISSUE TITLE
请问是不是不支持v4v6分别代理

### ISSUE THREAD

**Issue by token361** [FranzKafkaYu/x-ui#508]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

请问是不是不支持v4v6分别代理 我目前新建入站是只监听v4地址  再新建入站监听v6地址能成功但是无法导入客户端 提示无效的url配置 请问这种情况该怎么做 改回v4地址就行了

### Version of x-ui

最新

### x-ui log or xray log

Sep 23 06:18:14 s7278 systemd[1]: Started x-ui Service.
Sep 23 06:18:14 s7278 x-ui[795]: 2023/09/23 06:18:14 x-ui 0.3.4.4:20230717
Sep 23 06:18:14 s7278 x-ui[795]: 2023/09/23 06:18:14 INFO - web server run http on [::]:80
Sep 23 06:18:14 s7278 x-ui[795]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 23 06:18:14 s7278 x-ui[795]: 2023/09/23 06:18:14 WARNING - start xray warnging,create x-ui own chain failed
Sep 23 06:18:14 s7278 x-ui[795]: 2023/09/23 06:18:14 INFO - Wait 2 seconds for telegram bot ready
Sep 23 06:18:16 s7278 x-ui[795]: SSHLogin[2023-09-23 06:14:00] early than XUI start[2023-09-23 06:18:14],don't notify
Sep 23 06:18:47 s7278 x-ui[795]: get signal: terminated
Sep 23 06:18:47 s7278 systemd[1]: Stopping x-ui Service...
Sep 23 06:18:48 s7278 systemd[1]: x-ui.service: Deactivated successfully.
Sep 23 06:18:48 s7278 systemd[1]: Stopped x-ui Service.
Sep 23 06:18:48 s7278 systemd[1]: Started x-ui Service.
Sep 23 06:18:48 s7278 x-ui[979]: 2023/09/23 06:18:48 x-ui 0.3.4.4:20230717
Sep 23 06:18:48 s7278 x-ui[979]: 2023/09/23 06:18:48 INFO - web server run http on [::]:80
Sep 23 06:18:48 s7278 x-ui[979]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 23 06:18:48 s7278 x-ui[979]: 2023/09/23 06:18:48 WARNING - start xray warnging,create x-ui own chain failed
Sep 23 06:18:48 s7278 x-ui[979]: 2023/09/23 06:18:48 INFO - Wait 2 seconds for telegram bot ready
Sep 23 06:18:50 s7278 x-ui[979]: SSHLogin[2023-09-23 06:14:00] early than XUI start[2023-09-23 06:18:48],don't notify
Sep 23 06:20:25 s7278 x-ui[979]: 2023/09/23 06:20:25 [sessions] ERROR! securecookie: the value is not valid
Sep 23 06:21:31 s7278 x-ui[979]: 2023/09/23 06:21:31 INFO - haotian361 login success,Ip Address:121.60.59.175
Sep 23 06:21:31 s7278 x-ui[979]: 2023/09/23 06:21:31 INFO - user 1 login success
Sep 23 06:21:49 s7278 x-ui[979]: 2023/09/23 06:21:49 WARNING - stop server err: multierr: close tcp [::]:80: use of closed network connection |
Sep 23 06:21:49 s7278 x-ui[979]: 2023/09/23 06:21:49 INFO - web server run http on [::]:80
Sep 23 06:21:49 s7278 x-ui[979]: IptablesCreateOwnChain create failed,error Info exit status 127
Sep 23 06:21:49 s7278 x-ui[979]: 2023/09/23 06:21:49 WARNING - start xray warnging,create x-ui own chain failed
Sep 23 06:21:49 s7278 x-ui[979]: 2023/09/23 06:21:49 INFO - Wait 2 seconds for telegram bot ready
Sep 23 06:22:09 s7278 x-ui[979]: 2023/09/23 06:22:09 INFO - RecordXrayVersion: v1.8.4
Sep 23 06:24:09 s7278 x-ui[979]: 2023/09/23 06:24:09 INFO - We got 9 members in client
Sep 23 06:46:14 s7278 x-ui[979]: ClearTrafficByPort,port id 1
Sep 23 06:46:19 s7278 x-ui[979]: 2023/09/23 06:46:19 INFO - We got 9 members in client
Sep 23 06:46:59 s7278 x-ui[979]: 2023/09/23 06:46:59 INFO - We got 9 members in client
Sep 23 06:47:29 s7278 x-ui[979]: 2023/09/23 06:47:29 INFO - We got 9 members in client
Sep 23 06:47:54 s7278 x-ui[979]: ClearTrafficByPort,port id 1
Sep 23 06:47:59 s7278 x-ui[979]: 2023/09/23 06:47:59 INFO - We got 9 members in client
Sep 23 06:50:53 s7278 x-ui[979]: ClearTrafficByPort,port id 1
Sep 23 06:50:59 s7278 x-ui[979]: 2023/09/23 06:50:59 INFO - We got 9 members in client
Sep 23 06:51:59 s7278 x-ui[979]: 2023/09/23 06:51:59 INFO - We got 9 members in client
Sep 23 06:52:29 s7278 x-ui[979]: 2023/09/23 06:52:29 INFO - We got 9 members in client
Sep 23 06:52:38 s7278 x-ui[979]: ClearTrafficByPort,port id 1
Sep 23 06:52:39 s7278 x-ui[979]: 2023/09/23 06:52:39 INFO - We got 9 members in client
Sep 23 06:55:19 s7278 x-ui[979]: 2023/09/23 06:55:19 INFO - We got 9 members in client
Sep 23 06:55:19 s7278 x-ui[979]: 2023/09/23 06:55:19 INFO - We got 1 members in client
Sep 23 06:57:01 s7278 x-ui[979]: ClearTrafficByPort,port id 2
Sep 23 06:57:09 s7278 x-ui[979]: 2023/09/23 06:57:09 INFO - We got 9 members in client
Sep 23 06:57:09 s7278 x-ui[979]: 2023/09/23 06:57:09 INFO - We got 1 members in client
Sep 23 06:57:36 s7278 x-ui[979]: ClearTrafficByPort,port id 2
Sep 23 06:57:39 s7278 x-ui[979]: 2023/09/23 06:57:39 INFO - We got 9 members in client
Sep 23 06:57:39 s7278 x-ui[979]: 2023/09/23 06:57:39 INFO - We got 1 members in client
Sep 23 06:58:14 s7278 x-ui[979]: ClearTrafficByPort,port id 2
Sep 23 06:58:19 s7278 x-ui[979]: 2023/09/23 06:58:19 INFO - We got 9 members in client
Sep 23 06:58:19 s7278 x-ui[979]: 2023/09/23 06:58:19 INFO - We got 1 members in client

**Comment by FranzKafkaYu** [comment]
监听地址请留空，客户端可以将地址填为v4或v6地址皆可，如果使用域名，则分别解析A/AAAA类型地址，使用域名链接也可
