### ISSUE TITLE
How to donate to this project?

### ISSUE THREAD

**Issue by leomoon** [FranzKafkaYu/x-ui#509]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Me and I'm sure many other people want to support your work by donating.

Please provide a USDT address or a PayPal link for donation.

Thank you.

### Version of x-ui

<details>

```console
# paste log here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by wxj1996** [comment]
1. 创建节点时，能否新增，节点ip\域名输入框，变成可以自定义的，因为节点搭建完成后，基本会套转发，会用其他的域名，不然每次都得去v2里面改一下域名
2. 能否开发一键订阅功能，用户可以通过url 拉取节点。
$ x-ui version
# Paste output here


# paste log here
