### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by stealth-sr** [FranzKafkaYu/x-ui#51]
can you explain why this? I just installed

![Screenshot_2022-07-24-12-40-50-05_0a156e521caef1694fb53a7dad489d44](https://user-images.githubusercontent.com/109278456/180634045-e4a20d8c-1ac4-4788-a1b4-8fc4b428c4e7.jpg)

**Comment by FranzKafkaYu** [comment]
> can you explain why this? I just installed
> 
> ![Screenshot_2022-07-24-12-40-50-05_0a156e521caef1694fb53a7dad489d44](https://user-images.githubusercontent.com/109278456/180634045-e4a20d8c-1ac4-4788-a1b4-8fc4b428c4e7.jpg)

**plz see my release note**
![image](https://user-images.githubusercontent.com/38254177/180634462-79df8379-1336-4ed2-803f-8c1b24cbb850.png)
