### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by xiangchu95** [FranzKafkaYu/x-ui#512]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![image](https://github.com/FranzKafkaYu/x-ui/assets/110237853/16b74f5f-ecb2-4563-b984-9a0bafe6ec9e)

### Version of x-ui

enwaiax/x-ui:alpha-zh 最新镜像

### x-ui log or xray log

[+] Running 1/1
 ✔ Container xui-xui-1  Created                                                                                                                                                                                                 0.3s 
Attaching to xui-xui-1
xui-xui-1  | 2023/09/28 10:53:00 x-ui 0.3.4.4:20230717
xui-xui-1  | 2023/09/28 10:53:01 INFO - web server run http on [::]:54321
xui-xui-1  | 2023/09/28 10:53:01 WARNING - start xray warnging,create x-ui own chain failed
xui-xui-1  | IptablesCreateOwnChain create failed,error Info exit status 127
xui-xui-1  | 2023/09/28 10:53:01 INFO - Wait 2 seconds for telegram bot ready
xui-xui-1  | 2023/09/28 10:53:10 [sessions] ERROR! securecookie: the value is not valid
xui-xui-1  | 2023/09/28 10:53:21 INFO - admin login success,Ip Address:******
xui-xui-1  | 2023/09/28 10:53:21 [sessions] ERROR! securecookie: the value is not valid
xui-xui-1  | 2023/09/28 10:53:21 INFO - user 1 login success
xui-xui-1  | 2023/09/28 10:53:29 WARNING - 停止xray服务失败:  xray is not running
xui-xui-1  | 2023/09/28 10:53:39 INFO - RecordXrayVersion: v1.8.1
xui-xui-1  | 2023/09/28 10:54:04 WARNING - stop server err: multierr: close tcp [::]:54321: use of closed network connection | 
xui-xui-1  | 2023/09/28 10:54:04 INFO - web server run http on [::]:54321
xui-xui-1  | 2023/09/28 10:54:04 WARNING - start xray warnging,create x-ui own chain failed
xui-xui-1  | IptablesCreateOwnChain create failed,error Info exit status 127
xui-xui-1  | 2023/09/28 10:54:04 INFO - Wait 2 seconds for telegram bot ready
xui-xui-1  | 2023/09/28 10:59:37 WARNING - stop server err: multierr: close tcp [::]:54321: use of closed network connection | 
xui-xui-1  | 2023/09/28 10:59:37 INFO - web server run http on [::]:54321
xui-xui-1  | 2023/09/28 10:59:37 WARNING - start xray warnging,create x-ui own chain failed
xui-xui-1  | IptablesCreateOwnChain create failed,error Info exit status 127
xui-xui-1  | 2023/09/28 10:59:37 INFO - Wait 2 seconds for telegram bot ready
xui-xui-1  | 2023/09/28 10:59:48 INFO - user 1 logout
xui-xui-1  | 2023/09/28 10:59:52 INFO - xiangchu95 login success,Ip Address:**************
xui-xui-1  | 2023/09/28 10:59:52 INFO - user 1 login success
xui-xui-1  | panic: runtime error: index out of range [0] with length 0
xui-xui-1  | 
xui-xui-1  | goroutine 1770 [running]:
xui-xui-1  | x-ui/web/job.(*StatsNotifyJob).GetCpuUsage(0xf4b150?)
xui-xui-1  |    x-ui/web/job/stats_notify_job.go:563 +0x593
xui-xui-1  | x-ui/web/job.(*StatsNotifyJob).NewCpuStatusMonitorNotify(0xc000455f86)
xui-xui-1  |    x-ui/web/job/stats_notify_job.go:130 +0x2ad
xui-xui-1  | x-ui/web.(*Server).startTask.func7()
xui-xui-1  |    x-ui/web/web.go:326 +0x25
xui-xui-1  | github.com/robfig/cron/v3.FuncJob.Run(0x0?)
xui-xui-1  |    github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
xui-xui-1  | github.com/robfig/cron/v3.(*Cron).startJob.func1()
xui-xui-1  |    github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
xui-xui-1  | created by github.com/robfig/cron/v3.(*Cron).startJob
xui-xui-1  |    github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
xui-xui-1  | 
xui-xui-1 exited with code 0

**Comment by FranzKafkaYu** [comment]
抱歉，docker相关支持不在本项目考虑范围之内。
