### ISSUE TITLE
无法显示登录界面

### ISSUE THREAD

**Issue by coldrook** [FranzKafkaYu/x-ui#513]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

无法显示登录界面，一直转圈无显示

日志仅显示
x-ui[522]: 20XX/XX/XX XX:XX:XX INFO - Wait 2 seconds for telegram bot read
然后无其他显示
x-ui status
     Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; preset: enabled)
     Active: active (running) since Sat 20XX-XX-XX  XX:XX:XX PDT; 9min ago

### Version of x-ui

<details>

0.3.4.4:20230717

</details>

### x-ui log or xray log

<details>

日志仅显示
x-ui[522]: 20XX/XX/XX XX:XX:XX INFO - Wait 2 seconds for telegram bot read
然后无其他显示
x-ui status
     Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; preset: enabled)
     Active: active (running) since Sat 20XX-XX-XX  XX:XX:XX PDT; 9min ago

</details>

**Comment by FranzKafkaYu** [comment]
通常为浏览器网络环境问题，可以尝试更换浏览器或者关闭代理进行登录。

**Comment by coldrook** [comment]
排查原因发现，不能在安装x-ui前使用封锁BT&spam端口脚本，解除封锁后，可以顺利登录
再次使用封锁端口脚本，无影响
