### ISSUE TITLE
Multi QR code for multi user

### ISSUE THREAD

**Issue by ciph3rblackhat** [FranzKafkaYu/x-ui#514]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I have an issue with the last version.
I could not find multi QR code for multi user when I add multiple user (for instance 3 users).
Well,I have a question.I need multi qr code in 1 inbound user.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@ciph3rblackhat U can find each user's QR code in check

**Comment by itsmiura** [comment]
Hi,
I have an issue with multi user in new version, 
 How many users can be built in one inbuand?
I can only make 10 per inbuand.

**Comment by FranzKafkaYu** [comment]
> How many users can be built in one inbuand?

Only 10.If you would like to lift the restriction, please email me(loveme@duck.com) and explain your reason.
