### ISSUE TITLE
一键申请SSL证书(acme申请)失败

### ISSUE THREAD

**Issue by fzhw88** [FranzKafkaYu/x-ui#517]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

通过
bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh)
命令安装x-ui，且反复安装都不能解决问题。

  16. 一键申请SSL证书(acme申请)，无论选1还是2，都遇到
  /root/.acme.sh/acme.sh: No such file or directory
  报错，应该是acme.sh脚本没有下载，但原因未知。

hosthatch的vps，系统是Debian 12

另有一奇怪现象，用我的瓦工代理访问面板会遇到400错误，关掉代理国内直连才正常，请问这是面板的默认设置吗？

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```
0.3.4.4:20230717
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
Oct 12 15:46:33 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 15:46:33 debian x-ui[662]: 2023/10/12 15:46:33 x-ui 0.3.4.4:20230717
Oct 12 15:46:33 debian x-ui[662]: 2023/10/12 15:46:33 INFO - web server run http on [::]:8080
Oct 12 15:46:33 debian x-ui[662]: 2023/10/12 15:46:33 INFO - Wait 2 seconds for telegram bot ready
Oct 12 15:46:35 debian x-ui[662]: SSHLogin[2023-10-12 15:44:00] early than XUI start[2023-10-12 15:46:33],don't notify
Oct 12 15:58:15 debian x-ui[662]: get signal: terminated
Oct 12 15:58:15 debian systemd[1]: Stopping x-ui.service - x-ui Service...
Oct 12 15:58:15 debian systemd[1]: x-ui.service: Deactivated successfully.
Oct 12 15:58:15 debian systemd[1]: Stopped x-ui.service - x-ui Service.
Oct 12 15:58:15 debian systemd[1]: x-ui.service: Consumed 2.126s CPU time.
Oct 12 15:58:15 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 15:58:16 debian x-ui[2710]: 2023/10/12 15:58:16 x-ui 0.3.4.4:20230717
Oct 12 15:58:16 debian x-ui[2710]: 2023/10/12 15:58:16 INFO - web server run http on [::]:8080
Oct 12 15:58:16 debian x-ui[2710]: 2023/10/12 15:58:16 INFO - Wait 2 seconds for telegram bot ready
Oct 12 15:58:18 debian x-ui[2710]: SSHLogin[2023-10-12 15:44:00] early than XUI start[2023-10-12 15:58:16],don't notify
Oct 12 16:00:00 debian x-ui[2710]: 2023/10/12 16:00:00 INFO - Run InboundTrafficAlert Job...
Oct 12 16:00:00 debian x-ui[2710]: 2023/10/12 16:00:00 INFO - get inboundTrafficNotify is 0
Oct 12 16:00:00 debian x-ui[2710]: 2023/10/12 16:00:00 WARNING - current traffic notify  diff is:0
Oct 12 16:00:00 debian x-ui[2710]: 2023/10/12 16:00:00 INFO - Run InboundExpireNotify Job...
Oct 12 16:00:00 debian x-ui[2710]: 2023/10/12 16:00:00 INFO - get inboundExpireNotify time is 0
Oct 12 16:00:00 debian x-ui[2710]: 2023/10/12 16:00:00 WARNING - current Expire notify time diff is:0
Oct 12 16:05:32 debian x-ui[2710]: get signal: terminated
Oct 12 16:05:32 debian systemd[1]: Stopping x-ui.service - x-ui Service...
Oct 12 16:05:33 debian systemd[1]: x-ui.service: Deactivated successfully.
Oct 12 16:05:33 debian systemd[1]: Stopped x-ui.service - x-ui Service.
Oct 12 16:05:33 debian systemd[1]: x-ui.service: Consumed 1.394s CPU time.
Oct 12 16:05:33 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 16:05:33 debian x-ui[3673]: 2023/10/12 16:05:33 x-ui 0.3.4.4:20230717
Oct 12 16:05:33 debian x-ui[3673]: 2023/10/12 16:05:33 INFO - web server run http on [::]:54321
Oct 12 16:05:33 debian x-ui[3673]: 2023/10/12 16:05:33 INFO - Wait 2 seconds for telegram bot ready
Oct 12 16:05:35 debian x-ui[3673]: SSHLogin[2023-10-12 15:44:00] early than XUI start[2023-10-12 16:05:33],don't notify
Oct 12 16:07:58 debian x-ui[3673]: get signal: terminated
Oct 12 16:07:58 debian systemd[1]: Stopping x-ui.service - x-ui Service...
Oct 12 16:07:59 debian systemd[1]: x-ui.service: Deactivated successfully.
Oct 12 16:07:59 debian systemd[1]: Stopped x-ui.service - x-ui Service.
Oct 12 16:07:59 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 16:07:59 debian x-ui[4103]: 2023/10/12 16:07:59 x-ui 0.3.4.4:20230717
Oct 12 16:07:59 debian x-ui[4103]: 2023/10/12 16:07:59 INFO - web server run http on [::]:8080
Oct 12 16:07:59 debian x-ui[4103]: 2023/10/12 16:07:59 INFO - Wait 2 seconds for telegram bot ready
Oct 12 16:08:01 debian x-ui[4103]: SSHLogin[2023-10-12 15:44:00] early than XUI start[2023-10-12 16:07:59],don't notify
Oct 12 16:10:16 debian x-ui[4103]: 2023/10/12 16:10:16 INFO - fzhw88 login success,Ip Address:113.242.113.185
Oct 12 16:10:16 debian x-ui[4103]: 2023/10/12 16:10:16 INFO - user 1 login success
Oct 12 16:11:29 debian x-ui[4103]: 2023/10/12 16:11:29 WARNING - stop server err: multierr: close tcp [::]:8080: use of closed network connection |
Oct 12 16:11:29 debian x-ui[4103]: 2023/10/12 16:11:29 INFO - web server run http on [::]:8080
Oct 12 16:11:29 debian x-ui[4103]: 2023/10/12 16:11:29 INFO - Wait 2 seconds for telegram bot ready
Oct 12 16:13:06 debian x-ui[4103]: 2023/10/12 16:13:06 WARNING - stop server err: multierr: close tcp [::]:8080: use of closed network connection |
Oct 12 16:13:06 debian x-ui[4103]: 2023/10/12 16:13:06 INFO - web server run http on [::]:8080
Oct 12 16:13:06 debian x-ui[4103]: 2023/10/12 16:13:06 INFO - Wait 2 seconds for telegram bot ready
Oct 12 16:16:16 debian x-ui[4103]: 2023/10/12 16:16:16 INFO - RecordXrayVersion: v1.8.4
Oct 12 16:55:04 debian x-ui[4103]: get signal: terminated
Oct 12 16:55:04 debian systemd[1]: Stopping x-ui.service - x-ui Service...
Oct 12 16:55:05 debian systemd[1]: x-ui.service: Deactivated successfully.
Oct 12 16:55:05 debian systemd[1]: Stopped x-ui.service - x-ui Service.
Oct 12 16:55:05 debian systemd[1]: x-ui.service: Consumed 8.831s CPU time.
Oct 12 16:55:10 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 16:55:10 debian x-ui[10153]: 2023/10/12 16:55:10 x-ui 0.3.4.4:20230717
Oct 12 16:55:10 debian x-ui[10153]: 2023/10/12 16:55:10 INFO - web server run http on [::]:8080
Oct 12 16:55:10 debian x-ui[10153]: 2023/10/12 16:55:10 INFO - Wait 2 seconds for telegram bot ready
Oct 12 16:55:12 debian x-ui[10153]: SSHLogin[2023-10-12 16:42:00] early than XUI start[2023-10-12 16:55:10],don't notify
Oct 12 16:55:12 debian x-ui[10153]: 2023/10/12 16:55:12 INFO - get xray version from database: v1.8.4
Oct 12 16:55:12 debian x-ui[10153]: 2023/10/12 16:55:12 INFO - need to switch xray version from v1.7.5 to:v1.8.4
Oct 12 16:55:13 debian x-ui[10153]: 2023/10/12 16:55:13 INFO - RecordXrayVersion: v1.8.4
Oct 12 16:56:47 debian x-ui[10153]: get signal: terminated
Oct 12 16:56:47 debian systemd[1]: Stopping x-ui.service - x-ui Service...
Oct 12 16:56:48 debian systemd[1]: x-ui.service: Deactivated successfully.
Oct 12 16:56:48 debian systemd[1]: Stopped x-ui.service - x-ui Service.
Oct 12 16:57:07 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 16:57:07 debian x-ui[10550]: 2023/10/12 16:57:07 x-ui 0.3.4.4:20230717
Oct 12 16:57:07 debian x-ui[10550]: 2023/10/12 16:57:07 INFO - web server run http on [::]:8080
Oct 12 16:57:07 debian x-ui[10550]: 2023/10/12 16:57:07 INFO - Wait 2 seconds for telegram bot ready
Oct 12 16:57:09 debian x-ui[10550]: SSHLogin[2023-10-12 16:42:00] early than XUI start[2023-10-12 16:57:07],don't notify
Oct 12 16:57:10 debian x-ui[10550]: 2023/10/12 16:57:10 INFO - get xray version from database: v1.8.4
Oct 12 16:57:10 debian x-ui[10550]: 2023/10/12 16:57:10 INFO - need to switch xray version from v1.7.5 to:v1.8.4
Oct 12 16:57:10 debian x-ui[10550]: 2023/10/12 16:57:10 INFO - RecordXrayVersion: v1.8.4
Oct 12 17:08:30 debian x-ui[10550]: get signal: terminated
Oct 12 17:08:30 debian systemd[1]: Stopping x-ui.service - x-ui Service...
Oct 12 17:08:30 debian systemd[1]: x-ui.service: Deactivated successfully.
Oct 12 17:08:30 debian systemd[1]: Stopped x-ui.service - x-ui Service.
Oct 12 17:08:30 debian systemd[1]: x-ui.service: Consumed 2.482s CPU time.
Oct 12 17:15:37 debian systemd[1]: Started x-ui.service - x-ui Service.
Oct 12 17:15:37 debian x-ui[12281]: 2023/10/12 17:15:37 x-ui 0.3.4.4:20230717
Oct 12 17:15:37 debian x-ui[12281]: 2023/10/12 17:15:37 INFO - web server run http on [::]:8080
Oct 12 17:15:37 debian x-ui[12281]: 2023/10/12 17:15:37 INFO - Wait 2 seconds for telegram bot ready
Oct 12 17:15:39 debian x-ui[12281]: SSHLogin[2023-10-12 17:15:00] early than XUI start[2023-10-12 17:15:37],don't notify
Oct 12 17:15:39 debian x-ui[12281]: 2023/10/12 17:15:39 INFO - get xray version from database: v1.8.4
Oct 12 17:15:39 debian x-ui[12281]: 2023/10/12 17:15:39 INFO - need to switch xray version from v1.7.5 to:v1.8.4
Oct 12 17:15:39 debian x-ui[12281]: 2023/10/12 17:15:39 INFO - RecordXrayVersion: v1.8.4

</details>

**Comment by FranzKafkaYu** [comment]
@fzhw88 acme.sh安装可以尝试手动安装：  
```  
curl https://get.acme.sh | sh
```  
安装完成后可以自行检查：  
``` 
ls -la ~/.acme.sh/ 
```  
至于400错误，一般与代理设置相关，可以尝试使用其他代理;面板自身不会对代理连接做任何限制。
