### ISSUE TITLE
可能造成Linux内存泄漏

### ISSUE THREAD

**Issue by Merlin010** [FranzKafkaYu/x-ui#518]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

面板启动后 kmalloc-4096 会渐进式增长 操作系统版本
![image](https://github.com/FranzKafkaYu/x-ui/assets/48234152/b54eb0f9-a1f9-45e1-ae4a-2262710b01f7)

**Comment by FranzKafkaYu** [comment]
@Merlin010 请使用`top` command观察内存占用有异常的进程，并提供相应截图。

**Comment by Merlin010** [comment]
@FranzKafkaYu top查看内存占用是正常的  我暂时把面板卸载了所以无法提供截图 
前两天的排查情况就是停掉面板kmalloc-4096几乎不会增长 面板启动后会增长 没人提过可能是偶发的吧

**Comment by Merlin010** [comment]
> @Merlin010 请使用`top` command观察内存占用有异常的进程，并提供相应截图。

感谢回复 
top查看内存占用是正常的我暂时把面板卸载了所以无法提供截图

前两天的排查情况就是停掉面板kmalloc-4096几乎不会增长面板启动后会增长没人提过可能是环境问题吧

另外也可能是Xray内核的问题切换了1.8.3和1.7.5都有这个现象

**Comment by FranzKafkaYu** [comment]
@Merlin010 目前暂未收到其他报告，我注意到你的内核还是3.10版本，可能与这有关联；建议使用更新的系统版本。
