### ISSUE TITLE
一进入面板设置就变“404 page not found”

### ISSUE THREAD

**Issue by tmzg0000** [FranzKafkaYu/x-ui#52]
一键安装的。
chrome 浏览器一进入面板设置就变“404 page not found”
重新安装也不能解决。
更换安装路径才能回复正常。但是继续一进入面板设置 浏览器有提示文字飘出，太快没看清接着就变“404 page not found”

**Comment by FranzKafkaYu** [comment]
> 一键安装的。 chrome 浏览器一进入面板设置就变“404 page not found” 重新安装也不能解决。 更换安装路径才能回复正常。但是继续一进入面板设置 浏览器有提示文字飘出，太快没看清接着就变“404 page not found”

![image](https://user-images.githubusercontent.com/38254177/180647690-369fae96-800f-4ff6-8bb1-185055ef9234.png)
