### ISSUE TITLE
add unlimit user in each inbound

### ISSUE THREAD

**Issue by ciph3rblackhat** [FranzKafkaYu/x-ui#521]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello dear developer
Thank you for release the panel to us.
I have a question.
I could add unlimit user in the older version but I'm not able to add more than 10 users in the last version.
How can I add more than 10 users in the last version?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@ciph3rblackhat LOL,it's impossible because I made some restrictions here.

**Comment by ciph3rblackhat** [comment]
Why ? How can I enable the feature or turn off the restrictions on my panel ?
