### ISSUE TITLE
中文化版本，添加入站選單不能彈出

### ISSUE THREAD

**Issue by TharinWONG** [FranzKafkaYu/x-ui#522]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

成功安裝及啟動x-ui面板，登入但為什麼打不開 [添加入站]，沒有跳出選單。
已試過卸載再重新安裝，問題還未解決。切換過 1.8.0 ~ 1.8.4版本 也是一樣無法打開 [添加入站]

最後使用英文版本。開發者能修中文化嗎

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@TharinWONG 浏览器语言请设置为简体中文，繁体中文会存在问题。

**Comment by MoeCinnamo** [comment]
> @TharinWONG 浏览器语言请设置为简体中文，繁体中文会存在问题。

這是一個bug，我的瀏覽器不支援設置為簡體，因此要不在面板上添加語言選擇，否則刪除繁體。
