### ISSUE TITLE
invalid IP addr or iptables Chain not created

### ISSUE THREAD

**Issue by foremtehan** [FranzKafkaYu/x-ui#525]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I'm using the docker version of kafka from this docker repository: https://hub.docker.com/r/enwaiax/x-ui, and my client is nekoray on windows 10.

everything is fine for about 30 minutes, but suddenly the config doesn't work anymore, how can i find the issue? is this `invalid IP addr or iptables Chain not created` normal in log?

### Version of x-ui

<details>

```console
$ docker exec -it x-ui sh
$ x-ui version
except 'run' or 'v2-ui' or 'setting' subcommands

Usage of run:

Usage of v2-ui:
  -db string
        set v2-ui db file path (default "/etc/v2-ui/v2-ui.db")

Usage of setting:
  -enabletgbot
        enable telegram bot notify
  -password string
        set login password
  -port int
        set panel port
  -reset
        reset all settings
  -show
        show current settings
  -tgbotRuntime string
        set telegrame bot cron time
  -tgbotchatid int
        set telegrame bot chat id
  -tgbottoken string
        set telegrame bot token
  -username string
        set login username
```

</details>

### x-ui log or xray log

<details>

```console
iplimit worked,current we have 5 ips,and we will limit to 2
current ips: [172.71.12.138 172.71.12.142 172.71.12.154 172.71.12.158 172.71.12.160]
invalid IP addr or iptables Chain not created
invalid IP addr or iptables Chain not created
invalid IP addr or iptables Chain not created

```

</details>

**Comment by FranzKafkaYu** [comment]
this `invalid IP addr or iptables Chain not created` info has noting to do with your problem,plz check xray server log and your client log to figure it out.
