### ISSUE TITLE
我无法设置面板端口，只能使用系统随机分配或者是恢复默认的54321

### ISSUE THREAD

**Issue by B1gCarr0t** [FranzKafkaYu/x-ui#526]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

我在面板设置中更换端口，或者使用x-ui脚本更换端口，更换重启后，用更换的端口均无法访问面板，网页都会返回：404 page not found

### Version of x-ui

面板版本[version]: 0.3.4.4:20230717

### x-ui log or xray log

```
Oct 24 06:26:54 ip-172-26-11-227 x-ui[104575]: 2023/10/24 06:26:54 INFO - web server run http on [::]:54321
Oct 24 06:26:54 ip-172-26-11-227 x-ui[104575]: 2023/10/24 06:26:54 INFO - Wait 2 seconds for telegram bot ready
Oct 24 06:27:17 ip-172-26-11-227 x-ui[104575]: 2023/10/24 06:27:17 WARNING - stop server err: multierr: close tcp [::]:54321: use of closed network connection |
Oct 24 06:27:17 ip-172-26-11-227 x-ui[104575]: 2023/10/24 06:27:17 INFO - web server run http on [::]:54322
Oct 24 06:27:17 ip-172-26-11-227 x-ui[104575]: 2023/10/24 06:27:17 INFO - Wait 2 seconds for telegram bot ready
```

**Comment by FranzKafkaYu** [comment]
@B1gCarr0t https://github.com/FranzKafkaYu/x-ui/wiki/%E9%9D%A2%E6%9D%BF%E7%99%BB%E5%BD%95
