### ISSUE TITLE
Add users limited to the 10 in X-UI panel(inbound)

### ISSUE THREAD

**Issue by MrSaeid007** [FranzKafkaYu/x-ui#528]
Hi @FranzKafkaYu 

We can not add users of more than 10 in inbound(X-ui panel).
Can you fix that? so we can add users up to 50?

Thanks.

**Comment by FranzKafkaYu** [comment]
@MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:loveme@duck.com

**Comment by MrSaeid007** [comment]
> @MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:[loveme@duck.com](mailto:loveme@duck.com)

@FranzKafkaYu Can you at least upgrade this restriction to the 15 or 20 numbers please?

Thank you.

**Comment by FranzKafkaYu** [comment]
> > @MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:[loveme@duck.com](mailto:loveme@duck.com)
> 
> @FranzKafkaYu Can you at least upgrade this restriction to the 15 or 20 numbers please?
> 
> Thank you.

it's OK.but I am wondering that u have 0-65535 ports,and each port can set up to 10 users,isn't it enough for personal use?

**Comment by MrSaeid007** [comment]
> > > @MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:[loveme@duck.com](mailto:loveme@duck.com)
> > 
> > 
> > @FranzKafkaYu Can you at least upgrade this restriction to the 15 or 20 numbers please?
> > Thank you.
> 
> it's OK.but I am wondering that u have 0-65535 ports,and each port can set up to 10 users,isn't it enough for personal use?

Since we live in Iran, the GFW may find our server IP address traffic and block it if we don't use port 443 on the Reality protocol.
So we have to use port 443 to set up Reality protocol here to not be detected by GFW for our server safety.
So I request you if there is any way to upgrade that number up to 15 or 20, it will be great.

Thank you.

**Comment by MrSaeid007** [comment]
> > > @MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:[loveme@duck.com](mailto:loveme@duck.com)
> > 
> > 
> > @FranzKafkaYu Can you at least upgrade this restriction to the 15 or 20 numbers please?
> > Thank you.
> 
> it's OK.but I am wondering that u have 0-65535 ports,and each port can set up to 10 users,isn't it enough for personal use?

Since we live in Iran, the GFW may find our server IP address traffic and block it if we don't use port 443 on the Reality protocol.
So we have to use port 443 to set up Reality protocol here to not be detected by GFW for our server safety.
So I request you if there is any way to upgrade that number up to 15 or 20, it will be great.

Thank you.

By my new explanation, will you increase the limit to 15 or 20 users? Can you give a definitive answer? I will wait for your reply.. @FranzKafkaYu

**Comment by FranzKafkaYu** [comment]
> > > > @MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:[loveme@duck.com](mailto:loveme@duck.com)
> > > 
> > > 
> > > @FranzKafkaYu Can you at least upgrade this restriction to the 15 or 20 numbers please?
> > > Thank you.
> > 
> > 
> > it's OK.but I am wondering that u have 0-65535 ports,and each port can set up to 10 users,isn't it enough for personal use?
> 
> Since we live in Iran, the GFW may find our server IP address traffic and block it if we don't use port 443 on the Reality protocol. So we have to use port 443 to set up Reality protocol here to not be detected by GFW for our server safety. So I request you if there is any way to upgrade that number up to 15 or 20, it will be great.
> 
> Thank you.
> 
> By my new explanation, will you increase the limit to 15 or 20 users? Can you give a definitive answer? I will wait for your reply.. @FranzKafkaYu

No problem,I will make some changes in next version,but I am not sure when it will come.

**Comment by MrSaeid007** [comment]
> > > > > @MrSaeid007 Hi，this restriction is designed to avoid abusing,if u wanna extra help,you can contact me via email:[loveme@duck.com](mailto:loveme@duck.com)
> > > > 
> > > > 
> > > > @FranzKafkaYu Can you at least upgrade this restriction to the 15 or 20 numbers please?
> > > > Thank you.
> > > 
> > > 
> > > it's OK.but I am wondering that u have 0-65535 ports,and each port can set up to 10 users,isn't it enough for personal use?
> > 
> > 
> > Since we live in Iran, the GFW may find our server IP address traffic and block it if we don't use port 443 on the Reality protocol. So we have to use port 443 to set up Reality protocol here to not be detected by GFW for our server safety. So I request you if there is any way to upgrade that number up to 15 or 20, it will be great.
> > Thank you.
> > By my new explanation, will you increase the limit to 15 or 20 users? Can you give a definitive answer? I will wait for your reply.. @FranzKafkaYu
> 
> No problem,I will make some changes in next version,but I am not sure when it will come.

Thank you @FranzKafkaYu 

Please make a note of this case to apply changes in the next version. I look forward to the new version.
