### ISSUE TITLE
一进面板设置就自动变成：404 page not found

### ISSUE THREAD

**Issue by tmzg0000** [FranzKafkaYu/x-ui#53]
一键安装，装好后登录网页正常，一进入网页设置页，浏览器自动飘过一些提示。太快看不清。然后就变成“404 page not found”
重装也没发恢复。
我是卸载后换路径装才能恢复正常，可是再次进入网页设置页又变成“404 page not found”

**Comment by FranzKafkaYu** [comment]
> 一键安装，装好后登录网页正常，一进入网页设置页，浏览器自动飘过一些提示。太快看不清。然后就变成“404 page not found” 重装也没发恢复。 我是卸载后换路径装才能恢复正常，可是再次进入网页设置页又变成“404 page not found”

**请看release note，谢谢**
![image](https://user-images.githubusercontent.com/38254177/180648869-5190c45c-b713-4c43-9dad-52eb1b954330.png)
