### ISSUE TITLE
网页打开为空白

### ISSUE THREAD

**Issue by proxyBug** [FranzKafkaYu/x-ui#535]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

最新版本，网页打开一片空白（可以打开，但登入页面一片空白）safari chrome 均已尝试。

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
11月 09 19:57:43 instance-20210530-1139 systemd[1]: Started x-ui Service.
11月 09 19:57:43 instance-20210530-1139 x-ui[22563]: 2023/11/09 19:57:43 x-ui 0.3.4.4:20230717
11月 09 19:57:43 instance-20210530-1139 x-ui[22563]: 2023/11/09 19:57:43 INFO - web server run http on [::]:12357
11月 09 19:57:43 instance-20210530-1139 x-ui[22563]: 2023/11/09 19:57:43 INFO - Wait 2 seconds for telegram bot ready
11月 09 19:57:45 instance-20210530-1139 x-ui[22563]: SSHLogin[2023-11-09 17:26:00] early than XUI start[2023-11-09 19:57:43],don't notify
11月 09 19:58:28 instance-20210530-1139 x-ui[22563]: 2023/11/09 19:58:28 [sessions] ERROR! securecookie: the value is not valid
11月 09 19:58:36 instance-20210530-1139 x-ui[22563]: 2023/11/09 19:58:36 [sessions] ERROR! securecookie: the value is not valid

</details>

**Comment by RootSir** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/ant-design-vue@1.7.2/antd.min.css">
    <link rel="stylesheet" href="/assets/element-ui@2.15.0/theme-chalk/display.css">
    <link rel="stylesheet" href="/assets/css/custom.css?0.3.4.4%3a20230717">
    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    <title>登录</title>
</head>


<style>

    #app {
        padding-top: 100px;
    }


    h1 {
        text-align: center;
        color: #fff;
        margin: 20px 0 50px 0;
    }


    .ant-btn,
    .ant-input {
        height: 50px;
        border-radius: 30px;
    }

    .ant-input-affix-wrapper .ant-input-prefix {
        left: 23px;
    }

    .ant-input-affix-wrapper .ant-input:not(:first-child) {
        padding-left: 50px;
    }
</style>


<body>
    <a-layout id="app" v-cloak>
        <transition name="list" appear>
            <a-layout-content>
                <a-row type="flex" justify="center">
                    <a-col :xs="22" :sm="20" :md="16" :lg="12" :xl="8">
                        <h1>登录</h1>
                    </a-col>
                </a-row>
                <a-row type="flex" justify="center">
                    <a-col :xs="22" :sm="20" :md="16" :lg="12" :xl="8">
                        <a-form>
                            <a-form-item>
                                <a-input v-model.trim="user.username" placeholder='`


补充登陆页下载到的源码如上，下载不全登陆无法显示

**Comment by RootSir** [comment]
[index.zip](https://github.com/FranzKafkaYu/x-ui/files/13366823/index.zip)
加载在登录页如附件。

**Comment by LiXDL** [comment]
使用Chrome时我也遇到了一样的问题，语言首选项依次为英语，简体中文，日文，繁体中文；换到Edge之后可以正常打开web UI，语言首选项仅使用英文。
![9OPA1)HGY})(OPL8S)CFFYT](https://github.com/FranzKafkaYu/x-ui/assets/38141753/3777f946-acaa-4d51-a0cb-92afe1f7941a)
如上图所示，似乎是web/html/login.html加载translation时出现了一些问题。

**Comment by LiXDL** [comment]
> 使用Chrome时我也遇到了一样的问题，语言首选项依次为英语，简体中文，日文，繁体中文；换到Edge之后可以正常打开web UI，语言首选项仅使用英文。 ![9OPA1)HGY})(OPL8S)CFFYT](https://user-images.githubusercontent.com/38141753/284412633-3777f946-acaa-4d51-a0cb-92afe1f7941a.png) 如上图所示，似乎是web/html/login.html加载translation时出现了一些问题。

我现在用Edge也打不开了。

**Comment by FranzKafkaYu** [comment]
@LiXDL @RootSir @proxyBug 目前只有少部分人报告该问题，因此需要再澄清一下，针对页面打开空白的问题，请确认以下操作：  
1.浏览器语言设置为简体中文或者英文  
2.清除浏览器cookie与缓存
3.如果有开启代理进行连接，请关闭代理  

如上，再进行尝试
