### ISSUE TITLE
内部更新xray时，能不能只更新xray-linux-amd64

### ISSUE THREAD

**Issue by blueberry-pie-11** [FranzKafkaYu/x-ui#539]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

现在通过xui更新xray时，xray压缩包携带了精简版geo文件，会覆盖现有geoip和geosite，导致geoip:cloudflare之类无法使用

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@blueberry-pie-11 暂不支持，但控制菜单支持手动更新Geo数据，数据源为LoyalSoldier
