### ISSUE TITLE
reality协议占用内存过多

### ISSUE THREAD

**Issue by gallexy** [FranzKafkaYu/x-ui#540]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

reality+xtls-rprx-vision, 跑了一下speedtest，内存能占2GB多，实在有点太多了

![image](https://github.com/FranzKafkaYu/x-ui/assets/3725145/62f168cc-a7a9-418b-b4ae-1be9e2fb4cb7)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@gallexy 这类问题请提交至上游解决，当然你可以通过修改配置模板进行优化，具体配置请参考官方文档。

**Comment by gallexy** [comment]
减小buffersize到2048，有效控制了内存增长。多谢回复
