### ISSUE TITLE
源码缺失不太合适吧

### ISSUE THREAD

**Issue by gallexy** [FranzKafkaYu/x-ui#543]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

对比了一下这里的源码和原项目源码，发现只提交了README文件和两个脚本源码，
相关新协议的实现部分和html页面均未提交，作为开源项目是否不太合适？

### Version of x-ui

0.3.4
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@gallexy 如果你愿意维护，那么我可以将源码释放出来，参见：https://github.com/FranzKafkaYu/x-ui/issues/341

**Comment by gallexy** [comment]
关于代码维护，我愿意略效微薄之力。  ：）

**Comment by CCCoralie** [comment]
叭叭叭叭的，也不看看自己 GitHub Contribution activity 什么个样子，人家爱开源就开源，不愿意就不愿意，不行你就自己去开发一个，还要说人家“不合适吧”，上游就在那，能开发就去啊，在这一副道德婊的样子去施压下游分支作者，恶心吧啦的东西。

**Comment by gallexy** [comment]
不开源谁知道你里面带没带私货？凭啥让别人信你？不愿意开源就别打开源的旗号，挂羊头卖狗肉算什么东西

**Comment by FranzKafkaYu** [comment]
为了避免争议，我已经将闭源信息更新至Readme，该话题终结。

> 不开源谁知道你里面带没带私货？凭啥让别人信你？不愿意开源就别打开源的旗号，挂羊头卖狗肉算什么东西

顺带一句，我从未公开宣称这是开源的，并且在多个场合宣布项目已经闭源，包括Xray Core官方群组。

**Comment by gallexy** [comment]
很好很赞成，我只是就事论事，失礼之处请见谅
