### ISSUE TITLE
armv7有望支持吗？

### ISSUE THREAD

**Issue by zcmi** [FranzKafkaYu/x-ui#55]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by FranzKafkaYu** [comment]
后续编译打包时可以考虑增加该架构的版本，但我没有设备也没有时间进行测试。

**Comment by zcmi** [comment]
> 后续编译打包时可以考虑增加该架构的版本，但我没有设备也没有时间进行测试。

行吧，那没事了，哈哈哈
