### ISSUE TITLE
新版本好像有bug？

### ISSUE THREAD

**Issue by doublog** [FranzKafkaYu/x-ui#59]
添加了入站以后，二维码展示不出来，复制链接也复制不到。是BUG么？

**Comment by FranzKafkaYu** [comment]
> 添加了入站以后，二维码展示不出来，复制链接也复制不到。是BUG么？

目前新版本已支持单端口多用户，在添加入站后需要添加用户，才可获取二维码与分享链接。

**Comment by FranzKafkaYu** [comment]
0814发布的版本已经进行优化，可以更新最新版本进行测试。

**Comment by zonbar** [comment]
目前多用户是可以复制各自的链接但好像是不支持各自二维码的，是否可以在后面添加各用户的二维码，毕竟移动端用码比较方便，操作 菜单里的可保留也可去除
![微信截图_20230223093318](https://user-images.githubusercontent.com/44555226/220802954-39b4ee9e-3024-42bd-b24a-b37d128cb985.png)
