### ISSUE TITLE
后台换XRAY内核有问题

### ISSUE THREAD

**Issue by 97668589** [FranzKafkaYu/x-ui#6]
点击切换按钮后，xray内核会停止运行

**Comment by FranzKafkaYu** [comment]
请问是全新安装0.3.3.9版本，还是由老版本更新到了0.3.3.9版本

**Comment by 97668589** [comment]
> 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本

好像都不行，你试试看

**Comment by FranzKafkaYu** [comment]
> > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> 
> 好像都不行，你试试看

Ubantu 16 自测没有问题，所以你的系统版本是什么版本呢

**Comment by 97668589** [comment]
> > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > 
> > 
> > 好像都行，你试试看
> 
> ubantu 16 自测没有问题，所以你的系统版本是什么版本呢

ubantu 22.04

**Comment by 97668589** [comment]
> > > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > > 
> > > 
> > > 好像都行，你试试看
> > 
> > 
> > ubantu 16 自测没有问题，所以你的系统版本是什么版本呢
> 
> ubantu 22.04

我现在试了下原版x-ui  一切正常

**Comment by FranzKafkaYu** [comment]
> > > > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > > > 
> > > > 
> > > > 好像都行，你试试看
> > > 
> > > 
> > > ubantu 16 自测没有问题，所以你的系统版本是什么版本呢
> > 
> > 
> > ubantu 22.04
> 
> 我现在试了下原版x-ui 一切正常

可以通过bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh)  0.3.3.8 安装0.3.3.8版本，试试0.3.3.8版本

**Comment by 97668589** [comment]
> > > > > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > > > > 
> > > > > 
> > > > > 好像都行，你试试看
> > > > 
> > > > 
> > > > ubantu 16 自测没有问题，所以你的系统版本是什么版本呢
> > > 
> > > 
> > > ubantu 22.04
> > 
> > 
> > 我现在试了下原版x-ui 一切正常
> 
> 可以通过bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh) 0.3.3.8 安装0.3.3.8版本，试试0.3.3.8版本

3.8WEB都进不去  一直是登录界面  看来问题很大啊   哈哈  我还是用原版吧

**Comment by 97668589** [comment]
> > > > > > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > > > > > 
> > > > > > 
> > > > > > 好像都行，你试试看
> > > > > 
> > > > > 
> > > > > ubantu 16 自测没有问题，所以你的系统版本是什么版本呢
> > > > 
> > > > 
> > > > ubantu 22.04
> > > 
> > > 
> > > 我现在试了下原版x-ui 一切正常
> > 
> > 
> > 可以通过bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh) 0.3.3.8 安装0.3.3.8版本，试试0.3.3.8版本
> 
> 3.8WEB都进不去 一直是登录界面 看来问题很大啊 哈哈 我还是用原版吧

暂时不折腾了   累  等你完善再说

**Comment by FranzKafkaYu** [comment]
> > > > > > > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > > > > > > 
> > > > > > > 
> > > > > > > 好像都行，你试试看
> > > > > > 
> > > > > > 
> > > > > > ubantu 16 自测没有问题，所以你的系统版本是什么版本呢
> > > > > 
> > > > > 
> > > > > ubantu 22.04
> > > > 
> > > > 
> > > > 我现在试了下原版x-ui 一切正常
> > > 
> > > 
> > > 可以通过bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh) 0.3.3.8 安装0.3.3.8版本，试试0.3.3.8版本
> > 
> > 
> > 3.8WEB都进不去 一直是登录界面 看来问题很大啊 哈哈 我还是用原版吧
> 
> 暂时不折腾了 累 等你完善再说

已修复，还是版本兼容引起，可使用最新版本

**Comment by 97668589** [comment]
> > > > > > > > > 是请安装0.3.3.9版本，还是由旧版本更新到0.3.3.9版本
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 好像都行，你试试看
> > > > > > > 
> > > > > > > 
> > > > > > > ubantu 16 自测没有问题，所以你的系统版本是什么版本呢
> > > > > > 
> > > > > > 
> > > > > > ubantu 22.04
> > > > > 
> > > > > 
> > > > > 我现在试了下原版x-ui 一切正常
> > > > 
> > > > 
> > > > 可以通过bash <(curl -Ls https://raw.githubusercontent.com/FranzKafkaYu/x-ui/master/install.sh) 0.3.3.8 安装0.3.3.8版本，试试0.3.3.8版本
> > > 
> > > 
> > > 3.8WEB都进不去 一直是登录界面 看来问题很大啊 哈哈 我还是用原版吧
> > 
> > 
> > 暂时不折腾了 累 等你完善再说
> 
> 已修复，还是版本兼容引起，可使用最新版本

我靠，这么快就修复了啊，这就尴尬了，效率真高

**Comment by FranzKafkaYu** [comment]
最新版本修复该问题
