### ISSUE TITLE
最新版有bug

### ISSUE THREAD

**Issue by 7tianv** [FranzKafkaYu/x-ui#62]
使用一键命令安装最新版，打开设置界面时会出现白屏
![image](https://user-images.githubusercontent.com/69331846/185781523-bd71fcd0-cc83-49d9-ad78-513f5957104f.png)

**Comment by GH6324** [comment]
[https://github.com/FranzKafkaYu/x-ui/wiki/%E9%9D%A2%E6%9D%BF%E7%99%BB%E5%BD%95](url)

**Comment by FranzKafkaYu** [comment]
请查看WIKI说明文档。

**Comment by 7tianv** [comment]
> 请查看WIKI说明文档。

wiki文档里面的我都确认了，没有问题，防火墙开启，xui正常运行，进入xui后台后再打开设置界面会提示一次正在重启面板，然后界面就会白屏，清除缓存无痕模式都是白屏，在vps上重置一下面板设置就会恢复，但再次进入设置界面依旧会白屏

**Comment by FranzKafkaYu** [comment]
> > 请查看WIKI说明文档。
> 
> wiki文档里面的我都确认了，没有问题，防火墙开启，xui正常运行，进入xui后台后再打开设置界面会提示一次正在重启面板，然后界面就会白屏，清除缓存无痕模式都是白屏，在vps上重置一下面板设置就会恢复，但再次进入设置界面依旧会白屏

![image](https://user-images.githubusercontent.com/38254177/185797961-95dd9dce-bd4d-4d93-bab5-5b8eed10744b.png)
