### ISSUE TITLE
不同的域名加端口进入XUI会导致，相同的节点显示的地址域名不一样。

### ISSUE THREAD

**Issue by north459** [FranzKafkaYu/x-ui#64]
![photo_2022-08-24_14-07-17](https://user-images.githubusercontent.com/33856830/186426505-7430b776-2bd6-47dd-a2c2-babc8498adcd.jpg)
![photo_2022-08-24_14-07-29](https://user-images.githubusercontent.com/33856830/186426533-46e90088-78ea-4f96-82c2-d2d510a81b69.jpg)
能固定节点地址是在设置的时候的地址吗

**Comment by FranzKafkaYu** [comment]
> 或者节点在添加入站的时候能自己填写地址

启用tls的时候不是会填写域名么，这就是地址。如果没有启动tls，那么就会使用面板的域名作为地址。
