### ISSUE TITLE
安装后登录面板，点击面板设置后就404页面不存在

### ISSUE THREAD

**Issue by ronghong1320** [FranzKafkaYu/x-ui#65]
点击了面板设置，未做任何修改，即404页面不存在
这是什么情况

**Comment by FranzKafkaYu** [comment]
请查看WIKI文档：
![image](https://user-images.githubusercontent.com/38254177/186606407-d4ad2c5b-fb3d-4d3e-9426-3c0c5154077f.png)

**Comment by ronghong1320** [comment]
感谢！

Yu FranzKafka ***@***.***> 于2022年8月25日周四 15:47写道：

**Comment by ronghong1320** [comment]
[image: image.png][image: image.png][image: image.png] [image: image.png]
请教，这表示什么问题。证书申请下来安装好了，还需要这么完成设置呢？


Alex ***@***.***> 于2022年8月25日周四 16:10写道：

**Comment by ronghong1320** [comment]
仍然提示不安全。不能开启https


Alex ***@***.***> 于2022年8月25日周四 17:40写道：

**Comment by FranzKafkaYu** [comment]
> 

看不到图片，如有问题，可通过telegram 群组进行反馈
