### ISSUE TITLE
从原版升级过来，如果alterId的值是64，账号就无法连接

### ISSUE THREAD

**Issue by xuexiaokang** [FranzKafkaYu/x-ui#70]
从原版升级过来，如果alterId的值是64，账号就无法连接，这个是什么原因呢？

**Comment by FranzKafkaYu** [comment]
> 从原版升级过来，如果alterId的值是64，账号就无法连接，这个是什么原因呢？

![image](https://user-images.githubusercontent.com/38254177/188640520-82162cf1-5e40-434a-9f38-048e935bcca3.png)
**请将alterid设置为0**

**Comment by xuexiaokang** [comment]
好的，谢谢
