### ISSUE TITLE
希望提供Inbound TLS设置下的alpn以支持h2和http/1.1

### ISSUE THREAD

**Issue by miles-lin** [FranzKafkaYu/x-ui#73]
在某些时候还需要切换alpn顺序，希望能增加这个功能
https://xtls.github.io/config/features/fallback.html#fallbackobject

**Comment by FranzKafkaYu** [comment]
> 在某些时候还需要切换alpn顺序，希望能增加这个功能 https://xtls.github.io/config/features/fallback.html#fallbackobject

在不配置的情况下，程序内部会使用h2与http/1.1	，参见https://github.com/XTLS/Xray-core/blob/6bb735d103b713b7972684e07e84a693d0b4f61b/transport/internet/tls/config.go#L313，有必须单独设定的必要么
