### ISSUE TITLE
当我装好以后，点击面板设置的页面就会弹出修改完毕，保存设置，然后再访问就会变成404.

### ISSUE THREAD

**Issue by 18111800008** [FranzKafkaYu/x-ui#74]
当我装好以后，点击面板设置的页面就会弹出修改完毕，保存设置，然后再访问就会变成404.

**Comment by FranzKafkaYu** [comment]
https://github.com/FranzKafkaYu/x-ui/issues/65#issuecomment-1226901486

**Comment by 18111800008** [comment]
> x-ui 命令，可以查看配置，里面会有当前随机生成的路径 首次登录后，如果你眼睛够“尖”的话，会看到路径那个位置的变化
> 
> 有些时候，会先安装原版的x-ui，配置完毕后，再保留配置升级

十分感谢，原来如此
