### ISSUE TITLE
是否可增加按月设置限额、次月初自动重置流量的功能

### ISSUE THREAD

**Issue by jwd1208** [FranzKafkaYu/x-ui#75]
是否可增加按月设置限额、次月初自动重置流量的功能

**Comment by FranzKafkaYu** [comment]
> 是否可增加按月设置限额、次月初自动重置流量的功能

当前版本已经支持次月自动重置流量功能，在添加节点时开启自动重置功能，次月1日0点重置流量统计。

**Comment by jwd1208** [comment]
刚刚看了 并未重置 自动重置是开启状态

**Comment by FranzKafkaYu** [comment]
> 刚刚看了 并未重置 自动重置是开启状态

已经发现了，这可能是个bug

**Comment by zixu5u** [comment]
> > 刚刚看了 并未重置 自动重置是开启状态
> 
> 已经发现了，这可能是个bug

我的也是，开启了自动重置，月初实际不会重置。

**Comment by jwd1208** [comment]
开发者好，请问新版本里这个bug修复了吗

**Comment by FranzKafkaYu** [comment]
@jwd1208 最新版本已经修复。
