### ISSUE TITLE
使用vmess+ws+TLS+web，设备IP变化时电报机器人不会通知

### ISSUE THREAD

**Issue by zixu5u** [FranzKafkaYu/x-ui#79]
**我使用vmess+ws+TLS+web，nginx在xray前端分流，nginx监听端口443，nginx配置“ location /   分流到某伪装网址，location /UUID 分流到x ray”。**

**已设置设备IP变化时电报机器人通知，但实际不会通知，查看服务器access log，可以看到设备IP。SSH、xui面板登陆，电报机器人会正常通知。**

当前面板信息[current panel info]:
面板版本[version]: 0.3.3.16:20220814
x ray版本：v1.6.0

**xui面板xray配置如下**
{
"log": {
    "access": "/usr/local/x-ui/bin/access.log",
    "error": "/usr/local/x-ui/bin/error.log",
    "loglevel": "warning",
    "dnsLog": false
 },
     "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "dns": {
    "hosts": {
      "dns.google":  ["8.8.8.8", "8.8.4.4"],
      "dns.pub": "119.29.29.29",
      "dns.alidns.com": "223.5.5.5"
    },
    "servers": [
      {
        "address": "https://1.1.1.1/dns-query",
        "domains": ["geosite:geolocation-!cn", "geosite:google@cn"],
        "expectIPs": ["geoip:!cn"]
      },
        "1.1.1.1",
      {
        "address": "localhost",
        "skipFallback": true
      }
    ],
    "queryStrategy": "UseIP"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "bufferSize": 4
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "hybrid",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn"
          ],
        "outboundTag": "block"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**服务器/usr/local/x-ui/bin/config.json  配置如下**

{
  "log": {
    "access": "/usr/local/x-ui/bin/access.log",
    "error": "/usr/local/x-ui/bin/error.log",
    "loglevel": "warning",
    "dnsLog": false
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "hybrid",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn"
        ],
        "outboundTag": "block"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "dns": {
    "hosts": {
      "dns.google": [
        "8.8.8.8",
        "8.8.4.4"
      ],
      "dns.pub": "119.29.29.29",
      "dns.alidns.com": "223.5.5.5"
    },
    "servers": [
      {
        "address": "https://1.1.1.1/dns-query",
        "domains": [
          "geosite:geolocation-!cn",
          "geosite:google@cn"
        ],
        "expectIPs": [
          "geoip:!cn"
        ]
      },
      "1.1.1.1",
      {
        "address": "localhost",
        "skipFallback": true
      }
    ],
    "queryStrategy": "UseIP"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "streamSettings": null,
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": "127.0.0.1",
      "port": 13235,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "UUID1",
            "email": "ow@xray.com",
            "alterId": 0
          }
        ],
        "disableInsecureEncryption": true
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/UUID1",
          "headers": {}
        }
      },
      "tag": "inbound-13235",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 28680,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "UUID2",
            "email": "may@xray.com",
            "alterId": 0
          }
        ],
        "disableInsecureEncryption": true
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/UUID2",
          "headers": {}
        }
      },
      "tag": "inbound-28680",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 1848,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "UUID3",
            "email": "joy@xray.com",
            "alterId": 0
          }
        ],
        "disableInsecureEncryption": false
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/UUID3",
          "headers": {}
        }
      },
      "tag": "inbound-1848",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 35459,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "UUID4",
            "email": "D@xray.com",
            "alterId": 0
          }
        ],
        "disableInsecureEncryption": true
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/UUID4",
          "headers": {}
        }
      },
      "tag": "inbound-35459",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "transport": null,
  "policy": {
    "levels": {
      "0": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "bufferSize": 4
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "reverse": null,
  "fakeDns": null
}

**nginx config配置如下**

user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /usr/local/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
  server_tokens  off;
  
    include /usr/local/nginx/mime.types;
    default_type application/octet-stream;
    gzip on;
    

    server {
        listen  443 ssl http2;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        server_name 域名;  #你的域名
        ssl_certificate       /root/cert/域名.cer;  #证书位置
        ssl_certificate_key   /root/cert/域名.key; #私钥位置
                ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_protocols    TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
  ssl_ciphers           EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256::!MD5;

        location / {
            proxy_pass 伪装网址; #伪装网址
            proxy_redirect off;
            proxy_ssl_server_name on;
            sub_filter_once off;
            sub_filter "伪装网址" $server_name;
            proxy_set_header Host "伪装网址";
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header User-Agent $http_user_agent;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Accept-Language "zh-CN";
        }

        location /UUID1 {   #分流路径
            proxy_redirect off;
            proxy_pass http://127.0.0.1:19177; #Xray端口
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
                                   proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header x-forwarded-for $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Real-Port $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /UUID2 {   #分流路径
    proxy_redirect off;
    proxy_pass http://127.0.0.1:23095; #Xray端口
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
        location /UUID3-xui/{   #xui路径
            proxy_redirect off;
            proxy_pass http://127.0.0.1:168;  #xui监听端口
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-Port $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 80;
        location /.well-known/ {
               root /var/www/html;
            }
        location / {
                rewrite ^(.*)$ https://$host$1 permanent;
            }
    }
}

**Comment by xuanyepan** [comment]
你这xray配置监听的端口怎么和Nginx配置上xray的监听端口不一样的？

**Comment by zixu5u** [comment]
> 你这xray配置监听的端口怎么和Nginx配置上xray的监听端口不一样的？

一样的，你仔细看看配置内容

**Comment by Chasing66** [comment]
@zixu5u  遇到了跟你一样的现象
```
        location /test {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```
nginx 的配置看着是没哈问题的，可能是x-ui这边解析ip的时候存在bug？ @FranzKafkaYu

**Comment by FranzKafkaYu** [comment]
@Chasing66 @zixu5u 很抱歉，当前实现的逻辑无法满足Nginx前置情况下的设备通知。
