### ISSUE TITLE
大佬您好，请问几个问题

### ISSUE THREAD

**Issue by 281677160** [FranzKafkaYu/x-ui#8]
请问一下，安装面板的时候用什么命令能修改好面板的根路径和证书路径？现有的只能修改帐号、密码、端口，非常不方便啊，这个是非常需要的，因为安装的时候一起修改好，然后可以把反代那些全弄好的，非常方便，可惜我不知道用什么命令能改根路径跟证书路径

还有就是在面板里面能不能弄一个设置，把域名，证书路径填上，然后建立节点的时候就自动读取，不需要建立每个节点都要去搞一下证书路径的，还有域名也是，感觉很累啊

**Comment by FranzKafkaYu** [comment]
> 请问一下，安装面板的时候用什么命令能修改好面板的根路径和证书路径？现有的只能修改帐号、密码、端口，非常不方便啊，这个是非常需要的，因为安装的时候一起修改好，然后可以把反代那些全弄好的，非常方便，可惜我不知道用什么命令能改根路径跟证书路径
> 
> 还有就是在面板里面能不能弄一个设置，把域名，证书路径填上，然后建立节点的时候就自动读取，不需要建立每个节点都要去搞一下证书路径的，还有域名也是，感觉很累啊

1.针对你提到的第一点，目前不支持脚本设置跟路径与证书路径，也没有多大必要，你要修改可以在面板完成
2.针对第2点，可以理解作为一个优化项，抽空会实现的

**Comment by 281677160** [comment]
感谢大佬抽空回复，其实第一点对我来说更重要，什么都可以命令改的话，这样我一键安装就不需要折腾了，立马登录使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FranzKafkaYu/x-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FranzKafkaYu/x-ui] 大佬您好，请问几个问题 (Issue #8)





  
请问一下，安装面板的时候用什么命令能修改好面板的根路径和证书路径？现有的只能修改帐号、密码、端口，非常不方便啊，这个是非常需要的，因为安装的时候一起修改好，然后可以把反代那些全弄好的，非常方便，可惜我不知道用什么命令能改根路径跟证书路径
 
还有就是在面板里面能不能弄一个设置，把域名，证书路径填上，然后建立节点的时候就自动读取，不需要建立每个节点都要去搞一下证书路径的，还有域名也是，感觉很累啊
  
1.针对你提到的第一点，目前不支持脚本设置跟路径与证书路径，也没有多大必要，你要修改可以在面板完成
 2.针对第2点，可以理解作为一个优化项，抽空会实现的

**Comment by FranzKafkaYu** [comment]
> 感谢大佬抽空回复，其实第一点对我来说更重要，什么都可以命令改的话，这样我一键安装就不需要折腾了，立马登录使用
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FranzKafkaYu/x-ui" ***@***.***&gt;; 发送时间:&nbsp;2022年5月5日(星期四) 晚上7:51 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [FranzKafkaYu/x-ui] 大佬您好，请问几个问题 (Issue #8) 请问一下，安装面板的时候用什么命令能修改好面板的根路径和证书路径？现有的只能修改帐号、密码、端口，非常不方便啊，这个是非常需要的，因为安装的时候一起修改好，然后可以把反代那些全弄好的，非常方便，可惜我不知道用什么命令能改根路径跟证书路径 还有就是在面板里面能不能弄一个设置，把域名，证书路径填上，然后建立节点的时候就自动读取，不需要建立每个节点都要去搞一下证书路径的，还有域名也是，感觉很累啊 1.针对你提到的第一点，目前不支持脚本设置跟路径与证书路径，也没有多大必要，你要修改可以在面板完成 2.针对第2点，可以理解作为一个优化项，抽空会实现的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

鉴于该需求属于个人需求，暂不实现
