### ISSUE TITLE
证书签发失败

### ISSUE THREAD

**Issue by zzj-ztms** [FranzKafkaYu/x-ui#80]
[Fri 30 Sep 2022 09:10:50 AM CST] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
[Fri 30 Sep 2022 09:10:51 AM CST] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri 30 Sep 2022 09:10:51 AM CST] Create account key ok.
[Fri 30 Sep 2022 09:10:51 AM CST] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Fri 30 Sep 2022 09:10:53 AM CST] Registered
[Fri 30 Sep 2022 09:10:53 AM CST] ACCOUNT_THUMBPRINT='Y-QsSI3jbsAU7HybfxHid4xISS_sPmJqNTunTRCtLZ8'
[Fri 30 Sep 2022 09:10:53 AM CST] Creating domain key
[Fri 30 Sep 2022 09:10:53 AM CST] The domain key is here: /root/.acme.sh/zzjztms.cf/zzjztms.cf.key
[Fri 30 Sep 2022 09:10:53 AM CST] Multi domain='DNS:zzjztms.cf,DNS:*.zzjztms.cf'
[Fri 30 Sep 2022 09:10:53 AM CST] Getting domain auth token for each domain
[Fri 30 Sep 2022 09:10:55 AM CST] Getting webroot for domain='zzjztms.cf'
[Fri 30 Sep 2022 09:10:55 AM CST] Getting webroot for domain='*.zzjztms.cf'
[Fri 30 Sep 2022 09:10:55 AM CST] Adding txt value: q-L434Kf00OuhNQ1Mb2v6WCNhoIeaczInGXO8DchgKk for domain:  _acme-challenge.zzjztms.cf
[Fri 30 Sep 2022 09:10:58 AM CST] Adding record
[Fri 30 Sep 2022 09:11:00 AM CST] Add txt record error.
[Fri 30 Sep 2022 09:11:00 AM CST] Error add txt for domain:_acme-challenge.zzjztms.cf
[Fri 30 Sep 2022 09:11:00 AM CST] Please check log file for more details: /root/.acme.sh/acme.sh.log

再次使用一键申请提示已有对应域名证书
[ERR] 域名合法性校验失败,当前环境已有对应域名证书,不可重复申请,当前证书详情: 
[INF] Main_Domain  KeyLength  SAN_Domains   CA               Created  Renew
zzjztms.cf   "2048"     *.zzjztms.cf  LetsEncrypt.org 

这是成功了吗

**Comment by zzj-ztms** [comment]
/root/cert目录 下也没看到有证书

**Comment by FranzKafkaYu** [comment]
> 

并未申请成功，当前证书合法性检验存在问题，请进入~/. acme.sh目录，手动删除zzjztms.cf的文件夹后再行申请。

**Comment by zzj-ztms** [comment]
> > 
> 
> 并未申请成功，当前证书合法性检验存在问题，请进入~/. acme.sh目录，手动删除zzjztms.cf的文件夹后再行申请。

[Fri 30 Sep 2022 10:34:08 AM CST] Adding record
[Fri 30 Sep 2022 10:34:08 AM CST] zones/a7d81754a64616c0fed71202115ef148/dns_records
[Fri 30 Sep 2022 10:34:08 AM CST] data='{"type":"TXT","name":"_acme-challenge.zzjztms.cf","content":"c4JG22fCCZBK5IuWSQ2EuXrhK8kvr78VPXTnYDJx7FI","ttl":120}'
[Fri 30 Sep 2022 10:34:08 AM CST] POST
[Fri 30 Sep 2022 10:34:08 AM CST] _post_url='https://api.cloudflare.com/client/v4/zones/a7d81754a64616c0fed71202115ef148/dns_records'
[Fri 30 Sep 2022 10:34:08 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Fri 30 Sep 2022 10:34:09 AM CST] _ret='0'
[Fri 30 Sep 2022 10:34:09 AM CST] Add txt record error.
[Fri 30 Sep 2022 10:34:09 AM CST] Error add txt for domain:_acme-challenge.zzjztms.cf
[Fri 30 Sep 2022 10:34:09 AM CST] _on_issue_err
[Fri 30 Sep 2022 10:34:09 AM CST] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Fri 30 Sep 2022 10:34:09 AM CST] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009826/iLGX9w'
[Fri 30 Sep 2022 10:34:09 AM CST] payload='{}'
[Fri 30 Sep 2022 10:34:09 AM CST] POST
[Fri 30 Sep 2022 10:34:09 AM CST] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009826/iLGX9w'
[Fri 30 Sep 2022 10:34:09 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Fri 30 Sep 2022 10:34:10 AM CST] _ret='0'
[Fri 30 Sep 2022 10:34:10 AM CST] code='200'
[Fri 30 Sep 2022 10:34:10 AM CST] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009816/enK6RA'
[Fri 30 Sep 2022 10:34:10 AM CST] payload='{}'
[Fri 30 Sep 2022 10:34:10 AM CST] POST
[Fri 30 Sep 2022 10:34:10 AM CST] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009816/enK6RA'
[Fri 30 Sep 2022 10:34:10 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Fri 30 Sep 2022 10:34:11 AM CST] _ret='0'
[Fri 30 Sep 2022 10:34:11 AM CST] code='200'
[Fri 30 Sep 2022 10:34:11 AM CST] pid
[Fri 30 Sep 2022 10:34:11 AM CST] No need to restore nginx, skip.
[Fri 30 Sep 2022 10:34:11 AM CST] _clearupdns
[Fri 30 Sep 2022 10:34:11 AM CST] dns_entries
[Fri 30 Sep 2022 10:34:11 AM CST] skip dns.

大佬能帮忙看看是什么问题吗,cf添加了A记录并开启了代理,域名也能ping通

**Comment by FranzKafkaYu** [comment]
> > > 
> > 
> > 
> > 并未申请成功，当前证书合法性检验存在问题，请进入~/. acme.sh目录，手动删除zzjztms.cf的文件夹后再行申请。
> 
> [Fri 30 Sep 2022 10:34:08 AM CST] Adding record [Fri 30 Sep 2022 10:34:08 AM CST] zones/a7d81754a64616c0fed71202115ef148/dns_records [Fri 30 Sep 2022 10:34:08 AM CST] data='{"type":"TXT","name":"_acme-challenge.zzjztms.cf","content":"c4JG22fCCZBK5IuWSQ2EuXrhK8kvr78VPXTnYDJx7FI","ttl":120}' [Fri 30 Sep 2022 10:34:08 AM CST] POST [Fri 30 Sep 2022 10:34:08 AM CST] _post_url='https://api.cloudflare.com/client/v4/zones/a7d81754a64616c0fed71202115ef148/dns_records' [Fri 30 Sep 2022 10:34:08 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' [Fri 30 Sep 2022 10:34:09 AM CST] _ret='0' [Fri 30 Sep 2022 10:34:09 AM CST] Add txt record error. [Fri 30 Sep 2022 10:34:09 AM CST] Error add txt for domain:_acme-challenge.zzjztms.cf [Fri 30 Sep 2022 10:34:09 AM CST] _on_issue_err [Fri 30 Sep 2022 10:34:09 AM CST] Please check log file for more details: /root/.acme.sh/acme.sh.log [Fri 30 Sep 2022 10:34:09 AM CST] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009826/iLGX9w' [Fri 30 Sep 2022 10:34:09 AM CST] payload='{}' [Fri 30 Sep 2022 10:34:09 AM CST] POST [Fri 30 Sep 2022 10:34:09 AM CST] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009826/iLGX9w' [Fri 30 Sep 2022 10:34:09 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' [Fri 30 Sep 2022 10:34:10 AM CST] _ret='0' [Fri 30 Sep 2022 10:34:10 AM CST] code='200' [Fri 30 Sep 2022 10:34:10 AM CST] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009816/enK6RA' [Fri 30 Sep 2022 10:34:10 AM CST] payload='{}' [Fri 30 Sep 2022 10:34:10 AM CST] POST [Fri 30 Sep 2022 10:34:10 AM CST] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009816/enK6RA' [Fri 30 Sep 2022 10:34:10 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' [Fri 30 Sep 2022 10:34:11 AM CST] _ret='0' [Fri 30 Sep 2022 10:34:11 AM CST] code='200' [Fri 30 Sep 2022 10:34:11 AM CST] pid [Fri 30 Sep 2022 10:34:11 AM CST] No need to restore nginx, skip. [Fri 30 Sep 2022 10:34:11 AM CST] _clearupdns [Fri 30 Sep 2022 10:34:11 AM CST] dns_entries [Fri 30 Sep 2022 10:34:11 AM CST] skip dns.
> 
> 大佬能帮忙看看是什么问题吗,cf添加了A记录并开启了代理,域名也能ping通

第二次申请感觉是用的方式2?

**Comment by zzj-ztms** [comment]
> > > > 
> > > 
> > > 
> > > 并未申请成功，当前证书合法性检验存在问题，请进入~/. acme.sh目录，手动删除zzjztms.cf的文件夹后再行申请。
> > 
> > 
> > [Fri 30 Sep 2022 10:34:08 AM CST] Adding record [Fri 30 Sep 2022 10:34:08 AM CST] zones/a7d81754a64616c0fed71202115ef148/dns_records [Fri 30 Sep 2022 10:34:08 AM CST] data='{"type":"TXT","name":"_acme-challenge.zzjztms.cf","content":"c4JG22fCCZBK5IuWSQ2EuXrhK8kvr78VPXTnYDJx7FI","ttl":120}' [Fri 30 Sep 2022 10:34:08 AM CST] POST [Fri 30 Sep 2022 10:34:08 AM CST] _post_url='https://api.cloudflare.com/client/v4/zones/a7d81754a64616c0fed71202115ef148/dns_records' [Fri 30 Sep 2022 10:34:08 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' [Fri 30 Sep 2022 10:34:09 AM CST] _ret='0' [Fri 30 Sep 2022 10:34:09 AM CST] Add txt record error. [Fri 30 Sep 2022 10:34:09 AM CST] Error add txt for domain:_acme-challenge.zzjztms.cf [Fri 30 Sep 2022 10:34:09 AM CST] _on_issue_err [Fri 30 Sep 2022 10:34:09 AM CST] Please check log file for more details: /root/.acme.sh/acme.sh.log [Fri 30 Sep 2022 10:34:09 AM CST] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009826/iLGX9w' [Fri 30 Sep 2022 10:34:09 AM CST] payload='{}' [Fri 30 Sep 2022 10:34:09 AM CST] POST [Fri 30 Sep 2022 10:34:09 AM CST] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009826/iLGX9w' [Fri 30 Sep 2022 10:34:09 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' [Fri 30 Sep 2022 10:34:10 AM CST] _ret='0' [Fri 30 Sep 2022 10:34:10 AM CST] code='200' [Fri 30 Sep 2022 10:34:10 AM CST] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009816/enK6RA' [Fri 30 Sep 2022 10:34:10 AM CST] payload='{}' [Fri 30 Sep 2022 10:34:10 AM CST] POST [Fri 30 Sep 2022 10:34:10 AM CST] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/159080009816/enK6RA' [Fri 30 Sep 2022 10:34:10 AM CST] _CURL='curl --silent --dump-header /root/.acme.sh/http.header -L -g ' [Fri 30 Sep 2022 10:34:11 AM CST] _ret='0' [Fri 30 Sep 2022 10:34:11 AM CST] code='200' [Fri 30 Sep 2022 10:34:11 AM CST] pid [Fri 30 Sep 2022 10:34:11 AM CST] No need to restore nginx, skip. [Fri 30 Sep 2022 10:34:11 AM CST] _clearupdns [Fri 30 Sep 2022 10:34:11 AM CST] dns_entries [Fri 30 Sep 2022 10:34:11 AM CST] skip dns.
> > 大佬能帮忙看看是什么问题吗,cf添加了A记录并开启了代理,域名也能ping通
> 
> 第二次申请感觉是用的方式2?

是的

**Comment by FranzKafkaYu** [comment]
DNS API申请存在限制，尤其是免费域名，请确认
