### ISSUE TITLE
增加默认的证书路径或一键导入证书路径

### ISSUE THREAD

**Issue by doutuo** [FranzKafkaYu/x-ui#82]
作者你好，如若有时间，请您可以在添加tls证书的路径的输入框中，默认证书路径吗？【或者在旁边有个一键导入证书路径按钮】
比如咱们一键申请自动生成证书安装目录为/root/cert/fullchain.pem  privkey.pem   公钥和密钥都用默认申请的~

不然这个填证书路径的地方，每次新开用户都要去复制路径填一次，用电脑还好操作，用手机的时候，还要双开才有得复制填入。

谢谢！

**Comment by Jerry-Young-23** [comment]
> 实际上这个功能很难实现，每个人的路径名是不同的，文件名也是不同的。

**Comment by doutuo** [comment]
> > 实际上这个功能很难实现，每个人的路径名是不同的，文件名也是不同的。

逻辑上是可以实现的~ 如果是用的作者的一键自动生成证书的话， 证书目录是固定的
如果是自定义证书路径和名称的话，在首次填入路径后，可以有个勾选记住证书路径。类似咱们的记住密码的。

**Comment by iopq** [comment]
it could just be entering the folder name, the file names are going to usually be fullchain.pem and privkey.pem and they will be in the same folder

**Comment by duqn** [comment]
我在使用0.3.4.2版本时发现Bug，在安装过程中，选择默认的80端口，一键证书申请报错
