### ISSUE TITLE
Multi User At Same Port With multi GB Settings

### ISSUE THREAD

**Issue by alirezashahrokhi** [FranzKafkaYu/x-ui#83]
hi . thanks For your Work

possible to create multi user at same port with multi GB Teraffic Option?

I Want Tunnel Server_A to (x-ui)Server With SSH and need one port with multiuser . 

thanks

**Comment by alirezashahrokhi** [comment]
> hello As a user, I tried so many times to create multi-user port but I couldn't.

Thanks Dear User

**Comment by alirezashahrokhi** [comment]
lol
I Do it By iptables 


> > hi . thanks For your Work
> > possible to create multi user at same port with multi GB Teraffic Option?
> > I Want Tunnel Server_A to (x-ui)Server With SSH and need one port with multiuser .
> > thanks
> 
> Hi ,,
> 
> If u want to tunnel to server without one port I can help you,, I take your Iranian Server with 600t of money xD :)

**Comment by howard-99** [comment]
300t best config

**Comment by arianamini1212** [comment]
can you limit connections to a port with iptables? can you send your codes to do it please

**Comment by arianamini1212** [comment]
can you limit connections to a port with iptables? can you send your codes to do it please




> lol I Do it By iptables
> 
> > > hi . thanks For your Work
> > > possible to create multi user at same port with multi GB Teraffic Option?
> > > I Want Tunnel Server_A to (x-ui)Server With SSH and need one port with multiuser .
> > > thanks
> > 
> > 
> > Hi ,,
> > If u want to tunnel to server without one port I can help you,, I take your Iranian Server with 600t of money xD :)
