### ISSUE TITLE
How can our IP server not be censored and filtered?

### ISSUE THREAD

**Issue by alirezashahrokhi** [FranzKafkaYu/x-ui#88]
Hello to all friends, unfortunately, after using 100 GB of traffic, my server IP was filtered and can no longer be used.  Do you have any suggestions to make filtering more difficult?

**Comment by FranzKafkaYu** [comment]
> Hello to all friends, unfortunately, after using 100 GB of traffic, my server IP was filtered and can no longer be used. Do you have any suggestions to make filtering more difficult?

@alirezashahrokhi  plz find some tutorials by youselef,not related about x-ui.
