### ISSUE TITLE
入站列表数量只能添加10个用户

### ISSUE THREAD

**Issue by wardxi** [FranzKafkaYu/x-ui#93]
入站列表数量添加到11个用户后，就无法正常访问互联网，删除一个到10个用户后，一切正常。请问这是什么原因呢？

**Comment by FranzKafkaYu** [comment]
无法复现,请确保服务正常运行。如有必要，请尽可能提供x-ui日志与xray服务日志。

**Comment by doutuo** [comment]
> 入站列表数量添加到11个用户后，就无法正常访问互联网，删除一个到10个用户后，一切正常。请问这是什么原因呢？

不会有这个情况的，我加了都有超过10个号了。应该是你前面10个号中，有些号是错误的，才会这样~ 你看下你的xray服务器是不是被停止了，当添加tls时，证书路径填错时，都会造成xray的服务被停止，只有删掉这个出错的用户时，才会恢复正常。

**Comment by doutuo** [comment]
所以我上次有提个需求，请求作者有闲时，帮弄个可以导入证书路径的，不用我们每次都去填入，减少出错的情况。

**Comment by wardxi** [comment]
对，我看了日志是Xray服务器停止了，检查了下是证书路径多打了一个空格，填写正确就OK了👍👍👍，感谢👍👍👍
