### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by therealaleph** [FranzKafkaYu/x-ui#95]
Hello, is there a way to add users without accessing the UI? like API or injecting the data on the DB? 
If so, please elaborate

**Comment by phonixsetup** [comment]
hi i have this problem too plz help

**Comment by FranzKafkaYu** [comment]
Impossible

**Comment by therealaleph** [comment]
No problemo, DB injection is not that hard. I found my way through pushing each uuid to the database and generating the link with the pushed data and restarting x-ui in the end.

**Comment by einkaaf** [comment]
> No problemo, DB injection is not that hard. I found my way through pushing each uuid to the database and generating the link with the pushed data and restarting x-ui in the end.

where is db ? how can access it ?

**Comment by therealaleph** [comment]
/etc/x-ui/x-ui.db

**Comment by therealaleph** [comment]
> > No problemo, DB injection is not that hard. I found my way through pushing each uuid to the database and generating the link with the pushed data and restarting x-ui in the end.
> 
> where is db ? how can access it ?

/etc/x-ui/x-ui.db
