### ISSUE TITLE
limite user conection

### ISSUE THREAD

**Issue by hamidlashani** [FranzKafkaYu/x-ui#98]
hi
how to added user limited conenct?

**Comment by erfankm7** [comment]
> 

Unfortunately , I don't think it is possible one connection per user , you should use OpenVPN or cisco any connect !
I hope @FranzKafkaYu will develop this necessary update <3

**Comment by FranzKafkaYu** [comment]
> hi how to added user limited conenct?

@hamidlashani  once again，x-ui is designed for personal use,such function won't implemented here.
