### ISSUE TITLE
点击面板设置报错

### ISSUE THREAD

**Issue by SugarFatFree** [FranzKafkaYu/x-ui#99]
一点击面板设置，就会自动重启面板，但是实际启动不成功，智能卸载再安装，请尽快修复

**Comment by FranzKafkaYu** [comment]
> 一点击面板设置，就会自动重启面板，但是实际启动不成功，智能卸载再安装，请尽快修复

@SugarFatFree  如果是404 page not found的错误,请查看issue区或者wiki文档.在没有任何错误截图,日志说明的情况下无法做出判断.
